package com.google.android.gms.measurement.internal;

import com.applovin.mediation.AppLovinUtils;
import com.google.firebase.analytics.FirebaseAnalytics;

/* JADX INFO: compiled from: r8-map-id-fe3a094fefd4170380533b2bee0729f4459fea13fa461ce83871544caf231bbc */
/* JADX INFO: loaded from: classes5.dex */
public final class zzjn {
    public static final String[] zza = {"ga_conversion", "engagement_time_msec", "exposure_time", "ad_event_id", AppLovinUtils.ServerParameterKeys.AD_UNIT_ID, "ga_error", "ga_error_value", "ga_error_length", "ga_event_origin", "ga_screen", "ga_screen_class", "ga_screen_id", "ga_previous_screen", "ga_previous_class", "ga_previous_id", "manual_tracking", "message_device_time", com.google.firebase.messaging.b.d.f52265f, "message_name", "message_time", "message_tracking_id", com.google.firebase.messaging.b.d.f52263d, "previous_app_version", "previous_os_version", "topic", "update_with_analytics", "previous_first_open_count", "system_app", "system_app_update", "previous_install_count", "ga_event_id", "ga_extra_params_ct", "ga_group_name", "ga_list_length", "ga_index", "ga_event_name", "campaign_info_source", "cached_campaign", "deferred_analytics_collection", "ga_session_number", "ga_session_id", "campaign_extra_referrer", "app_in_background", "firebase_feature_rollouts", "customer_type", "firebase_conversion", "firebase_error", "firebase_error_value", "firebase_error_length", "firebase_event_origin", "firebase_screen", "firebase_screen_class", "firebase_screen_id", "firebase_previous_screen", "firebase_previous_class", "firebase_previous_id", "session_number", "session_id"};
    public static final String[] zzb = {"_c", "_et", "_xt", "_aeid", "_ai", "_err", "_ev", "_el", bk.f.f21759c, "_sn", "_sc", "_si", "_pn", "_pc", "_pi", "_mst", com.google.firebase.messaging.b.f.f52289i, com.google.firebase.messaging.b.f.f52298r, com.google.firebase.messaging.b.f.f52287g, com.google.firebase.messaging.b.f.f52288h, "_nmtid", com.google.firebase.messaging.b.f.f52291k, "_pv", "_po", com.google.firebase.messaging.b.f.f52285e, "_uwa", "_pfo", "_sys", "_sysu", "_pin", "_eid", "_epc", "_gn", "_ll", "_i", "_en", "_cis", "_cc", "_dac", "_sno", "_sid", "_cer", "_aib", "_ffr", "_ct", "_c", "_err", "_ev", "_el", bk.f.f21759c, "_sn", "_sc", "_si", "_pn", "_pc", "_pi", "_sno", "_sid"};
    public static final String[] zzc = {"items"};
    public static final String[] zzd = {FirebaseAnalytics.d.f52078a0, FirebaseAnalytics.d.f52095j, FirebaseAnalytics.d.Y, FirebaseAnalytics.d.Z, "currency", "_ct", FirebaseAnalytics.d.f52082c0, "index", FirebaseAnalytics.d.f52109q, FirebaseAnalytics.d.W, FirebaseAnalytics.d.f52107p, FirebaseAnalytics.d.f52084d0, FirebaseAnalytics.d.f52086e0, FirebaseAnalytics.d.f52088f0, FirebaseAnalytics.d.f52090g0, FirebaseAnalytics.d.f52094i0, FirebaseAnalytics.d.f52092h0, FirebaseAnalytics.d.f52111r, FirebaseAnalytics.d.X, FirebaseAnalytics.d.f52098k0, FirebaseAnalytics.d.f52100l0, "price", FirebaseAnalytics.d.f52102m0, FirebaseAnalytics.d.f52104n0, FirebaseAnalytics.d.C, FirebaseAnalytics.d.E, FirebaseAnalytics.d.f52110q0, FirebaseAnalytics.d.I, "transaction_id", "value", "item_list", "checkout_step", "checkout_option", "item_location_id"};
}
