package iv;

import android.os.Parcel;
import dr.p0;
import oy.l;

/* JADX INFO: compiled from: r8-map-id-fe3a094fefd4170380533b2bee0729f4459fea13fa461ce83871544caf231bbc */
/* JADX INFO: loaded from: classes8.dex */
public interface b<T> {

    /* JADX INFO: compiled from: r8-map-id-fe3a094fefd4170380533b2bee0729f4459fea13fa461ce83871544caf231bbc */
    public static final class a {
        @l
        public static <T> T[] a(@l b<T> bVar, int i10) {
            throw new p0("Generated by Android Extensions automatically");
        }
    }

    T a(@l Parcel parcel);

    void b(T t10, @l Parcel parcel, int i10);

    @l
    T[] newArray(int i10);
}
