package com.sportybet.feature.payment.impl.security.nameupdate.presentation.activity.kekO;

/* JADX INFO: loaded from: classes.dex */
public class YAzniTbXHYQ {
    public static String BaGiJwnCpgx;
    public static String CtNrVzFA;
    public static String FNQWMzrMtOgVf;
    public static String FYbeEzKw;
    public static String HSuGWTWVblkwx;
    public static String HZaF;
    public static String JWwkDTdhZmIzTF;
    public static String JpQMEsDIJ;
    public static String KzAHJf;
    public static String PErgjNBvi;
    public static String PPqUVoG;
    public static String QAKPbamYrxSU;
    public static String QBUEckOgnwow;
    public static String RPmYCqqVvrAD;
    public static String SCLSZE;
    public static String SwUrQ;
    public static String TedtnHwav;
    public static String VyPvytXIF;
    public static String WkjNatCVpSn;
    public static String WxYJKOAKWtePr;
    public static String XJszdi;
    public static String YBExwhNKtQpvQe;
    public static String YEJXnZ;
    public static String ZnfHLViMIjQS;
    public static String bIFGHWZEnl;
    public static String bqdWBp;
    public static String czPIRF;
    public static String eQexOHXqjrg;
    public static String eRjimoYgdZ;
    public static String fNxlEECGtSWhElR;
    public static String fZh;
    public static String fmqvX;
    public static String gkmFBHCA;
    public static String lMwqhXCQphiKwjj;
    public static String oudiva;
    public static String rJKlSNPYfpq;
    public static String rqwU;
    public static String sOBFaAlZVWbxM;
    public static String siMBxzIdeVFjll;
    public static String uAwAVsO;
    public static String ulpwZFq;
    public static String wGR;
    public static String wJMcJiDMdP;
    public static String zzgvDYTOyU;
}
