package defpackage;

/* JADX INFO: loaded from: classes.dex */
public final class c9h0 {
    public static final long A;
    public static final long A0;
    public static final v1k A1;
    public static final long B;
    public static final t9i B0;
    public static final long B1;
    public static final long C;
    public static final v1k C0;
    public static final long C1;
    public static final t9i D;
    public static final long D0;
    public static final long D1;
    public static final v1k E;
    public static final long E0;
    public static final t9i E1;
    public static final long F;
    public static final long F0;
    public static final v1k F1;
    public static final long G;
    public static final t9i G0;
    public static final long G1;
    public static final long H;
    public static final v1k H0;
    public static final long H1;
    public static final t9i I;
    public static final long I0;
    public static final long I1;
    public static final v1k J;
    public static final long J0;
    public static final t9i J1;
    public static final long K;
    public static final long K0;
    public static final v1k K1;
    public static final long L;
    public static final t9i L0;
    public static final long L1;
    public static final long M;
    public static final v1k M0;
    public static final long M1;
    public static final t9i N;
    public static final long N0;
    public static final long N1;
    public static final v1k O;
    public static final long O0;
    public static final t9i O1;
    public static final long P;
    public static final long P0;
    public static final v1k P1;
    public static final long Q;
    public static final t9i Q0;
    public static final long Q1;
    public static final long R;
    public static final v1k R0;
    public static final long R1;
    public static final t9i S;
    public static final long S0;
    public static final long S1;
    public static final v1k T;
    public static final long T0;
    public static final t9i T1;
    public static final long U;
    public static final long U0;
    public static final long V;
    public static final t9i V0;
    public static final long W;
    public static final v1k W0;
    public static final t9i X;
    public static final long X0;
    public static final v1k Y;
    public static final long Y0;
    public static final long Z;
    public static final long Z0;
    public static final v1k a;
    public static final long a0;
    public static final t9i a1;
    public static final long b;
    public static final long b0;
    public static final v1k b1;
    public static final long c;
    public static final t9i c0;
    public static final long c1;
    public static final long d;
    public static final v1k d0;
    public static final long d1;
    public static final t9i e;
    public static final long e0;
    public static final long e1;
    public static final v1k f;
    public static final long f0;
    public static final t9i f1;
    public static final long g;
    public static final long g0;
    public static final v1k g1;
    public static final long h;
    public static final t9i h0;
    public static final long h1;
    public static final long i;
    public static final v1k i0;
    public static final long i1;
    public static final t9i j;
    public static final long j0;
    public static final long j1;
    public static final v1k k;
    public static final long k0;
    public static final t9i k1;
    public static final long l;
    public static final long l0;
    public static final v1k l1;
    public static final long m;
    public static final t9i m0;
    public static final long m1;
    public static final long n;
    public static final v1k n0;
    public static final long n1;
    public static final t9i o;
    public static final long o0;
    public static final long o1;
    public static final v1k p;
    public static final long p0;
    public static final t9i p1;
    public static final long q;
    public static final long q0;
    public static final v1k q1;
    public static final long r;
    public static final t9i r0;
    public static final long r1;
    public static final long s;
    public static final v1k s0;
    public static final long s1;
    public static final t9i t;
    public static final long t0;
    public static final long t1;
    public static final v1k u;
    public static final long u0;
    public static final t9i u1;
    public static final long v;
    public static final long v0;
    public static final v1k v1;
    public static final long w;
    public static final t9i w0;
    public static final long w1;
    public static final long x;
    public static final v1k x0;
    public static final long x1;
    public static final t9i y;
    public static final long y0;
    public static final long y1;
    public static final v1k z;
    public static final long z0;
    public static final t9i z1;

    static {
        v1k v1kVar = bah0.b;
        a = v1kVar;
        b = d2l.d(24.0d);
        c = d2l.f(16);
        d = d2l.d(0.5d);
        t9i t9iVar = bah0.e;
        e = t9iVar;
        f = v1kVar;
        g = d2l.d(20.0d);
        h = d2l.f(14);
        i = d2l.d(0.2d);
        j = t9iVar;
        k = v1kVar;
        l = d2l.d(16.0d);
        m = d2l.f(12);
        n = d2l.d(0.4d);
        o = t9iVar;
        v1k v1kVar2 = bah0.a;
        p = v1kVar2;
        q = d2l.d(64.0d);
        r = d2l.f(57);
        long jD = d2l.d(0.2d);
        d2l.a(jD);
        s = d2l.g(-omf0.c(jD), jD & 1095216660480L);
        t = t9iVar;
        u = v1kVar2;
        v = d2l.d(52.0d);
        w = d2l.f(45);
        x = d2l.d(0.0d);
        y = t9iVar;
        z = v1kVar2;
        A = d2l.d(44.0d);
        B = d2l.f(36);
        C = d2l.d(0.0d);
        D = t9iVar;
        E = v1kVar2;
        F = d2l.d(40.0d);
        G = d2l.f(32);
        H = d2l.d(0.0d);
        I = t9iVar;
        J = v1kVar2;
        K = d2l.d(36.0d);
        L = d2l.f(28);
        M = d2l.d(0.0d);
        N = t9iVar;
        O = v1kVar2;
        P = d2l.d(32.0d);
        Q = d2l.f(24);
        R = d2l.d(0.0d);
        S = t9iVar;
        T = v1kVar;
        U = d2l.d(20.0d);
        V = d2l.f(14);
        W = d2l.d(0.1d);
        t9i t9iVar2 = bah0.d;
        X = t9iVar2;
        Y = v1kVar;
        Z = d2l.d(16.0d);
        a0 = d2l.f(12);
        b0 = d2l.d(0.5d);
        c0 = t9iVar2;
        d0 = v1kVar;
        e0 = d2l.d(16.0d);
        f0 = d2l.f(11);
        g0 = d2l.d(0.5d);
        h0 = t9iVar2;
        i0 = v1kVar2;
        j0 = d2l.d(28.0d);
        k0 = d2l.f(22);
        l0 = d2l.d(0.0d);
        m0 = t9iVar;
        n0 = v1kVar;
        o0 = d2l.d(24.0d);
        p0 = d2l.f(16);
        q0 = d2l.d(0.2d);
        r0 = t9iVar2;
        s0 = v1kVar;
        t0 = d2l.d(20.0d);
        u0 = d2l.f(14);
        v0 = d2l.d(0.1d);
        w0 = t9iVar2;
        x0 = v1kVar;
        y0 = d2l.d(24.0d);
        z0 = d2l.f(16);
        A0 = d2l.d(0.15d);
        B0 = t9iVar2;
        C0 = v1kVar;
        D0 = d2l.d(20.0d);
        E0 = d2l.f(14);
        F0 = d2l.d(0.25d);
        G0 = t9iVar2;
        H0 = v1kVar;
        I0 = d2l.d(16.0d);
        J0 = d2l.f(12);
        K0 = d2l.d(0.4d);
        L0 = t9iVar2;
        M0 = v1kVar2;
        N0 = d2l.d(64.0d);
        O0 = d2l.f(57);
        P0 = d2l.f(0);
        Q0 = t9iVar2;
        R0 = v1kVar2;
        S0 = d2l.d(52.0d);
        T0 = d2l.f(45);
        U0 = d2l.f(0);
        V0 = t9iVar2;
        W0 = v1kVar2;
        X0 = d2l.d(44.0d);
        Y0 = d2l.f(36);
        Z0 = d2l.f(0);
        a1 = t9iVar2;
        b1 = v1kVar2;
        c1 = d2l.d(40.0d);
        d1 = d2l.f(32);
        e1 = d2l.f(0);
        f1 = t9iVar2;
        g1 = v1kVar2;
        h1 = d2l.d(36.0d);
        i1 = d2l.f(28);
        j1 = d2l.f(0);
        k1 = t9iVar2;
        l1 = v1kVar2;
        m1 = d2l.d(32.0d);
        n1 = d2l.f(24);
        o1 = d2l.f(0);
        p1 = t9iVar2;
        q1 = v1kVar;
        r1 = d2l.d(20.0d);
        s1 = d2l.f(14);
        t1 = d2l.d(0.1d);
        t9i t9iVar3 = bah0.c;
        u1 = t9iVar3;
        v1 = v1kVar;
        w1 = d2l.d(16.0d);
        x1 = d2l.f(12);
        y1 = d2l.d(0.5d);
        z1 = t9iVar3;
        A1 = v1kVar;
        B1 = d2l.d(16.0d);
        C1 = d2l.f(11);
        D1 = d2l.d(0.5d);
        E1 = t9iVar3;
        F1 = v1kVar2;
        G1 = d2l.d(28.0d);
        H1 = d2l.f(22);
        I1 = d2l.f(0);
        J1 = t9iVar2;
        K1 = v1kVar;
        L1 = d2l.d(24.0d);
        M1 = d2l.f(16);
        N1 = d2l.d(0.15d);
        O1 = t9iVar3;
        P1 = v1kVar;
        Q1 = d2l.d(20.0d);
        R1 = d2l.f(14);
        S1 = d2l.d(0.1d);
        T1 = t9iVar3;
    }
}
