package defpackage;

import com.sportygames.crash.models.header.snc.OdQr;

/* JADX INFO: loaded from: classes.dex */
public final class d68 {
    public final long A;
    public final long B;
    public final long C;
    public final long D;
    public final long E;
    public final long F;
    public final long G;
    public final long H;
    public final long I;
    public final long J;
    public final long K;
    public final long L;
    public final long M;
    public final long N;
    public final long O;
    public final long P;
    public final long Q;
    public final long R;
    public final long S;
    public final long T;
    public final long U;
    public final long V;
    public ak5 W;
    public ak5 X;
    public ak5 Y;
    public fg6 Z;
    public final long a;
    public fg6 a0;
    public final long b;
    public d780 b0;
    public final long c;
    public c1g0 c0;
    public final long d;
    public oj7 d0;
    public final long e;
    public gtc e0;
    public final long f;
    public u5n f0;
    public final long g;
    public u5n g0;
    public final long h;
    public hmv h0;
    public final long i;
    public ez90 i0;
    public final long j;
    public ene0 j0;
    public final long k;
    public lff0 k0;
    public final long l;
    public lff0 l0;
    public final long m;
    public final long n;
    public final long o;
    public final long p;
    public final long q;
    public final long r;
    public final long s;
    public final long t;
    public final long u;
    public final long v;
    public final long w;
    public final long x;
    public final long y;
    public final long z;

    public d68(long j, long j2, long j3, long j4, long j5, long j6, long j7, long j8, long j9, long j10, long j11, long j12, long j13, long j14, long j15, long j16, long j17, long j18, long j19, long j20, long j21, long j22, long j23, long j24, long j25, long j26, long j27, long j28, long j29, long j30, long j31, long j32, long j33, long j34, long j35, long j36, long j37, long j38, long j39, long j40, long j41, long j42, long j43, long j44, long j45, long j46, long j47, long j48) {
        this.a = j;
        this.b = j2;
        this.c = j3;
        this.d = j4;
        this.e = j5;
        this.f = j6;
        this.g = j7;
        this.h = j8;
        this.i = j9;
        this.j = j10;
        this.k = j11;
        this.l = j12;
        this.m = j13;
        this.n = j14;
        this.o = j15;
        this.p = j16;
        this.q = j17;
        this.r = j18;
        this.s = j19;
        this.t = j20;
        this.u = j21;
        this.v = j22;
        this.w = j23;
        this.x = j24;
        this.y = j25;
        this.z = j26;
        this.A = j27;
        this.B = j28;
        this.C = j29;
        this.D = j30;
        this.E = j31;
        this.F = j32;
        this.G = j33;
        this.H = j34;
        this.I = j35;
        this.J = j36;
        this.K = j37;
        this.L = j38;
        this.M = j39;
        this.N = j40;
        this.O = j41;
        this.P = j42;
        this.Q = j43;
        this.R = j44;
        this.S = j45;
        this.T = j46;
        this.U = j47;
        this.V = j48;
    }

    public final String toString() {
        StringBuilder sb = new StringBuilder("ColorScheme(primary=");
        ofz.a(this.a, "onPrimary=", sb);
        ofz.a(this.b, "primaryContainer=", sb);
        ofz.a(this.c, "onPrimaryContainer=", sb);
        long j = this.d;
        ofz.a(j, "inversePrimary=", sb);
        ofz.a(this.e, "secondary=", sb);
        ofz.a(this.f, "onSecondary=", sb);
        ofz.a(this.g, "secondaryContainer=", sb);
        ofz.a(this.h, "onSecondaryContainer=", sb);
        ofz.a(this.i, "tertiary=", sb);
        ofz.a(this.j, "onTertiary=", sb);
        ofz.a(this.k, "tertiaryContainer=", sb);
        ofz.a(this.l, "onTertiaryContainer=", sb);
        ofz.a(this.m, "background=", sb);
        ofz.a(this.n, "onBackground=", sb);
        ofz.a(this.o, "surface=", sb);
        ofz.a(this.p, "onSurface=", sb);
        ofz.a(this.q, "surfaceVariant=", sb);
        ofz.a(this.r, "onSurfaceVariant=", sb);
        ofz.a(this.s, "surfaceTint=", sb);
        ofz.a(this.t, "inverseSurface=", sb);
        ofz.a(this.u, "inverseOnSurface=", sb);
        ofz.a(this.v, "error=", sb);
        ofz.a(this.w, "onError=", sb);
        ofz.a(this.x, "errorContainer=", sb);
        ofz.a(this.y, OdQr.ivrkPXdIduG, sb);
        ofz.a(this.z, "outline=", sb);
        ofz.a(this.A, "outlineVariant=", sb);
        ofz.a(this.B, "scrim=", sb);
        ofz.a(this.C, "surfaceBright=", sb);
        ofz.a(this.D, "surfaceDim=", sb);
        ofz.a(this.E, "surfaceContainer=", sb);
        ofz.a(this.F, "surfaceContainerHigh=", sb);
        ofz.a(this.G, "surfaceContainerHighest=", sb);
        ofz.a(this.H, "surfaceContainerLow=", sb);
        ofz.a(this.I, "surfaceContainerLowest=", sb);
        ofz.a(this.J, "primaryFixed=", sb);
        ofz.a(this.K, "primaryFixedDim=", sb);
        ofz.a(this.L, "onPrimaryFixed=", sb);
        ofz.a(j, "onPrimaryFixedVariant=", sb);
        ofz.a(this.N, "secondaryFixed=", sb);
        ofz.a(this.O, "secondaryFixedDim=", sb);
        ofz.a(this.P, "onSecondaryFixed=", sb);
        ofz.a(this.Q, "onSecondaryFixedVariant=", sb);
        ofz.a(this.R, "tertiaryFixed=", sb);
        ofz.a(this.S, "tertiaryFixedDim=", sb);
        ofz.a(this.T, "onTertiaryFixed=", sb);
        ofz.a(this.U, "onTertiaryFixedVariant=", sb);
        sb.append((Object) j58.i(this.V));
        sb.append(')');
        return sb.toString();
    }
}
