package defpackage;

import android.view.View;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.cardview.widget.CardView;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.recyclerview.widget.RecyclerView;
import com.sportybet.android.gp.tz.R;

/* JADX INFO: loaded from: classes7.dex */
public final class eb7 extends RecyclerView.d0 {
    public final TextView A;
    public final TextView B;
    public final TextView C;
    public final ImageView D;
    public final CardView E;
    public final ConstraintLayout F;
    public final TextView G;
    public final ImageView H;
    public final LinearLayout I;
    public final LinearLayout J;
    public final LinearLayout K;
    public final ImageView a;
    public final ImageView b;
    public final ImageView c;
    public final TextView d;
    public final TextView e;
    public final TextView f;
    public final TextView i;
    public final TextView v;
    public final TextView w;
    public final TextView y;
    public final TextView z;

    public eb7(View view) {
        super(view);
        View viewFindViewById = view.findViewById(R.id.user_image);
        viewFindViewById.getClass();
        this.a = (ImageView) viewFindViewById;
        View viewFindViewById2 = view.findViewById(R.id.image);
        viewFindViewById2.getClass();
        this.b = (ImageView) viewFindViewById2;
        View viewFindViewById3 = view.findViewById(R.id.bot_image);
        viewFindViewById3.getClass();
        this.c = (ImageView) viewFindViewById3;
        View viewFindViewById4 = view.findViewById(R.id.bot_name);
        viewFindViewById4.getClass();
        this.d = (TextView) viewFindViewById4;
        View viewFindViewById5 = view.findViewById(R.id.cashed_out_text);
        viewFindViewById5.getClass();
        this.e = (TextView) viewFindViewById5;
        View viewFindViewById6 = view.findViewById(R.id.win_text);
        viewFindViewById6.getClass();
        this.f = (TextView) viewFindViewById6;
        View viewFindViewById7 = view.findViewById(R.id.round_text);
        viewFindViewById7.getClass();
        this.i = (TextView) viewFindViewById7;
        View viewFindViewById8 = view.findViewById(R.id.bet_text);
        viewFindViewById8.getClass();
        this.v = (TextView) viewFindViewById8;
        View viewFindViewById9 = view.findViewById(R.id.bot_message);
        viewFindViewById9.getClass();
        this.w = (TextView) viewFindViewById9;
        View viewFindViewById10 = view.findViewById(R.id.user_name);
        viewFindViewById10.getClass();
        this.y = (TextView) viewFindViewById10;
        View viewFindViewById11 = view.findViewById(R.id.coefficient);
        viewFindViewById11.getClass();
        this.z = (TextView) viewFindViewById11;
        View viewFindViewById12 = view.findViewById(R.id.win_amount);
        viewFindViewById12.getClass();
        this.A = (TextView) viewFindViewById12;
        View viewFindViewById13 = view.findViewById(R.id.round);
        viewFindViewById13.getClass();
        this.B = (TextView) viewFindViewById13;
        View viewFindViewById14 = view.findViewById(R.id.bet_amount);
        viewFindViewById14.getClass();
        this.C = (TextView) viewFindViewById14;
        View viewFindViewById15 = view.findViewById(R.id.fairness);
        viewFindViewById15.getClass();
        this.D = (ImageView) viewFindViewById15;
        View viewFindViewById16 = view.findViewById(R.id.json_layout);
        viewFindViewById16.getClass();
        this.E = (CardView) viewFindViewById16;
        View viewFindViewById17 = view.findViewById(R.id.gif_text_layout);
        viewFindViewById17.getClass();
        this.F = (ConstraintLayout) viewFindViewById17;
        View viewFindViewById18 = view.findViewById(R.id.name);
        viewFindViewById18.getClass();
        this.G = (TextView) viewFindViewById18;
        View viewFindViewById19 = view.findViewById(R.id.gif_item);
        viewFindViewById19.getClass();
        this.H = (ImageView) viewFindViewById19;
        View viewFindViewById20 = view.findViewById(R.id.background_header);
        viewFindViewById20.getClass();
        this.I = (LinearLayout) viewFindViewById20;
        View viewFindViewById21 = view.findViewById(R.id.background_body);
        viewFindViewById21.getClass();
        this.J = (LinearLayout) viewFindViewById21;
        View viewFindViewById22 = view.findViewById(R.id.background_header_profile);
        viewFindViewById22.getClass();
        this.K = (LinearLayout) viewFindViewById22;
    }
}
