package defpackage;

import android.view.View;
import android.widget.Button;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.compose.ui.platform.ComposeView;
import androidx.constraintlayout.motion.widget.MotionLayout;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.constraintlayout.widget.Group;
import androidx.drawerlayout.widget.DrawerLayout;
import androidx.recyclerview.widget.RecyclerView;
import com.google.android.material.button.MaterialButton;
import com.sportygames.commons.components.GiftToast;
import com.sportygames.commons.components.ProgressMeterComponent;
import com.sportygames.commons.components.SGHamburgerMenu;
import com.sportygames.commons.components.SgCommonHeaderContainer;
import com.sportygames.commons.components.SgCommonToastContainer;
import com.sportygames.commons.components.SgErrorToastContainer;
import com.sportygames.crash.components.header.DepositTooltipComponent;
import com.sportygames.rush.components.SgRushWaveLoader;
import com.sportygames.sportyherov2.components.SHKeypadContainer;

/* JADX INFO: loaded from: classes6.dex */
public final class eo80 implements g6i0 {
    public final ImageView A;
    public final TextView A0;
    public final Button B;
    public final TextView B0;
    public final Button C;
    public final TextView C0;
    public final Button D;
    public final TextView D0;
    public final Button E;
    public final TextView E0;
    public final Button F;
    public final TextView F0;
    public final Button G;
    public final TextView G0;
    public final Button H;
    public final TextView H0;
    public final Button I;
    public final TextView I0;
    public final Button J;
    public final SgRushWaveLoader J0;
    public final ImageView K;
    public final TextView K0;
    public final ConstraintLayout L;
    public final SgCommonToastContainer L0;
    public final MotionLayout M;
    public final RecyclerView N;
    public final DrawerLayout O;
    public final SgErrorToastContainer P;
    public final ImageView Q;
    public final ImageView R;
    public final ComposeView S;
    public final ImageView T;
    public final GiftToast U;
    public final SGHamburgerMenu V;
    public final SgCommonHeaderContainer W;
    public final FrameLayout X;
    public final SHKeypadContainer Y;
    public final ConstraintLayout Z;
    public final ConstraintLayout a;
    public final View a0;
    public final TextView b;
    public final View b0;
    public final Group c;
    public final View c0;
    public final Group d;
    public final ConstraintLayout d0;
    public final ConstraintLayout e;
    public final ConstraintLayout e0;
    public final ConstraintLayout f;
    public final SgRushWaveLoader f0;
    public final SgRushWaveLoader g0;
    public final SgRushWaveLoader h0;
    public final ComposeView i;
    public final SgRushWaveLoader i0;
    public final ConstraintLayout j0;
    public final FrameLayout k0;
    public final TextView l0;
    public final MaterialButton m0;
    public final MotionLayout n0;
    public final ProgressMeterComponent o0;
    public final TextView p0;
    public final DepositTooltipComponent q0;
    public final TextView r0;
    public final TextView s0;
    public final TextView t0;
    public final ImageView u0;
    public final ImageView v;
    public final TextView v0;
    public final ImageView w;
    public final TextView w0;
    public final TextView x0;
    public final ImageView y;
    public final TextView y0;
    public final ImageView z;
    public final TextView z0;

    public eo80(ConstraintLayout constraintLayout, TextView textView, Group group, Group group2, ConstraintLayout constraintLayout2, ConstraintLayout constraintLayout3, ComposeView composeView, ImageView imageView, ImageView imageView2, ImageView imageView3, ImageView imageView4, ImageView imageView5, Button button, Button button2, Button button3, Button button4, Button button5, Button button6, Button button7, Button button8, Button button9, ImageView imageView6, ConstraintLayout constraintLayout4, MotionLayout motionLayout, RecyclerView recyclerView, DrawerLayout drawerLayout, SgErrorToastContainer sgErrorToastContainer, ImageView imageView7, ImageView imageView8, ComposeView composeView2, ImageView imageView9, GiftToast giftToast, SGHamburgerMenu sGHamburgerMenu, SgCommonHeaderContainer sgCommonHeaderContainer, FrameLayout frameLayout, SHKeypadContainer sHKeypadContainer, ConstraintLayout constraintLayout5, View view, View view2, View view3, ConstraintLayout constraintLayout6, ConstraintLayout constraintLayout7, SgRushWaveLoader sgRushWaveLoader, SgRushWaveLoader sgRushWaveLoader2, SgRushWaveLoader sgRushWaveLoader3, SgRushWaveLoader sgRushWaveLoader4, ConstraintLayout constraintLayout8, FrameLayout frameLayout2, TextView textView2, MaterialButton materialButton, MotionLayout motionLayout2, ProgressMeterComponent progressMeterComponent, TextView textView3, DepositTooltipComponent depositTooltipComponent, TextView textView4, TextView textView5, TextView textView6, ImageView imageView10, TextView textView7, TextView textView8, TextView textView9, TextView textView10, TextView textView11, TextView textView12, TextView textView13, TextView textView14, TextView textView15, TextView textView16, TextView textView17, TextView textView18, TextView textView19, TextView textView20, SgRushWaveLoader sgRushWaveLoader5, TextView textView21, SgCommonToastContainer sgCommonToastContainer) {
        this.a = constraintLayout;
        this.b = textView;
        this.c = group;
        this.d = group2;
        this.e = constraintLayout2;
        this.f = constraintLayout3;
        this.i = composeView;
        this.v = imageView;
        this.w = imageView2;
        this.y = imageView3;
        this.z = imageView4;
        this.A = imageView5;
        this.B = button;
        this.C = button2;
        this.D = button3;
        this.E = button4;
        this.F = button5;
        this.G = button6;
        this.H = button7;
        this.I = button8;
        this.J = button9;
        this.K = imageView6;
        this.L = constraintLayout4;
        this.M = motionLayout;
        this.N = recyclerView;
        this.O = drawerLayout;
        this.P = sgErrorToastContainer;
        this.Q = imageView7;
        this.R = imageView8;
        this.S = composeView2;
        this.T = imageView9;
        this.U = giftToast;
        this.V = sGHamburgerMenu;
        this.W = sgCommonHeaderContainer;
        this.X = frameLayout;
        this.Y = sHKeypadContainer;
        this.Z = constraintLayout5;
        this.a0 = view;
        this.b0 = view2;
        this.c0 = view3;
        this.d0 = constraintLayout6;
        this.e0 = constraintLayout7;
        this.f0 = sgRushWaveLoader;
        this.g0 = sgRushWaveLoader2;
        this.h0 = sgRushWaveLoader3;
        this.i0 = sgRushWaveLoader4;
        this.j0 = constraintLayout8;
        this.k0 = frameLayout2;
        this.l0 = textView2;
        this.m0 = materialButton;
        this.n0 = motionLayout2;
        this.o0 = progressMeterComponent;
        this.p0 = textView3;
        this.q0 = depositTooltipComponent;
        this.r0 = textView4;
        this.s0 = textView5;
        this.t0 = textView6;
        this.u0 = imageView10;
        this.v0 = textView7;
        this.w0 = textView8;
        this.x0 = textView9;
        this.y0 = textView10;
        this.z0 = textView11;
        this.A0 = textView12;
        this.B0 = textView13;
        this.C0 = textView14;
        this.D0 = textView15;
        this.E0 = textView16;
        this.F0 = textView17;
        this.G0 = textView18;
        this.H0 = textView19;
        this.I0 = textView20;
        this.J0 = sgRushWaveLoader5;
        this.K0 = textView21;
        this.L0 = sgCommonToastContainer;
    }

    @Override // defpackage.g6i0
    public final View getRoot() {
        return this.a;
    }
}
