package defpackage;

import android.view.View;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ProgressBar;
import android.widget.TextView;
import androidx.appcompat.widget.AppCompatImageView;
import androidx.appcompat.widget.AppCompatTextView;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.constraintlayout.widget.Group;
import com.sportybet.android.widget.EarlyPayoutCheckbox;
import com.sportybet.android.widget.OneUpTwoUpItemControl;
import com.sportybet.plugin.realsports.betslip.simulate.SimulateAutoBetPanel;
import com.sportybet.plugin.realsports.betslip.virtualkeyboard.KeyboardView;
import com.sportybet.plugin.realsports.betslip.widget.QuickBetView;

/* JADX INFO: loaded from: classes7.dex */
public final class ijd0 implements g6i0 {
    public final ConstraintLayout A;
    public final ImageView B;
    public final ConstraintLayout C;
    public final TextView D;
    public final KeyboardView E;
    public final EarlyPayoutCheckbox F;
    public final TextView G;
    public final Group H;
    public final TextView I;
    public final ConstraintLayout J;
    public final TextView K;
    public final Group L;
    public final TextView M;
    public final ConstraintLayout N;
    public final TextView O;
    public final TextView P;
    public final TextView Q;
    public final LinearLayout R;
    public final TextView S;
    public final LinearLayout T;
    public final ImageView U;
    public final EarlyPayoutCheckbox V;
    public final OneUpTwoUpItemControl W;
    public final ProgressBar X;
    public final TextView Y;
    public final LinearLayout Z;
    public final QuickBetView a;
    public final TextView a0;
    public final Button b;
    public final Group b0;
    public final TextView c;
    public final TextView c0;
    public final ConstraintLayout d;
    public final Group d0;
    public final ImageView e;
    public final TextView e0;
    public final ConstraintLayout f;
    public final TextView f0;
    public final LinearLayout g0;
    public final LinearLayout h0;
    public final TextView i;
    public final TextView i0;
    public final ImageView j0;
    public final SimulateAutoBetPanel k0;
    public final EditText l0;
    public final TextView m0;
    public final AppCompatImageView n0;
    public final ImageView o0;
    public final TextView p0;
    public final TextView q0;
    public final TextView r0;
    public final TextView s0;
    public final TextView t0;
    public final AppCompatTextView u0;
    public final LinearLayout v;
    public final TextView w;
    public final TextView y;
    public final CheckBox z;

    public ijd0(QuickBetView quickBetView, Button button, TextView textView, ConstraintLayout constraintLayout, ImageView imageView, ConstraintLayout constraintLayout2, TextView textView2, LinearLayout linearLayout, TextView textView3, TextView textView4, CheckBox checkBox, ConstraintLayout constraintLayout3, ImageView imageView2, ConstraintLayout constraintLayout4, TextView textView5, KeyboardView keyboardView, EarlyPayoutCheckbox earlyPayoutCheckbox, TextView textView6, Group group, TextView textView7, ConstraintLayout constraintLayout5, TextView textView8, Group group2, TextView textView9, ConstraintLayout constraintLayout6, TextView textView10, TextView textView11, TextView textView12, LinearLayout linearLayout2, TextView textView13, LinearLayout linearLayout3, ImageView imageView3, EarlyPayoutCheckbox earlyPayoutCheckbox2, OneUpTwoUpItemControl oneUpTwoUpItemControl, ProgressBar progressBar, TextView textView14, LinearLayout linearLayout4, TextView textView15, Group group3, TextView textView16, Group group4, TextView textView17, TextView textView18, LinearLayout linearLayout5, LinearLayout linearLayout6, TextView textView19, ImageView imageView4, SimulateAutoBetPanel simulateAutoBetPanel, EditText editText, TextView textView20, AppCompatImageView appCompatImageView, ImageView imageView5, TextView textView21, TextView textView22, TextView textView23, TextView textView24, TextView textView25, AppCompatTextView appCompatTextView) {
        this.a = quickBetView;
        this.b = button;
        this.c = textView;
        this.d = constraintLayout;
        this.e = imageView;
        this.f = constraintLayout2;
        this.i = textView2;
        this.v = linearLayout;
        this.w = textView3;
        this.y = textView4;
        this.z = checkBox;
        this.A = constraintLayout3;
        this.B = imageView2;
        this.C = constraintLayout4;
        this.D = textView5;
        this.E = keyboardView;
        this.F = earlyPayoutCheckbox;
        this.G = textView6;
        this.H = group;
        this.I = textView7;
        this.J = constraintLayout5;
        this.K = textView8;
        this.L = group2;
        this.M = textView9;
        this.N = constraintLayout6;
        this.O = textView10;
        this.P = textView11;
        this.Q = textView12;
        this.R = linearLayout2;
        this.S = textView13;
        this.T = linearLayout3;
        this.U = imageView3;
        this.V = earlyPayoutCheckbox2;
        this.W = oneUpTwoUpItemControl;
        this.X = progressBar;
        this.Y = textView14;
        this.Z = linearLayout4;
        this.a0 = textView15;
        this.b0 = group3;
        this.c0 = textView16;
        this.d0 = group4;
        this.e0 = textView17;
        this.f0 = textView18;
        this.g0 = linearLayout5;
        this.h0 = linearLayout6;
        this.i0 = textView19;
        this.j0 = imageView4;
        this.k0 = simulateAutoBetPanel;
        this.l0 = editText;
        this.m0 = textView20;
        this.n0 = appCompatImageView;
        this.o0 = imageView5;
        this.p0 = textView21;
        this.q0 = textView22;
        this.r0 = textView23;
        this.s0 = textView24;
        this.t0 = textView25;
        this.u0 = appCompatTextView;
    }

    @Override // defpackage.g6i0
    public final View getRoot() {
        return this.a;
    }
}
