package defpackage;

/* JADX INFO: loaded from: classes.dex */
public final class k58 {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final long D;
    public static final long E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final long I;
    public static final long J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final long N;
    public static final long O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final long S;
    public static final long T;
    public static final long U;
    public static final long a;
    public static final long b;
    public static final long c;
    public static final long d;
    public static final long e;
    public static final long f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final long j;
    public static final long k;
    public static final long l;
    public static final long m;
    public static final long n;
    public static final long o;
    public static final long p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final long t;
    public static final long u;
    public static final long v;
    public static final long w;
    public static final long x;
    public static final long y;
    public static final long z;

    static {
        long j2 = irz.q;
        a = j2;
        b = irz.f;
        c = irz.d;
        d = irz.m;
        e = irz.H;
        long j3 = irz.s;
        f = j3;
        g = j3;
        h = irz.c;
        i = irz.g;
        j = irz.F;
        long j4 = irz.J;
        k = j4;
        l = irz.D;
        long j5 = irz.G;
        m = j5;
        n = irz.M;
        long j6 = irz.Q;
        o = j6;
        p = irz.K;
        long j7 = irz.N;
        q = j7;
        r = j3;
        s = irz.B;
        t = irz.T;
        long j8 = irz.X;
        u = j8;
        v = irz.R;
        long j9 = irz.U;
        w = j9;
        x = irz.A;
        long j10 = irz.y;
        y = j10;
        long j11 = irz.I;
        z = j11;
        A = j5;
        B = j4;
        C = j11;
        D = irz.h;
        long j12 = irz.P;
        E = j12;
        F = j7;
        G = j6;
        H = j12;
        I = j2;
        J = irz.o;
        K = irz.k;
        L = irz.l;
        M = irz.n;
        N = irz.i;
        O = irz.p;
        P = j2;
        Q = j10;
        long j13 = irz.W;
        R = j13;
        S = j9;
        T = j8;
        U = j13;
    }
}
