package defpackage;

import android.view.View;
import android.widget.CheckBox;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ProgressBar;
import android.widget.RelativeLayout;
import android.widget.SeekBar;
import android.widget.TextView;
import androidx.appcompat.widget.AppCompatTextView;
import androidx.compose.ui.platform.ComposeView;
import androidx.constraintlayout.widget.ConstraintLayout;
import com.google.android.flexbox.FlexboxLayout;
import com.sportybet.android.widget.ArrowButton;
import com.sportybet.android.widget.BetSlipHintView;
import com.sportybet.plugin.realsports.betslip.simulate.SimulateAutoBetPanel;
import com.sportybet.plugin.realsports.betslip.virtualkeyboard.EditTextWithKeyBoard;
import com.sportybet.plugin.realsports.betslip.widget.IndicatorLayout;

/* JADX INFO: loaded from: classes7.dex */
public final class mgd0 implements g6i0 {
    public final ProgressBar A;
    public final AppCompatTextView A0;
    public final AppCompatTextView B;
    public final ComposeView B0;
    public final TextView C;
    public final CheckBox C0;
    public final LinearLayout D;
    public final View D0;
    public final CheckBox E;
    public final ConstraintLayout E0;
    public final AppCompatTextView F;
    public final ConstraintLayout F0;
    public final TextView G;
    public final ConstraintLayout G0;
    public final RelativeLayout H;
    public final SimulateAutoBetPanel H0;
    public final ImageView I;
    public final CheckBox I0;
    public final BetSlipHintView J;
    public final LinearLayout J0;
    public final RelativeLayout K;
    public final View K0;
    public final TextView L;
    public final TextView L0;
    public final TextView M;
    public final EditTextWithKeyBoard M0;
    public final CheckBox N;
    public final TextView N0;
    public final TextView O;
    public final FlexboxLayout O0;
    public final BetSlipHintView P;
    public final ComposeView P0;
    public final ConstraintLayout Q;
    public final CheckBox Q0;
    public final TextView R;
    public final View R0;
    public final TextView S;
    public final LinearLayout S0;
    public final IndicatorLayout T;
    public final ConstraintLayout T0;
    public final CheckBox U;
    public final RelativeLayout U0;
    public final View V;
    public final TextView V0;
    public final ConstraintLayout W;
    public final CheckBox W0;
    public final CheckBox X;
    public final LinearLayout X0;
    public final View Y;
    public final View Y0;
    public final View Z;
    public final TextView Z0;
    public final RelativeLayout a;
    public final ConstraintLayout a0;
    public final TextView a1;
    public final ImageView b;
    public final TextView b0;
    public final TextView b1;
    public final TextView c;
    public final View c0;
    public final BetSlipHintView d;
    public final CheckBox d0;
    public final TextView e;
    public final LinearLayout e0;
    public final ArrowButton f;
    public final View f0;
    public final TextView g0;
    public final TextView h0;
    public final ArrowButton i;
    public final View i0;
    public final EditTextWithKeyBoard j0;
    public final RelativeLayout k0;
    public final SimulateAutoBetPanel l0;
    public final TextView m0;
    public final TextView n0;
    public final TextView o0;
    public final TextView p0;
    public final ConstraintLayout q0;
    public final TextView r0;
    public final CheckBox s0;
    public final ImageView t0;
    public final TextView u0;
    public final ConstraintLayout v;
    public final TextView v0;
    public final ComposeView w;
    public final SeekBar w0;
    public final BetSlipHintView x0;
    public final TextView y;
    public final TextView y0;
    public final ConstraintLayout z;
    public final RelativeLayout z0;

    public mgd0(RelativeLayout relativeLayout, ImageView imageView, TextView textView, BetSlipHintView betSlipHintView, TextView textView2, ArrowButton arrowButton, ArrowButton arrowButton2, ConstraintLayout constraintLayout, ComposeView composeView, TextView textView3, ConstraintLayout constraintLayout2, ProgressBar progressBar, AppCompatTextView appCompatTextView, TextView textView4, LinearLayout linearLayout, CheckBox checkBox, AppCompatTextView appCompatTextView2, TextView textView5, RelativeLayout relativeLayout2, ImageView imageView2, BetSlipHintView betSlipHintView2, RelativeLayout relativeLayout3, TextView textView6, TextView textView7, CheckBox checkBox2, TextView textView8, BetSlipHintView betSlipHintView3, ConstraintLayout constraintLayout3, TextView textView9, TextView textView10, IndicatorLayout indicatorLayout, CheckBox checkBox3, View view, ConstraintLayout constraintLayout4, CheckBox checkBox4, View view2, View view3, ConstraintLayout constraintLayout5, TextView textView11, View view4, CheckBox checkBox5, LinearLayout linearLayout2, View view5, TextView textView12, TextView textView13, View view6, EditTextWithKeyBoard editTextWithKeyBoard, RelativeLayout relativeLayout4, SimulateAutoBetPanel simulateAutoBetPanel, TextView textView14, TextView textView15, TextView textView16, TextView textView17, ConstraintLayout constraintLayout6, TextView textView18, CheckBox checkBox6, ImageView imageView3, TextView textView19, TextView textView20, SeekBar seekBar, BetSlipHintView betSlipHintView4, TextView textView21, RelativeLayout relativeLayout5, AppCompatTextView appCompatTextView3, ComposeView composeView2, CheckBox checkBox7, View view7, ConstraintLayout constraintLayout7, ConstraintLayout constraintLayout8, ConstraintLayout constraintLayout9, SimulateAutoBetPanel simulateAutoBetPanel2, CheckBox checkBox8, LinearLayout linearLayout3, View view8, TextView textView22, EditTextWithKeyBoard editTextWithKeyBoard2, TextView textView23, FlexboxLayout flexboxLayout, ComposeView composeView3, CheckBox checkBox9, View view9, LinearLayout linearLayout4, ConstraintLayout constraintLayout10, ConstraintLayout constraintLayout11, RelativeLayout relativeLayout6, TextView textView24, CheckBox checkBox10, LinearLayout linearLayout5, View view10, TextView textView25, TextView textView26, TextView textView27, TextView textView28) {
        this.a = relativeLayout;
        this.b = imageView;
        this.c = textView;
        this.d = betSlipHintView;
        this.e = textView2;
        this.f = arrowButton;
        this.i = arrowButton2;
        this.v = constraintLayout;
        this.w = composeView;
        this.y = textView3;
        this.z = constraintLayout2;
        this.A = progressBar;
        this.B = appCompatTextView;
        this.C = textView4;
        this.D = linearLayout;
        this.E = checkBox;
        this.F = appCompatTextView2;
        this.G = textView5;
        this.H = relativeLayout2;
        this.I = imageView2;
        this.J = betSlipHintView2;
        this.K = relativeLayout3;
        this.L = textView6;
        this.M = textView7;
        this.N = checkBox2;
        this.O = textView8;
        this.P = betSlipHintView3;
        this.Q = constraintLayout3;
        this.R = textView9;
        this.S = textView10;
        this.T = indicatorLayout;
        this.U = checkBox3;
        this.V = view;
        this.W = constraintLayout4;
        this.X = checkBox4;
        this.Y = view2;
        this.Z = view3;
        this.a0 = constraintLayout5;
        this.b0 = textView11;
        this.c0 = view4;
        this.d0 = checkBox5;
        this.e0 = linearLayout2;
        this.f0 = view5;
        this.g0 = textView12;
        this.h0 = textView13;
        this.i0 = view6;
        this.j0 = editTextWithKeyBoard;
        this.k0 = relativeLayout4;
        this.l0 = simulateAutoBetPanel;
        this.m0 = textView14;
        this.n0 = textView15;
        this.o0 = textView16;
        this.p0 = textView17;
        this.q0 = constraintLayout6;
        this.r0 = textView18;
        this.s0 = checkBox6;
        this.t0 = imageView3;
        this.u0 = textView19;
        this.v0 = textView20;
        this.w0 = seekBar;
        this.x0 = betSlipHintView4;
        this.y0 = textView21;
        this.z0 = relativeLayout5;
        this.A0 = appCompatTextView3;
        this.B0 = composeView2;
        this.C0 = checkBox7;
        this.D0 = view7;
        this.E0 = constraintLayout7;
        this.F0 = constraintLayout8;
        this.G0 = constraintLayout9;
        this.H0 = simulateAutoBetPanel2;
        this.I0 = checkBox8;
        this.J0 = linearLayout3;
        this.K0 = view8;
        this.L0 = textView22;
        this.M0 = editTextWithKeyBoard2;
        this.N0 = textView23;
        this.O0 = flexboxLayout;
        this.P0 = composeView3;
        this.Q0 = checkBox9;
        this.R0 = view9;
        this.S0 = linearLayout4;
        this.T0 = constraintLayout11;
        this.U0 = relativeLayout6;
        this.V0 = textView24;
        this.W0 = checkBox10;
        this.X0 = linearLayout5;
        this.Y0 = view10;
        this.Z0 = textView25;
        this.a1 = textView27;
        this.b1 = textView28;
    }

    @Override // defpackage.g6i0
    public final View getRoot() {
        return this.a;
    }
}
