package defpackage;

import android.view.View;
import android.widget.TextView;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.recyclerview.widget.RecyclerView;
import com.google.android.material.floatingactionbutton.FloatingActionButton;

/* JADX INFO: loaded from: classes6.dex */
public final class mq80 implements g6i0 {
    public final TextView A;
    public final TextView B;
    public final TextView C;
    public final TextView D;
    public final TextView E;
    public final TextView F;
    public final TextView G;
    public final TextView H;
    public final TextView I;
    public final TextView J;
    public final TextView K;
    public final TextView L;
    public final TextView M;
    public final TextView N;
    public final TextView O;
    public final TextView P;
    public final TextView Q;
    public final TextView R;
    public final TextView S;
    public final TextView T;
    public final TextView U;
    public final TextView V;
    public final TextView W;
    public final TextView X;
    public final TextView Y;
    public final TextView Z;
    public final ConstraintLayout a;
    public final TextView a0;
    public final FloatingActionButton b;
    public final TextView b0;
    public final View c;
    public final TextView c0;
    public final TextView d;
    public final TextView d0;
    public final TextView e;
    public final TextView e0;
    public final TextView f;
    public final TextView f0;
    public final TextView g0;
    public final TextView h0;
    public final TextView i;
    public final TextView i0;
    public final TextView j0;
    public final TextView k0;
    public final TextView l0;
    public final TextView m0;
    public final TextView n0;
    public final TextView o0;
    public final TextView p0;
    public final TextView q0;
    public final TextView r0;
    public final TextView s0;
    public final TextView t0;
    public final TextView u0;
    public final TextView v;
    public final TextView v0;
    public final TextView w;
    public final RecyclerView w0;
    public final TextView x0;
    public final TextView y;
    public final TextView z;

    public mq80(ConstraintLayout constraintLayout, FloatingActionButton floatingActionButton, View view, TextView textView, TextView textView2, TextView textView3, TextView textView4, TextView textView5, TextView textView6, TextView textView7, TextView textView8, TextView textView9, TextView textView10, TextView textView11, TextView textView12, TextView textView13, TextView textView14, TextView textView15, TextView textView16, TextView textView17, TextView textView18, TextView textView19, TextView textView20, TextView textView21, TextView textView22, TextView textView23, TextView textView24, TextView textView25, TextView textView26, TextView textView27, TextView textView28, TextView textView29, TextView textView30, TextView textView31, TextView textView32, TextView textView33, TextView textView34, TextView textView35, TextView textView36, TextView textView37, TextView textView38, TextView textView39, TextView textView40, TextView textView41, TextView textView42, TextView textView43, TextView textView44, TextView textView45, TextView textView46, TextView textView47, TextView textView48, TextView textView49, TextView textView50, TextView textView51, TextView textView52, TextView textView53, TextView textView54, TextView textView55, TextView textView56, RecyclerView recyclerView, TextView textView57) {
        this.a = constraintLayout;
        this.b = floatingActionButton;
        this.c = view;
        this.d = textView;
        this.e = textView2;
        this.f = textView3;
        this.i = textView4;
        this.v = textView5;
        this.w = textView6;
        this.y = textView7;
        this.z = textView8;
        this.A = textView9;
        this.B = textView10;
        this.C = textView11;
        this.D = textView12;
        this.E = textView13;
        this.F = textView14;
        this.G = textView15;
        this.H = textView16;
        this.I = textView17;
        this.J = textView18;
        this.K = textView19;
        this.L = textView20;
        this.M = textView21;
        this.N = textView22;
        this.O = textView23;
        this.P = textView24;
        this.Q = textView25;
        this.R = textView26;
        this.S = textView27;
        this.T = textView28;
        this.U = textView29;
        this.V = textView30;
        this.W = textView31;
        this.X = textView32;
        this.Y = textView33;
        this.Z = textView34;
        this.a0 = textView35;
        this.b0 = textView36;
        this.c0 = textView37;
        this.d0 = textView38;
        this.e0 = textView39;
        this.f0 = textView40;
        this.g0 = textView41;
        this.h0 = textView42;
        this.i0 = textView43;
        this.j0 = textView44;
        this.k0 = textView45;
        this.l0 = textView46;
        this.m0 = textView47;
        this.n0 = textView48;
        this.o0 = textView49;
        this.p0 = textView50;
        this.q0 = textView51;
        this.r0 = textView52;
        this.s0 = textView53;
        this.t0 = textView54;
        this.u0 = textView55;
        this.v0 = textView56;
        this.w0 = recyclerView;
        this.x0 = textView57;
    }

    @Override // defpackage.g6i0
    public final View getRoot() {
        return this.a;
    }
}
