package defpackage;

import com.sportybet.android.instantwin.presentation.openbet.fNZf.oLsIjJCWb;
import com.sportybet.plugin.webcontainer.caipiao.jsplugin.JsPluginCommon;
import com.sportygames.newcms.CMSRes;

/* JADX INFO: loaded from: classes2.dex */
public class mu00 extends jp5 {
    public final CMSRes A;
    public final CMSRes A0;
    public final CMSRes A1;
    public final CMSRes B;
    public final CMSRes B0;
    public final CMSRes B1;
    public final CMSRes C;
    public final CMSRes C0;
    public final CMSRes C1;
    public final CMSRes D;
    public final CMSRes D0;
    public final CMSRes D1;
    public final CMSRes E;
    public final CMSRes E0;
    public final CMSRes E1;
    public final CMSRes F;
    public final CMSRes F0;
    public final CMSRes F1;
    public final CMSRes G;
    public final CMSRes G0;
    public final CMSRes G1;
    public final CMSRes H;
    public final CMSRes H0;
    public final CMSRes H1;
    public final CMSRes I;
    public final CMSRes I0;
    public final CMSRes I1;
    public final CMSRes J;
    public final CMSRes J0;
    public final CMSRes J1;
    public final CMSRes K;
    public final CMSRes K0;
    public final CMSRes K1;
    public final CMSRes L;
    public final CMSRes L0;
    public final CMSRes L1;
    public final CMSRes M;
    public final CMSRes M0;
    public final CMSRes M1;
    public final CMSRes N;
    public final CMSRes N0;
    public final CMSRes N1;
    public final CMSRes O;
    public final CMSRes O0;
    public final CMSRes O1;
    public final CMSRes P;
    public final CMSRes P0;
    public final CMSRes P1;
    public final CMSRes Q;
    public final CMSRes Q0;
    public final CMSRes Q1;
    public final CMSRes R;
    public final CMSRes R0;
    public final CMSRes R1;
    public final CMSRes S;
    public final CMSRes S0;
    public final CMSRes S1;
    public final CMSRes T;
    public final CMSRes T0;
    public final CMSRes T1;
    public final CMSRes U;
    public final CMSRes U0;
    public final CMSRes U1;
    public final CMSRes V;
    public final CMSRes V0;
    public final CMSRes V1;
    public final CMSRes W;
    public final CMSRes W0;
    public final CMSRes W1;
    public final CMSRes X;
    public final CMSRes X0;
    public final CMSRes X1;
    public final CMSRes Y;
    public final CMSRes Y0;
    public final CMSRes Y1;
    public final CMSRes Z;
    public final CMSRes Z0;
    public final CMSRes Z1;
    public final CMSRes a0;
    public final CMSRes a1;
    public final CMSRes a2;
    public final int b;
    public final CMSRes b0;
    public final CMSRes b1;
    public final CMSRes c;
    public final CMSRes c0;
    public final CMSRes c1;
    public final CMSRes d;
    public final CMSRes d0;
    public final CMSRes d1;
    public final CMSRes e;
    public final CMSRes e0;
    public final CMSRes e1;
    public final CMSRes f;
    public final CMSRes f0;
    public final CMSRes f1;
    public final CMSRes g;
    public final CMSRes g0;
    public final CMSRes g1;
    public final CMSRes h;
    public final CMSRes h0;
    public final CMSRes h1;
    public final CMSRes i;
    public final CMSRes i0;
    public final CMSRes i1;
    public final CMSRes j;
    public final CMSRes j0;
    public final CMSRes j1;
    public final CMSRes k;
    public final CMSRes k0;
    public final CMSRes k1;
    public final CMSRes l;
    public final CMSRes l0;
    public final CMSRes l1;
    public final CMSRes m;
    public final CMSRes m0;
    public final CMSRes m1;
    public final CMSRes n;
    public final CMSRes n0;
    public final CMSRes n1;
    public final CMSRes o;
    public final CMSRes o0;
    public final CMSRes o1;
    public final CMSRes p;
    public final CMSRes p0;
    public final CMSRes p1;
    public final CMSRes q;
    public final CMSRes q0;
    public final CMSRes q1;
    public final CMSRes r;
    public final CMSRes r0;
    public final CMSRes r1;
    public final CMSRes s;
    public final CMSRes s0;
    public final CMSRes s1;
    public final CMSRes t;
    public final CMSRes t0;
    public final CMSRes t1;
    public final CMSRes u;
    public final CMSRes u0;
    public final CMSRes u1;
    public final CMSRes v;
    public final CMSRes v0;
    public final CMSRes v1;
    public final CMSRes w;
    public final CMSRes w0;
    public final CMSRes w1;
    public final CMSRes x;
    public final CMSRes x0;
    public final CMSRes x1;
    public final CMSRes y;
    public final CMSRes y0;
    public final CMSRes y1;
    public final CMSRes z;
    public final CMSRes z0;
    public final CMSRes z1;

    /* JADX INFO: loaded from: classes7.dex */
    public static final class a {
    }

    @Override // defpackage.jp5
    public final int t() {
        return this.b;
    }

    /* JADX WARN: 'super' call moved to the top of the method (can break code semantics) */
    public mu00(on5 on5Var) {
        super(on5Var);
        on5Var.getClass();
        this.b = a.class.hashCode();
        nn5 nn5Var = nn5.Image;
        this.c = on5.h(this, this, "sg_piggy_bash_game", "red_pig", nn5Var, null, 8);
        this.d = on5.h(this, this, "sg_piggy_bash_game", "blue_pig", nn5Var, null, 8);
        this.e = on5.h(this, this, "sg_piggy_bash_game", "green_pig", nn5Var, null, 8);
        this.f = on5.h(this, this, "sg_piggy_bash_game", "green_pig_with_hammers", nn5Var, null, 8);
        this.g = on5.h(this, this, "sg_piggy_bash_game", "robotic_pig", nn5Var, null, 8);
        this.h = on5.h(this, this, "sg_piggy_bash_game", "russo_one_font", nn5.Font, null, 8);
        this.i = on5.h(this, this, "sg_piggy_bash_game", "asian_theme_background", nn5Var, null, 8);
        this.j = on5.h(this, this, "sg_piggy_bash_game", "wild_west_theme_background", nn5Var, null, 8);
        this.k = on5.h(this, this, "sg_piggy_bash_game", "robotic_theme_background", nn5Var, null, 8);
        this.l = on5.h(this, this, "sg_piggy_bash_game", "jungle_theme_background", nn5Var, null, 8);
        this.m = on5.h(this, this, "sg_piggy_bash_game", "smash_the_pig", null, null, 12);
        this.n = on5.h(this, this, "sg_piggy_bash_game", "unlock_the_treasure", null, null, 12);
        this.o = on5.h(this, this, "sg_piggy_bash_game", "choose_event_to_play", null, null, 12);
        this.p = on5.h(this, this, "sg_piggy_bash_game", "win_up_to", null, null, 12);
        this.q = on5.h(this, this, "sg_piggy_bash_game", "join_room", null, null, 12);
        this.r = on5.h(this, this, "sg_piggy_bash_game", "special_event", null, null, 12);
        this.s = on5.h(this, this, "sg_piggy_bash_game", "coin_stack_image", nn5Var, null, 8);
        this.t = on5.h(this, this, "sg_piggy_bash_game", "groups_image", nn5Var, null, 8);
        this.u = on5.h(this, this, "sg_piggy_bash_game", "something_went_wrong", null, null, 12);
        this.v = on5.h(this, this, "sg_piggy_bash_game", "retry", null, null, 12);
        this.w = on5.h(this, this, "sg_piggy_bash_game", "header_logo", nn5Var, null, 8);
        this.x = on5.h(this, this, "sg_piggy_bash_game", "header_wallet_background", nn5Var, null, 8);
        this.y = on5.h(this, this, "sg_piggy_bash_game", "chat_icon", nn5Var, null, 8);
        this.z = on5.h(this, this, "sg_piggy_bash_game", "chat_unavailable", null, null, 12);
        this.A = on5.h(this, this, "sg_piggy_bash_game", "htp_title", null, null, 12);
        this.B = on5.h(this, this, "sg_piggy_bash_game", "htp_step1_label", null, null, 12);
        this.C = on5.h(this, this, "sg_piggy_bash_game", "htp_step1_description", null, null, 12);
        this.D = on5.h(this, this, "sg_piggy_bash_game", "htp_step1_image", nn5Var, null, 8);
        this.E = on5.h(this, this, "sg_piggy_bash_game", "htp_step2_label", null, null, 12);
        this.F = on5.h(this, this, "sg_piggy_bash_game", "htp_step2_description", null, null, 12);
        this.G = on5.h(this, this, "sg_piggy_bash_game", "htp_step2_image_wap", nn5Var, null, 8);
        this.H = on5.h(this, this, "sg_piggy_bash_game", "htp_step3_label", null, null, 12);
        this.I = on5.h(this, this, "sg_piggy_bash_game", "htp_step3_description", null, null, 12);
        this.J = on5.h(this, this, "sg_piggy_bash_game", "htp_step3_image_wap", nn5Var, null, 8);
        this.K = on5.h(this, this, "sg_piggy_bash_game", "music", null, null, 12);
        this.L = on5.h(this, this, "sg_piggy_bash_game", "sound", null, null, 12);
        this.M = on5.h(this, this, "sg_piggy_bash_game", "how_to_play", null, null, 12);
        this.N = on5.h(this, this, "sg_piggy_bash_game", "bet_history", null, null, 12);
        this.O = on5.h(this, this, "sg_piggy_bash_game", "add_money_btn", null, null, 12);
        this.P = on5.h(this, this, "sg_piggy_bash_game", "side_menu_pig", nn5Var, null, 8);
        this.Q = on5.h(this, this, "sg_piggy_bash_game", "avatar_default", nn5Var, null, 8);
        this.R = on5.h(this, this, "sg_piggy_bash_game", "player", null, null, 12);
        this.S = on5.h(this, this, "sg_piggy_bash_game", "join_confirmation_message", null, null, 12);
        this.T = on5.h(this, this, "sg_piggy_bash_game", "join_confirmation_cancel", null, null, 12);
        this.U = on5.h(this, this, "sg_piggy_bash_game", "join_confirmation_confirm", null, null, 12);
        this.V = on5.h(this, this, "sg_piggy_bash_game", "login_error_message", null, null, 12);
        this.W = on5.h(this, this, "sg_piggy_bash_game", JsPluginCommon.GAMES_EXIT, null, null, 12);
        this.X = on5.h(this, this, "sg_piggy_bash_game", JsPluginCommon.GAMES_LOGIN, null, null, 12);
        this.Y = on5.h(this, this, "sg_piggy_bash_game", "pre_filling_screen_green_pig_background", nn5Var, null, 8);
        this.Z = on5.h(this, this, "sg_piggy_bash_game", "pre_filling_screen_red_pig_background", nn5Var, null, 8);
        this.a0 = on5.h(this, this, "sg_piggy_bash_game", "pre_filling_screen_blue_pig_background", nn5Var, null, 8);
        this.b0 = on5.h(this, this, "sg_piggy_bash_game", "pre_filling_screen_robo_pig_background", nn5Var, null, 8);
        this.c0 = on5.h(this, this, "sg_piggy_bash_game", "expand_reaction_tray_image", nn5Var, null, 8);
        this.d0 = on5.h(this, this, "sg_piggy_bash_game", oLsIjJCWb.IvP, null, null, 12);
        this.e0 = on5.h(this, this, "sg_piggy_bash_game", "round_starts_in", null, null, 12);
        this.f0 = on5.h(this, this, "sg_piggy_bash_game", "players_joined", null, null, 12);
        this.g0 = on5.h(this, this, "sg_piggy_bash_game", "players_joined_image", nn5Var, null, 8);
        this.h0 = on5.h(this, this, "sg_piggy_bash_game", "round_cancelled_header", null, null, 12);
        this.i0 = on5.h(this, this, "sg_piggy_bash_game", "round_cancelled_text", null, null, 12);
        this.j0 = on5.h(this, this, "sg_piggy_bash_game", "back_to_lobby", null, null, 12);
        this.k0 = on5.h(this, this, "sg_piggy_bash_game", "out_of_hits", null, null, 12);
        this.l0 = on5.h(this, this, "sg_piggy_bash_game", "one_hit_left", null, null, 12);
        this.m0 = on5.h(this, this, "sg_piggy_bash_game", "hammer_count_icon", nn5Var, null, 8);
        this.n0 = on5.h(this, this, "sg_piggy_bash_game", "hammer_count_background_icon", nn5Var, null, 8);
        this.o0 = on5.h(this, this, "sg_piggy_bash_game", "hammer_count_alert_background_icon", nn5Var, null, 8);
        this.p0 = on5.h(this, this, "sg_piggy_bash_game", "player_hammer", nn5Var, null, 8);
        this.q0 = on5.h(this, this, "sg_piggy_bash_game", "user_hammer", nn5Var, null, 8);
        this.r0 = on5.h(this, this, "sg_piggy_bash_game", "user_robo_hammer", nn5Var, null, 8);
        this.s0 = on5.h(this, this, "sg_piggy_bash_game", "piggy_crack", nn5Var, null, 8);
        this.t0 = on5.h(this, this, "sg_piggy_bash_game", "won_a_minor_prize", null, null, 12);
        this.u0 = on5.h(this, this, "sg_piggy_bash_game", "you_won_a_minor_prize", null, null, 12);
        this.v0 = on5.h(this, this, "sg_piggy_bash_game", "fly_away_at_any_moment", null, null, 12);
        this.w0 = on5.h(this, this, "sg_piggy_bash_game", "gold_rain_title", null, null, 12);
        this.x0 = on5.h(this, this, "sg_piggy_bash_game", "start_hitting", null, null, 12);
        this.y0 = on5.h(this, this, "sg_piggy_bash_game", "intentional_leave_header", null, null, 12);
        this.z0 = on5.h(this, this, "sg_piggy_bash_game", "intentional_leave_text", null, null, 12);
        this.A0 = on5.h(this, this, "sg_piggy_bash_game", "leave_game", null, null, 12);
        this.B0 = on5.h(this, this, "sg_piggy_bash_game", "you", null, null, 12);
        this.C0 = on5.h(this, this, "sg_piggy_bash_game", "coin_full", nn5Var, null, 8);
        this.D0 = on5.h(this, this, "sg_piggy_bash_game", "glow_ray", nn5Var, null, 8);
        this.E0 = on5.h(this, this, "sg_piggy_bash_game", "your_total_winnings", null, null, 12);
        this.F0 = on5.h(this, this, "sg_piggy_bash_game", "your_winnings", null, null, 12);
        this.G0 = on5.h(this, this, "sg_piggy_bash_game", "result_major_win", null, null, 12);
        this.H0 = on5.h(this, this, "sg_piggy_bash_game", "result_bonus_win", null, null, 12);
        this.I0 = on5.h(this, this, "sg_piggy_bash_game", "result_gold_rain", null, null, 12);
        this.J0 = on5.h(this, this, "sg_piggy_bash_game", "result_total", null, null, 12);
        this.K0 = on5.h(this, this, "sg_piggy_bash_game", "explore_sessions", null, null, 12);
        this.L0 = on5.h(this, this, "sg_piggy_bash_game", "join_next_round", null, null, 12);
        this.M0 = on5.h(this, this, "sg_piggy_bash_game", "congratulations_ribbon", nn5Var, null, 8);
        this.N0 = on5.h(this, this, "sg_piggy_bash_game", "crown", nn5Var, null, 8);
        this.O0 = on5.h(this, this, "sg_piggy_bash_game", "you_won_mega_win", null, null, 12);
        this.P0 = on5.h(this, this, "sg_piggy_bash_game", "got_away_image", nn5Var, null, 8);
        this.Q0 = on5.h(this, this, "sg_piggy_bash_game", "it_got_away", null, null, 12);
        this.R0 = on5.h(this, this, "sg_piggy_bash_game", "dont_let_the_next_one_escape", null, null, 12);
        this.S0 = on5.h(this, this, "sg_piggy_bash_game", "smashed_the_pig", null, null, 12);
        this.T0 = on5.h(this, this, "sg_piggy_bash_game", "and_won_mega_win", null, null, 12);
        this.U0 = on5.h(this, this, "sg_piggy_bash_game", "you_could_be_next", null, null, 12);
        this.V0 = on5.h(this, this, "sg_piggy_bash_game", "quick_tip", null, null, 12);
        this.W0 = on5.h(this, this, "sg_piggy_bash_game", "quick_tips", null, null, 12);
        this.X0 = on5.h(this, this, "sg_piggy_bash_game", "bet_history_time", null, null, 12);
        this.Y0 = on5.h(this, this, "sg_piggy_bash_game", "bet_history_stake", null, null, 12);
        this.Z0 = on5.h(this, this, "sg_piggy_bash_game", "bet_history_status", null, null, 12);
        this.a1 = on5.h(this, this, "sg_piggy_bash_game", "bet_history_details", null, null, 12);
        this.b1 = on5.h(this, this, "sg_piggy_bash_game", "bet_history_mega_win", null, null, 12);
        this.c1 = on5.h(this, this, "sg_piggy_bash_game", "bet_history_bonus_win", null, null, 12);
        this.d1 = on5.h(this, this, "sg_piggy_bash_game", "bet_history_gold_rain", null, null, 12);
        this.e1 = on5.h(this, this, "sg_piggy_bash_game", "bet_history_lost", null, null, 12);
        this.f1 = on5.h(this, this, "sg_piggy_bash_game", "bet_history_pending", null, null, 12);
        this.g1 = on5.h(this, this, "sg_piggy_bash_game", "bet_history_round_id", null, null, 12);
        this.h1 = on5.h(this, this, "sg_piggy_bash_game", "bet_history_ticket_id", null, null, 12);
        this.i1 = on5.h(this, this, "sg_piggy_bash_game", "bet_history_empty", null, null, 12);
        this.j1 = on5.h(this, this, "sg_piggy_bash_game", "bet_history_failed", null, null, 12);
        this.k1 = on5.h(this, this, "sg_piggy_bash_game", "bet_history_reload", null, null, 12);
        this.l1 = on5.h(this, this, "sg_piggy_bash_game", "bet_history_more", null, null, 12);
        this.m1 = on5.h(this, this, "sg_piggy_bash_game", "bet_history_cancelled", null, null, 12);
        this.n1 = on5.h(this, this, "sg_piggy_bash_game", "image_star", null, null, 12);
        nn5 nn5Var2 = nn5.LongMusic;
        this.o1 = on5.h(this, this, "sg_piggy_bash_game", "bgm_lobby", nn5Var2, null, 8);
        this.p1 = on5.h(this, this, "sg_piggy_bash_game", "bgm_jungle_theme", nn5Var2, null, 8);
        this.q1 = on5.h(this, this, "sg_piggy_bash_game", "bgm_jungle_theme_intense", nn5Var2, null, 8);
        this.r1 = on5.h(this, this, "sg_piggy_bash_game", "bgm_robotic_theme", nn5Var2, null, 8);
        this.s1 = on5.h(this, this, "sg_piggy_bash_game", "bgm_robotic_theme_intense", nn5Var2, null, 8);
        this.t1 = on5.h(this, this, "sg_piggy_bash_game", "bgm_temple_theme", nn5Var2, null, 8);
        this.u1 = on5.h(this, this, "sg_piggy_bash_game", "bgm_temple_theme_intense", nn5Var2, null, 8);
        this.v1 = on5.h(this, this, "sg_piggy_bash_game", "bgm_wild_west_theme", nn5Var2, null, 8);
        this.w1 = on5.h(this, this, "sg_piggy_bash_game", "bgm_wild_west_theme_intense", nn5Var2, null, 8);
        nn5 nn5Var3 = nn5.ShortSound;
        this.x1 = on5.h(this, this, "sg_piggy_bash_game", "sfx_major_crack_1", nn5Var3, null, 8);
        this.y1 = on5.h(this, this, "sg_piggy_bash_game", "sfx_major_crack_2", nn5Var3, null, 8);
        this.z1 = on5.h(this, this, "sg_piggy_bash_game", "sfx_major_crack_3", nn5Var3, null, 8);
        this.A1 = on5.h(this, this, "sg_piggy_bash_game", "sfx_major_crack_4", nn5Var3, null, 8);
        this.B1 = on5.h(this, this, "sg_piggy_bash_game", "sfx_major_crack_5", nn5Var3, null, 8);
        this.C1 = on5.h(this, this, "sg_piggy_bash_game", "sfx_minor_crack_1", nn5Var3, null, 8);
        this.D1 = on5.h(this, this, "sg_piggy_bash_game", "sfx_minor_crack_2", nn5Var3, null, 8);
        this.E1 = on5.h(this, this, "sg_piggy_bash_game", "sfx_minor_crack_3", nn5Var3, null, 8);
        this.F1 = on5.h(this, this, "sg_piggy_bash_game", "sfx_minor_crack_4", nn5Var3, null, 8);
        this.G1 = on5.h(this, this, "sg_piggy_bash_game", "sfx_major_hits_1", nn5Var3, null, 8);
        this.H1 = on5.h(this, this, "sg_piggy_bash_game", "sfx_major_hits_2", nn5Var3, null, 8);
        this.I1 = on5.h(this, this, "sg_piggy_bash_game", "sfx_major_hits_3", nn5Var3, null, 8);
        this.J1 = on5.h(this, this, "sg_piggy_bash_game", "sfx_minor_hits_1", nn5Var3, null, 8);
        this.K1 = on5.h(this, this, "sg_piggy_bash_game", "sfx_minor_hits_2", nn5Var3, null, 8);
        this.L1 = on5.h(this, this, "sg_piggy_bash_game", "sfx_minor_hits_3", nn5Var3, null, 8);
        this.M1 = on5.h(this, this, "sg_piggy_bash_game", "sfx_pigs_laugh", nn5Var3, null, 8);
        this.N1 = on5.h(this, this, "sg_piggy_bash_game", "sfx_pigs_oink_with_smoke", nn5Var3, null, 8);
        this.O1 = on5.h(this, this, "sg_piggy_bash_game", "sfx_pigs_grunt_with_whistle", nn5Var3, null, 8);
        this.P1 = on5.h(this, this, "sg_piggy_bash_game", "sfx_pigs_oink", nn5Var3, null, 8);
        this.Q1 = on5.h(this, this, "sg_piggy_bash_game", "sfx_card_selection_confirmed", nn5Var3, null, 8);
        this.R1 = on5.h(this, this, "sg_piggy_bash_game", "sfx_card_selection_sound", nn5Var3, null, 8);
        this.S1 = on5.h(this, this, "sg_piggy_bash_game", "sfx_main_player_big_win", nn5Var3, null, 8);
        this.T1 = on5.h(this, this, "sg_piggy_bash_game", "sfx_respawn", nn5Var3, null, 8);
        this.U1 = on5.h(this, this, "sg_piggy_bash_game", "sfx_winning_counter_raising", nn5Var3, null, 8);
        this.V1 = on5.h(this, this, "sg_piggy_bash_game", "sfx_fly_away", nn5Var3, null, 8);
        this.W1 = on5.h(this, this, "sg_piggy_bash_game", "sfx_gold_filling", nn5Var3, null, 8);
        this.X1 = on5.h(this, this, "sg_piggy_bash_game", "sfx_bonus_win", nn5Var3, null, 8);
        this.Y1 = on5.h(this, this, "sg_piggy_bash_game", "sfx_gold_rain", nn5Var3, null, 8);
        this.Z1 = on5.h(this, this, "sg_piggy_bash_game", "sfx_hammer_spawn", nn5Var3, null, 8);
        this.a2 = on5.h(this, this, "sg_common_dialog_message", "unavailable_country", null, null, 12);
    }
}
