package defpackage;

/* JADX INFO: loaded from: classes.dex */
public final class s58 {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final long D;
    public static final long E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final long I;
    public static final long J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final long N;
    public static final long O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final long S;
    public static final long T;
    public static final long U;
    public static final long a;
    public static final long b;
    public static final long c;
    public static final long d;
    public static final long e;
    public static final long f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final long j;
    public static final long k;
    public static final long l;
    public static final long m;
    public static final long n;
    public static final long o;
    public static final long p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final long t;
    public static final long u;
    public static final long v;
    public static final long w;
    public static final long x;
    public static final long y;
    public static final long z;

    static {
        long j2 = irz.x;
        a = j2;
        b = irz.e;
        c = irz.g;
        d = irz.v;
        long j3 = irz.I;
        e = j3;
        f = irz.m;
        long j4 = irz.i;
        g = j4;
        h = irz.b;
        i = irz.a;
        j = irz.E;
        long j5 = irz.D;
        k = j5;
        l = j5;
        m = irz.G;
        n = irz.L;
        long j6 = irz.K;
        o = j6;
        p = j6;
        q = irz.N;
        r = j4;
        s = irz.y;
        t = irz.S;
        long j7 = irz.R;
        u = j7;
        v = j7;
        w = irz.U;
        x = irz.z;
        y = irz.B;
        z = irz.H;
        long j8 = irz.J;
        A = j8;
        B = j8;
        C = j3;
        D = irz.h;
        E = irz.O;
        long j9 = irz.Q;
        F = j9;
        G = j9;
        H = irz.P;
        I = j2;
        J = j2;
        K = irz.u;
        L = irz.t;
        M = irz.s;
        N = irz.w;
        O = irz.j;
        P = irz.r;
        Q = irz.C;
        R = irz.V;
        long j10 = irz.X;
        S = j10;
        T = j10;
        U = irz.W;
    }
}
