package defpackage;

import android.R;

/* JADX INFO: loaded from: classes4.dex */
public final class sk30 {
    public static final int[] a = {R.attr.colorBackground, R.attr.textColorPrimary, R.attr.fontFamily, com.sportybet.android.gp.tz.R.attr.colorAccent, com.sportybet.android.gp.tz.R.attr.colorError, com.sportybet.android.gp.tz.R.attr.colorPrimary, com.sportybet.android.gp.tz.R.attr.colorPrimaryDark, com.sportybet.android.gp.tz.R.attr.fontFamily, com.sportybet.android.gp.tz.R.attr.isLightTheme, com.sportybet.android.gp.tz.R.attr.windowActionBar};
    public static final int[] b = {com.sportybet.android.gp.tz.R.attr.boxIcon, com.sportybet.android.gp.tz.R.attr.boxText, com.sportybet.android.gp.tz.R.attr.showDropdown};
    public static final int[] c = {R.attr.text};
    public static final int[] d = {com.sportybet.android.gp.tz.R.attr.rsb_gravity, com.sportybet.android.gp.tz.R.attr.rsb_indicator_arrow_size, com.sportybet.android.gp.tz.R.attr.rsb_indicator_background_color, com.sportybet.android.gp.tz.R.attr.rsb_indicator_drawable, com.sportybet.android.gp.tz.R.attr.rsb_indicator_height, com.sportybet.android.gp.tz.R.attr.rsb_indicator_margin, com.sportybet.android.gp.tz.R.attr.rsb_indicator_padding_bottom, com.sportybet.android.gp.tz.R.attr.rsb_indicator_padding_left, com.sportybet.android.gp.tz.R.attr.rsb_indicator_padding_right, com.sportybet.android.gp.tz.R.attr.rsb_indicator_padding_top, com.sportybet.android.gp.tz.R.attr.rsb_indicator_radius, com.sportybet.android.gp.tz.R.attr.rsb_indicator_show_mode, com.sportybet.android.gp.tz.R.attr.rsb_indicator_text_color, com.sportybet.android.gp.tz.R.attr.rsb_indicator_text_size, com.sportybet.android.gp.tz.R.attr.rsb_indicator_width, com.sportybet.android.gp.tz.R.attr.rsb_max, com.sportybet.android.gp.tz.R.attr.rsb_min, com.sportybet.android.gp.tz.R.attr.rsb_min_interval, com.sportybet.android.gp.tz.R.attr.rsb_mode, com.sportybet.android.gp.tz.R.attr.rsb_progress_color, com.sportybet.android.gp.tz.R.attr.rsb_progress_default_color, com.sportybet.android.gp.tz.R.attr.rsb_progress_drawable, com.sportybet.android.gp.tz.R.attr.rsb_progress_drawable_default, com.sportybet.android.gp.tz.R.attr.rsb_progress_height, com.sportybet.android.gp.tz.R.attr.rsb_progress_radius, com.sportybet.android.gp.tz.R.attr.rsb_step_auto_bonding, com.sportybet.android.gp.tz.R.attr.rsb_step_color, com.sportybet.android.gp.tz.R.attr.rsb_step_drawable, com.sportybet.android.gp.tz.R.attr.rsb_step_height, com.sportybet.android.gp.tz.R.attr.rsb_step_radius, com.sportybet.android.gp.tz.R.attr.rsb_step_width, com.sportybet.android.gp.tz.R.attr.rsb_steps, com.sportybet.android.gp.tz.R.attr.rsb_thumb_drawable, com.sportybet.android.gp.tz.R.attr.rsb_thumb_height, com.sportybet.android.gp.tz.R.attr.rsb_thumb_inactivated_drawable, com.sportybet.android.gp.tz.R.attr.rsb_thumb_scale_ratio, com.sportybet.android.gp.tz.R.attr.rsb_thumb_width, com.sportybet.android.gp.tz.R.attr.rsb_tick_mark_gravity, com.sportybet.android.gp.tz.R.attr.rsb_tick_mark_in_range_text_color, com.sportybet.android.gp.tz.R.attr.rsb_tick_mark_layout_gravity, com.sportybet.android.gp.tz.R.attr.rsb_tick_mark_mode, com.sportybet.android.gp.tz.R.attr.rsb_tick_mark_number, com.sportybet.android.gp.tz.R.attr.rsb_tick_mark_text_array, com.sportybet.android.gp.tz.R.attr.rsb_tick_mark_text_color, com.sportybet.android.gp.tz.R.attr.rsb_tick_mark_text_margin, com.sportybet.android.gp.tz.R.attr.rsb_tick_mark_text_size};
    public static final int[] e = {com.sportybet.android.gp.tz.R.attr.endLineColor, com.sportybet.android.gp.tz.R.attr.lineOrientation, com.sportybet.android.gp.tz.R.attr.linePadding, com.sportybet.android.gp.tz.R.attr.lineStyle, com.sportybet.android.gp.tz.R.attr.lineStyleDashGap, com.sportybet.android.gp.tz.R.attr.lineStyleDashLength, com.sportybet.android.gp.tz.R.attr.lineWidth, com.sportybet.android.gp.tz.R.attr.marker, com.sportybet.android.gp.tz.R.attr.markerInCenter, com.sportybet.android.gp.tz.R.attr.markerPaddingBottom, com.sportybet.android.gp.tz.R.attr.markerPaddingLeft, com.sportybet.android.gp.tz.R.attr.markerPaddingRight, com.sportybet.android.gp.tz.R.attr.markerPaddingTop, com.sportybet.android.gp.tz.R.attr.markerSize, com.sportybet.android.gp.tz.R.attr.startLineColor};
}
