package defpackage;

import com.sportybet.android.instantwin.presentation.buildandgo.sTE.siPCzPFw;

/* JADX INFO: loaded from: classes2.dex */
public final class th60 {
    public final long A;
    public final long A0;
    public final long B;
    public final long B0;
    public final long C;
    public final long D;
    public final long E;
    public final long F;
    public final long G;
    public final long H;
    public final long I;
    public final long J;
    public final long K;
    public final long L;
    public final long M;
    public final long N;
    public final long O;
    public final long P;
    public final long Q;
    public final long R;
    public final long S;
    public final long T;
    public final long U;
    public final long V;
    public final long W;
    public final long X;
    public final long Y;
    public final long Z;
    public final long a;
    public final long a0;
    public final long b;
    public final long b0;
    public final long c;
    public final long c0;
    public final long d;
    public final long d0;
    public final long e;
    public final long e0;
    public final long f;
    public final long f0;
    public final long g;
    public final long g0;
    public final long h;
    public final long h0;
    public final long i;
    public final long i0;
    public final long j;
    public final long j0;
    public final long k;
    public final long k0;
    public final long l;
    public final long l0;
    public final long m;
    public final long m0;
    public final long n;
    public final long n0;
    public final long o;
    public final long o0;
    public final long p;
    public final long p0;
    public final long q;
    public final long q0;
    public final long r;
    public final long r0;
    public final long s;
    public final long s0;
    public final long t;
    public final long t0;
    public final long u;
    public final long u0;
    public final long v;
    public final long v0;
    public final long w;
    public final long w0;
    public final long x;
    public final long x0;
    public final long y;
    public final long y0;
    public final long z;
    public final long z0;

    public th60(long j, long j2, long j3, long j4, long j5, long j6, long j7, long j8, long j9, long j10, long j11, long j12, long j13, long j14, long j15, long j16, long j17, long j18, long j19, long j20, long j21, long j22, long j23, long j24, long j25, long j26, long j27, long j28, long j29, long j30, long j31, long j32, long j33, long j34, long j35, long j36, long j37, long j38, long j39, long j40, long j41, long j42, long j43, long j44, long j45, long j46, long j47, long j48, long j49, long j50, long j51, long j52, long j53, long j54, long j55, long j56, long j57, long j58, long j59, long j60, long j61, long j62, long j63, long j64, long j65, long j66, long j67, long j68, long j69, long j70, long j71, long j72, long j73, long j74, long j75, long j76, long j77, long j78, long j79, long j80) {
        this.a = j;
        this.b = j2;
        this.c = j3;
        this.d = j4;
        this.e = j5;
        this.f = j6;
        this.g = j7;
        this.h = j8;
        this.i = j9;
        this.j = j10;
        this.k = j11;
        this.l = j12;
        this.m = j13;
        this.n = j14;
        this.o = j15;
        this.p = j16;
        this.q = j17;
        this.r = j18;
        this.s = j19;
        this.t = j20;
        this.u = j21;
        this.v = j22;
        this.w = j23;
        this.x = j24;
        this.y = j25;
        this.z = j26;
        this.A = j27;
        this.B = j28;
        this.C = j29;
        this.D = j30;
        this.E = j31;
        this.F = j32;
        this.G = j33;
        this.H = j34;
        this.I = j35;
        this.J = j36;
        this.K = j37;
        this.L = j38;
        this.M = j39;
        this.N = j40;
        this.O = j41;
        this.P = j42;
        this.Q = j43;
        this.R = j44;
        this.S = j45;
        this.T = j46;
        this.U = j47;
        this.V = j48;
        this.W = j49;
        this.X = j50;
        this.Y = j51;
        this.Z = j52;
        this.a0 = j53;
        this.b0 = j54;
        this.c0 = j55;
        this.d0 = j56;
        this.e0 = j57;
        this.f0 = j58;
        this.g0 = j59;
        this.h0 = j60;
        this.i0 = j61;
        this.j0 = j62;
        this.k0 = j63;
        this.l0 = j64;
        this.m0 = j65;
        this.n0 = j66;
        this.o0 = j67;
        this.p0 = j68;
        this.q0 = j69;
        this.r0 = j70;
        this.s0 = j71;
        this.t0 = j72;
        this.u0 = j73;
        this.v0 = j74;
        this.w0 = j75;
        this.x0 = j76;
        this.y0 = j77;
        this.z0 = j78;
        this.A0 = j79;
        this.B0 = j80;
    }

    public final boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof th60)) {
            return false;
        }
        th60 th60Var = (th60) obj;
        long j = th60Var.a;
        int i = j58.n;
        return nbh0.a(this.a, j) && nbh0.a(this.b, th60Var.b) && nbh0.a(this.c, th60Var.c) && nbh0.a(this.d, th60Var.d) && nbh0.a(this.e, th60Var.e) && nbh0.a(this.f, th60Var.f) && nbh0.a(this.g, th60Var.g) && nbh0.a(this.h, th60Var.h) && nbh0.a(this.i, th60Var.i) && nbh0.a(this.j, th60Var.j) && nbh0.a(this.k, th60Var.k) && nbh0.a(this.l, th60Var.l) && nbh0.a(this.m, th60Var.m) && nbh0.a(this.n, th60Var.n) && nbh0.a(this.o, th60Var.o) && nbh0.a(this.p, th60Var.p) && nbh0.a(this.q, th60Var.q) && nbh0.a(this.r, th60Var.r) && nbh0.a(this.s, th60Var.s) && nbh0.a(this.t, th60Var.t) && nbh0.a(this.u, th60Var.u) && nbh0.a(this.v, th60Var.v) && nbh0.a(this.w, th60Var.w) && nbh0.a(this.x, th60Var.x) && nbh0.a(this.y, th60Var.y) && nbh0.a(this.z, th60Var.z) && nbh0.a(this.A, th60Var.A) && nbh0.a(this.B, th60Var.B) && nbh0.a(this.C, th60Var.C) && nbh0.a(this.D, th60Var.D) && nbh0.a(this.E, th60Var.E) && nbh0.a(this.F, th60Var.F) && nbh0.a(this.G, th60Var.G) && nbh0.a(this.H, th60Var.H) && nbh0.a(this.I, th60Var.I) && nbh0.a(this.J, th60Var.J) && nbh0.a(this.K, th60Var.K) && nbh0.a(this.L, th60Var.L) && nbh0.a(this.M, th60Var.M) && nbh0.a(this.N, th60Var.N) && nbh0.a(this.O, th60Var.O) && nbh0.a(this.P, th60Var.P) && nbh0.a(this.Q, th60Var.Q) && nbh0.a(this.R, th60Var.R) && nbh0.a(this.S, th60Var.S) && nbh0.a(this.T, th60Var.T) && nbh0.a(this.U, th60Var.U) && nbh0.a(this.V, th60Var.V) && nbh0.a(this.W, th60Var.W) && nbh0.a(this.X, th60Var.X) && nbh0.a(this.Y, th60Var.Y) && nbh0.a(this.Z, th60Var.Z) && nbh0.a(this.a0, th60Var.a0) && nbh0.a(this.b0, th60Var.b0) && nbh0.a(this.c0, th60Var.c0) && nbh0.a(this.d0, th60Var.d0) && nbh0.a(this.e0, th60Var.e0) && nbh0.a(this.f0, th60Var.f0) && nbh0.a(this.g0, th60Var.g0) && nbh0.a(this.h0, th60Var.h0) && nbh0.a(this.i0, th60Var.i0) && nbh0.a(this.j0, th60Var.j0) && nbh0.a(this.k0, th60Var.k0) && nbh0.a(this.l0, th60Var.l0) && nbh0.a(this.m0, th60Var.m0) && nbh0.a(this.n0, th60Var.n0) && nbh0.a(this.o0, th60Var.o0) && nbh0.a(this.p0, th60Var.p0) && nbh0.a(this.q0, th60Var.q0) && nbh0.a(this.r0, th60Var.r0) && nbh0.a(this.s0, th60Var.s0) && nbh0.a(this.t0, th60Var.t0) && nbh0.a(this.u0, th60Var.u0) && nbh0.a(this.v0, th60Var.v0) && nbh0.a(this.w0, th60Var.w0) && nbh0.a(this.x0, th60Var.x0) && nbh0.a(this.y0, th60Var.y0) && nbh0.a(this.z0, th60Var.z0) && nbh0.a(this.A0, th60Var.A0) && nbh0.a(this.B0, th60Var.B0);
    }

    public final int hashCode() {
        int i = j58.n;
        nbh0.a aVar = nbh0.b;
        return Long.hashCode(this.B0) + f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(f87.a(Long.hashCode(this.a) * 31, this.b, 31), this.c, 31), this.d, 31), this.e, 31), this.f, 31), this.g, 31), this.h, 31), this.i, 31), this.j, 31), this.k, 31), this.l, 31), this.m, 31), this.n, 31), this.o, 31), this.p, 31), this.q, 31), this.r, 31), this.s, 31), this.t, 31), this.u, 31), this.v, 31), this.w, 31), this.x, 31), this.y, 31), this.z, 31), this.A, 31), this.B, 31), this.C, 31), this.D, 31), this.E, 31), this.F, 31), this.G, 31), this.H, 31), this.I, 31), this.J, 31), this.K, 31), this.L, 31), this.M, 31), this.N, 31), this.O, 31), this.P, 31), this.Q, 31), this.R, 31), this.S, 31), this.T, 31), this.U, 31), this.V, 31), this.W, 31), this.X, 31), this.Y, 31), this.Z, 31), this.a0, 31), this.b0, 31), this.c0, 31), this.d0, 31), this.e0, 31), this.f0, 31), this.g0, 31), this.h0, 31), this.i0, 31), this.j0, 31), this.k0, 31), this.l0, 31), this.m0, 31), this.n0, 31), this.o0, 31), this.p0, 31), this.q0, 31), this.r0, 31), this.s0, 31), this.t0, 31), this.u0, 31), this.v0, 31), this.w0, 31), this.x0, 31), this.y0, 31), this.z0, 31), this.A0, 31);
    }

    public final String toString() {
        String strI = j58.i(this.a);
        String strI2 = j58.i(this.b);
        String strI3 = j58.i(this.c);
        String strI4 = j58.i(this.d);
        String strI5 = j58.i(this.e);
        String strI6 = j58.i(this.f);
        String strI7 = j58.i(this.g);
        String strI8 = j58.i(this.h);
        String strI9 = j58.i(this.i);
        String strI10 = j58.i(this.j);
        String strI11 = j58.i(this.k);
        String strI12 = j58.i(this.l);
        String strI13 = j58.i(this.m);
        String strI14 = j58.i(this.n);
        String strI15 = j58.i(this.o);
        String strI16 = j58.i(this.p);
        String strI17 = j58.i(this.q);
        String strI18 = j58.i(this.r);
        String strI19 = j58.i(this.s);
        String strI20 = j58.i(this.t);
        String strI21 = j58.i(this.u);
        String strI22 = j58.i(this.v);
        String strI23 = j58.i(this.w);
        String strI24 = j58.i(this.x);
        String strI25 = j58.i(this.y);
        String strI26 = j58.i(this.z);
        String strI27 = j58.i(this.A);
        String strI28 = j58.i(this.B);
        String strI29 = j58.i(this.C);
        String strI30 = j58.i(this.D);
        String strI31 = j58.i(this.E);
        String strI32 = j58.i(this.F);
        String strI33 = j58.i(this.G);
        String strI34 = j58.i(this.H);
        String strI35 = j58.i(this.I);
        String strI36 = j58.i(this.J);
        String strI37 = j58.i(this.K);
        String strI38 = j58.i(this.L);
        String strI39 = j58.i(this.M);
        String strI40 = j58.i(this.N);
        String strI41 = j58.i(this.O);
        String strI42 = j58.i(this.P);
        String strI43 = j58.i(this.Q);
        String strI44 = j58.i(this.R);
        String strI45 = j58.i(this.S);
        String strI46 = j58.i(this.T);
        String strI47 = j58.i(this.U);
        String strI48 = j58.i(this.V);
        String strI49 = j58.i(this.W);
        String strI50 = j58.i(this.X);
        String strI51 = j58.i(this.Y);
        String strI52 = j58.i(this.Z);
        String strI53 = j58.i(this.a0);
        String strI54 = j58.i(this.b0);
        String strI55 = j58.i(this.c0);
        String strI56 = j58.i(this.d0);
        String strI57 = j58.i(this.e0);
        String strI58 = j58.i(this.f0);
        String strI59 = j58.i(this.g0);
        String strI60 = j58.i(this.h0);
        String strI61 = j58.i(this.i0);
        String strI62 = j58.i(this.j0);
        String strI63 = j58.i(this.k0);
        String strI64 = j58.i(this.l0);
        String strI65 = j58.i(this.m0);
        String strI66 = j58.i(this.n0);
        String strI67 = j58.i(this.o0);
        String strI68 = j58.i(this.p0);
        String strI69 = j58.i(this.q0);
        String strI70 = j58.i(this.r0);
        String strI71 = j58.i(this.s0);
        String strI72 = j58.i(this.t0);
        String strI73 = j58.i(this.u0);
        String strI74 = j58.i(this.v0);
        String strI75 = j58.i(this.w0);
        String strI76 = j58.i(this.x0);
        String strI77 = j58.i(this.y0);
        String strI78 = j58.i(this.z0);
        String strI79 = j58.i(this.A0);
        String strI80 = j58.i(this.B0);
        StringBuilder sbA = ux5.a("SGColorPalette(categoryTitleBg=", strI, ", categoryItemBg=", strI2, ", categoryItemSelectedBg=");
        hxa.c(sbA, strI3, ", categoryTextColor=", strI4, ", categoryTextColorSelected=");
        hxa.c(sbA, strI5, ", categoryTextTitleColor=", strI6, ", categoryDivider=");
        hxa.c(sbA, strI7, ", gameItemTitleTextColor=", strI8, ", gameItemShowAllTextColor=");
        hxa.c(sbA, strI9, ", gameItemShowAllBg=", strI10, ", gameCardTitleTextColor=");
        hxa.c(sbA, strI11, ", gameCardPlayButtonBgTop=", strI12, ", gameCardPlayButtonBgBottom=");
        hxa.c(sbA, strI13, ", gameCardPlayButtonText=", strI14, ", gameCardCategoryText=");
        hxa.c(sbA, strI15, siPCzPFw.ELWpH, strI16, ", placeholderShimmerLeftTop=");
        hxa.c(sbA, strI17, ", placeholderShimmerLeftBottom=", strI18, ", placeholderShimmerRightTop=");
        hxa.c(sbA, strI19, ", placeholderShimmerRightBottom=", strI20, ", placeholderBg=");
        hxa.c(sbA, strI21, ", lobbyBg=", strI22, ", searchBarIconTint=");
        hxa.c(sbA, strI23, ", searchBarBorder=", strI24, ", searchBarText=");
        hxa.c(sbA, strI25, ", searchBarBg=", strI26, ", searchBarDivider=");
        hxa.c(sbA, strI27, ", searchBarCrossTint=", strI28, ", searchBarTypingText=");
        hxa.c(sbA, strI29, ", retryButtonBgTop=", strI30, ", retryButtonBgBottom=");
        hxa.c(sbA, strI31, ", retryButtonText=", strI32, ", searchDivider=");
        hxa.c(sbA, strI33, ", searchBg=", strI34, ", gameItemBannerBg=");
        hxa.c(sbA, strI35, ", gameItemBannerCircleSelected=", strI36, ", gameItemBannerCircleUnSelected=");
        hxa.c(sbA, strI37, ", gameCardBg=", strI38, ", gameItemBannerText=");
        hxa.c(sbA, strI39, ", gameItemCardIndexColor=", strI40, ", gameItemDoubleRowChevronBg=");
        hxa.c(sbA, strI41, ", gameItemDoubleRowChevronBorder=", strI42, ", searchTitle=");
        hxa.c(sbA, strI43, ", searchInfoBg=", strI44, ", searchInfoText=");
        hxa.c(sbA, strI45, ", categoryIconTint=", strI46, ", commonCategoryIconTint=");
        hxa.c(sbA, strI47, ", searchExtraItemBackground=", strI48, ", searchExtraItemText=");
        hxa.c(sbA, strI49, ", searchExtraTitle=", strI50, ", infoDescriptionText=");
        hxa.c(sbA, strI51, ", lobbyV2GameProviderCountTextColor=", strI52, ", lobbyV2GameProviderBackgroundColor=");
        hxa.c(sbA, strI53, ", termsAndConditionsButtonBg=", strI54, ", spotlightTextGradientStart=");
        hxa.c(sbA, strI55, ", spotlightTextGradientEnd=", strI56, ", spotlightBannerBorderStart=");
        hxa.c(sbA, strI57, ", spotlightBannerBorderEnd=", strI58, ", spotlightBannerTitleStart=");
        hxa.c(sbA, strI59, ", spotlightBannerTitleEnd=", strI60, ", spotlightBannerTitleSolid=");
        hxa.c(sbA, strI61, ", spotlightCategoryCardBg=", strI62, ", promoDoNotShowAgainBg=");
        hxa.c(sbA, strI63, ", promoCheckboxTint=", strI64, ", promoDoNotShowAgainText=");
        hxa.c(sbA, strI65, ", topWinsCardBackground=", strI66, ", topWinsComponentBorder1=");
        hxa.c(sbA, strI67, ", topWinsComponentBorder2=", strI68, ", topWinsComponentBorder3=");
        hxa.c(sbA, strI69, ", topWinsComponentBorder4=", strI70, ", topWinsImageBorder=");
        hxa.c(sbA, strI71, ", topWinsCardBorderTop=", strI72, ", topWinsCardBorderMid=");
        hxa.c(sbA, strI73, ", topWinsCardBorderLow=", strI74, ", topWinsAmountText=");
        hxa.c(sbA, strI75, ", topWinsUserText=", strI76, ", topWinsPlayNowBorder=");
        hxa.c(sbA, strI77, ", topWinsPlayNowText=", strI78, ", topWinsPlayNowBackgroundTop=");
        return kwi.a(sbA, strI79, ", topWinsPlayNowBackgroundBottom=", strI80, ")");
    }
}
