package defpackage;

import android.view.View;
import android.widget.ImageButton;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.compose.ui.platform.ComposeView;
import androidx.constraintlayout.widget.ConstraintLayout;

/* JADX INFO: loaded from: classes5.dex */
public final class txi implements g6i0 {
    public final TextView A;
    public final ComposeView B;
    public final TextView C;
    public final TextView D;
    public final View E;
    public final TextView F;
    public final View G;
    public final TextView H;
    public final View I;
    public final TextView J;
    public final View K;
    public final ConstraintLayout L;
    public final ImageButton M;
    public final LinearLayout N;
    public final LinearLayout O;
    public final TextView P;
    public final TextView Q;
    public final View R;
    public final ComposeView S;
    public final View T;
    public final ConstraintLayout U;
    public final ImageView V;
    public final TextView W;
    public final View X;
    public final TextView Y;
    public final View Z;
    public final ConstraintLayout a;
    public final TextView a0;
    public final TextView b;
    public final View b0;
    public final ComposeView c;
    public final TextView c0;
    public final ComposeView d;
    public final TextView d0;
    public final ConstraintLayout e;
    public final TextView e0;
    public final ImageButton f;
    public final TextView f0;
    public final ComposeView g0;
    public final ConstraintLayout h0;
    public final TextView i;
    public final ImageView i0;
    public final TextView j0;
    public final View k0;
    public final ConstraintLayout l0;
    public final TextView m0;
    public final TextView n0;
    public final View o0;
    public final TextView p0;
    public final View q0;
    public final TextView r0;
    public final ScrollView s0;
    public final ConstraintLayout t0;
    public final ComposeView u0;
    public final View v;
    public final ConstraintLayout v0;
    public final View w;
    public final ImageView w0;
    public final TextView y;
    public final View z;

    public txi(ConstraintLayout constraintLayout, TextView textView, ComposeView composeView, ComposeView composeView2, ConstraintLayout constraintLayout2, ImageButton imageButton, TextView textView2, View view, View view2, TextView textView3, View view3, TextView textView4, ComposeView composeView3, TextView textView5, TextView textView6, View view4, TextView textView7, View view5, TextView textView8, View view6, TextView textView9, View view7, ConstraintLayout constraintLayout3, ImageButton imageButton2, LinearLayout linearLayout, LinearLayout linearLayout2, TextView textView10, TextView textView11, View view8, ComposeView composeView4, View view9, ConstraintLayout constraintLayout4, ImageView imageView, TextView textView12, View view10, TextView textView13, View view11, TextView textView14, View view12, TextView textView15, TextView textView16, TextView textView17, TextView textView18, ComposeView composeView5, ConstraintLayout constraintLayout5, ImageView imageView2, TextView textView19, View view13, ConstraintLayout constraintLayout6, TextView textView20, TextView textView21, View view14, TextView textView22, View view15, TextView textView23, ScrollView scrollView, ConstraintLayout constraintLayout7, ComposeView composeView6, ConstraintLayout constraintLayout8, ImageView imageView3) {
        this.a = constraintLayout;
        this.b = textView;
        this.c = composeView;
        this.d = composeView2;
        this.e = constraintLayout2;
        this.f = imageButton;
        this.i = textView2;
        this.v = view;
        this.w = view2;
        this.y = textView3;
        this.z = view3;
        this.A = textView4;
        this.B = composeView3;
        this.C = textView5;
        this.D = textView6;
        this.E = view4;
        this.F = textView7;
        this.G = view5;
        this.H = textView8;
        this.I = view6;
        this.J = textView9;
        this.K = view7;
        this.L = constraintLayout3;
        this.M = imageButton2;
        this.N = linearLayout;
        this.O = linearLayout2;
        this.P = textView10;
        this.Q = textView11;
        this.R = view8;
        this.S = composeView4;
        this.T = view9;
        this.U = constraintLayout4;
        this.V = imageView;
        this.W = textView12;
        this.X = view10;
        this.Y = textView13;
        this.Z = view11;
        this.a0 = textView14;
        this.b0 = view12;
        this.c0 = textView15;
        this.d0 = textView16;
        this.e0 = textView17;
        this.f0 = textView18;
        this.g0 = composeView5;
        this.h0 = constraintLayout5;
        this.i0 = imageView2;
        this.j0 = textView19;
        this.k0 = view13;
        this.l0 = constraintLayout6;
        this.m0 = textView20;
        this.n0 = textView21;
        this.o0 = view14;
        this.p0 = textView22;
        this.q0 = view15;
        this.r0 = textView23;
        this.s0 = scrollView;
        this.t0 = constraintLayout7;
        this.u0 = composeView6;
        this.v0 = constraintLayout8;
        this.w0 = imageView3;
    }

    @Override // defpackage.g6i0
    public final View getRoot() {
        return this.a;
    }
}
