package defpackage;

import androidx.recyclerview.widget.r;
import com.sportybet.feature.dedicatedteampage.team.data.model.Vc.ACKxwYRsuWyGz;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import okhttp3.internal.ws.RealWebSocket;

/* JADX INFO: loaded from: classes4.dex */
public final class v2l0 {
    public static final t2l0 A;
    public static final t2l0 A0;
    public static final t2l0 B;
    public static final t2l0 B0;
    public static final t2l0 C;
    public static final t2l0 C0;
    public static final t2l0 D;
    public static final t2l0 D0;
    public static final t2l0 E;
    public static final t2l0 E0;
    public static final t2l0 F;
    public static final t2l0 F0;
    public static final t2l0 G;
    public static final t2l0 G0;
    public static final t2l0 H;
    public static final t2l0 H0;
    public static final t2l0 I;
    public static final t2l0 I0;
    public static final t2l0 J;
    public static final t2l0 J0;
    public static final t2l0 K;
    public static final t2l0 K0;
    public static final t2l0 L;
    public static final t2l0 L0;
    public static final t2l0 M;
    public static final t2l0 M0;
    public static final t2l0 N;
    public static final t2l0 N0;
    public static final t2l0 O;
    public static final t2l0 O0;
    public static final t2l0 P;
    public static final t2l0 P0;
    public static final t2l0 Q;
    public static final t2l0 Q0;
    public static final t2l0 R;
    public static final t2l0 R0;
    public static final t2l0 S;
    public static final t2l0 S0;
    public static final t2l0 T;
    public static final t2l0 T0;
    public static final t2l0 U;
    public static final t2l0 U0;
    public static final t2l0 V;
    public static final t2l0 V0;
    public static final t2l0 W;
    public static final t2l0 W0;
    public static final t2l0 X;
    public static final t2l0 X0;
    public static final t2l0 Y;
    public static final t2l0 Y0;
    public static final t2l0 Z;
    public static final t2l0 Z0;
    public static final List a = Collections.synchronizedList(new ArrayList());
    public static final t2l0 a0;
    public static final t2l0 a1;
    public static final t2l0 b;
    public static final t2l0 b0;
    public static final t2l0 b1;
    public static final t2l0 c;
    public static final t2l0 c0;
    public static final t2l0 c1;
    public static final t2l0 d;
    public static final t2l0 d0;
    public static final t2l0 d1;
    public static final t2l0 e;
    public static final t2l0 e0;
    public static final t2l0 e1;
    public static final t2l0 f;
    public static final t2l0 f0;
    public static final t2l0 f1;
    public static final t2l0 g;
    public static final t2l0 g0;
    public static final t2l0 g1;
    public static final t2l0 h;
    public static final t2l0 h0;
    public static final t2l0 h1;
    public static final t2l0 i;
    public static final t2l0 i0;
    public static final t2l0 i1;
    public static final t2l0 j;
    public static final t2l0 j0;
    public static final t2l0 j1;
    public static final t2l0 k;
    public static final t2l0 k0;
    public static final t2l0 k1;
    public static final t2l0 l;
    public static final t2l0 l0;
    public static final t2l0 m;
    public static final t2l0 m0;
    public static final t2l0 n;
    public static final t2l0 n0;
    public static final t2l0 o;
    public static final t2l0 o0;
    public static final t2l0 p;
    public static final t2l0 p0;
    public static final t2l0 q;
    public static final t2l0 q0;
    public static final t2l0 r;
    public static final t2l0 r0;
    public static final t2l0 s;
    public static final t2l0 s0;
    public static final t2l0 t;
    public static final t2l0 t0;
    public static final t2l0 u;
    public static final t2l0 u0;
    public static final t2l0 v;
    public static final t2l0 v0;
    public static final t2l0 w;
    public static final t2l0 w0;
    public static final t2l0 x;
    public static final t2l0 x0;
    public static final t2l0 y;
    public static final t2l0 y0;
    public static final t2l0 z;
    public static final t2l0 z0;

    public static t2l0 a(String str, Object obj, otk0 otk0Var, boolean z2) {
        t2l0 t2l0Var = new t2l0(str, obj, otk0Var);
        if (z2) {
            a.add(t2l0Var);
        }
        return t2l0Var;
    }

    static {
        Collections.synchronizedSet(new HashSet());
        b = a("measurement.ad_id_cache_time", 10000L, okm.b, false);
        c = a("measurement.app_uninstalled_additional_ad_id_cache_time", 3600000L, qtk0.a, false);
        d = a("measurement.monitoring.sample_period_millis", 86400000L, z240.b, false);
        e = a("measurement.config.cache_time", 86400000L, svk0.a, false);
        f = a("measurement.config.url_scheme", "https", axk0.a, false);
        g = a("measurement.config.url_authority", "app-measurement.com", xxk0.a, false);
        h = a("measurement.upload.max_bundles", 100, ut8.c, false);
        i = a("measurement.upload.max_batch_size", 65536, zzk0.a, false);
        j = a("measurement.upload.max_bundle_size", 65536, ugm.c, false);
        k = a("measurement.upload.max_events_per_bundle", 1000, img0.b, false);
        l = a("measurement.upload.max_events_per_day", 100000, ekm.b, false);
        m = a("measurement.upload.max_error_events_per_day", 1000, auk0.a, false);
        n = a("measurement.upload.max_public_events_per_day", 50000, buk0.a, false);
        o = a("measurement.upload.max_conversions_per_day", 10000, duk0.a, false);
        p = a("measurement.upload.max_realtime_events_per_day", 10, fuk0.a, false);
        q = a("measurement.store.max_stored_events_per_app", 100000, huk0.a, false);
        r = a("measurement.upload.url", "https://app-measurement.com/a", u240.b, false);
        s = a("measurement.sgtm.google_signal.url", "https://app-measurement.com/s/d", hvk0.a, false);
        t = a("measurement.sgtm.service_upload_apps_list", "", w240.b, false);
        u = a("measurement.sgtm.upload.backoff_http_codes", "404,429,503,504", xp8.d, false);
        v = a("measurement.sgtm.upload.retry_interval", 600000L, ivk0.a, false);
        w = a("measurement.sgtm.upload.retry_max_wait", 21600000L, kvk0.a, false);
        x = a("measurement.sgtm.batch.retry_interval", 1800000L, c340.b, false);
        y = a("measurement.sgtm.batch.retry_max_wait", 21600000L, d340.b, false);
        z = a("measurement.sgtm.batch.retry_max_count", 10, nvk0.a, false);
        A = a("measurement.sgtm.upload.max_queued_batches", 5000, g340.b, false);
        B = a("measurement.sgtm.upload.batches_retrieval_limit", 5, h340.b, false);
        C = a("measurement.sgtm.upload.min_delay_after_startup", 5000L, ovk0.a, false);
        D = a("measurement.sgtm.upload.min_delay_after_broadcast", 1000L, id00.b, false);
        E = a("measurement.sgtm.upload.min_delay_after_background", 600000L, jd00.b, false);
        F = a("measurement.sgtm.batch.long_queuing_threshold", 14400000L, sd00.a, false);
        G = a("measurement.upload.backoff_period", 43200000L, uvk0.a, false);
        a("measurement.upload.window_interval", 3600000L, t7h.b, false);
        H = a("measurement.upload.interval", 3600000L, be00.a, false);
        I = a("measurement.upload.realtime_upload_interval", 10000L, yvk0.a, false);
        J = a("measurement.upload.debug_upload_interval", 1000L, awk0.a, false);
        K = a("measurement.upload.minimum_delay", 500L, om80.b, false);
        L = a("measurement.alarm_manager.minimum_interval", Long.valueOf(RealWebSocket.CANCEL_AFTER_CLOSE_MILLIS), pm80.b, false);
        M = a("measurement.upload.stale_data_deletion_interval", 86400000L, w8h.a, false);
        N = a("measurement.upload.refresh_blacklisted_config_interval", 604800000L, dr8.y, false);
        O = a("measurement.upload.initial_upload_delay_time", 15000L, ywk0.a, false);
        P = a("measurement.upload.retry_time", 1800000L, cxk0.a, false);
        Q = a("measurement.upload.retry_count", 6, exk0.a, false);
        R = a("measurement.upload.max_queue_time", 518400000L, gxk0.a, false);
        S = a("measurement.upload.google_signal_max_queue_time", 300000L, bo3.b, false);
        T = a("measurement.lifetimevalue.max_currency_tracked", 4, co3.b, false);
        U = a("measurement.audience.filter_result_max_count", Integer.valueOf(r.d.DEFAULT_DRAG_ANIMATION_DURATION), kxk0.a, false);
        V = a("measurement.upload.max_public_user_properties", 100, null, false);
        W = a("measurement.upload.max_event_name_cardinality", 2000, null, false);
        X = a("measurement.upload.max_public_event_params", 100, null, false);
        Y = a("measurement.service_client.idle_disconnect_millis", 5000L, nxk0.a, false);
        Z = a(ACKxwYRsuWyGz.sPzHrODdKNyPYB, 1000L, qxk0.a, false);
        Boolean bool = Boolean.FALSE;
        a0 = a("measurement.test.boolean_flag", bool, txk0.a, false);
        b0 = a("measurement.test.string_flag", "---", vxk0.a, false);
        c0 = a("measurement.test.long_flag", -1L, ys8.b, false);
        a("measurement.test.cached_long_flag", -1L, at8.b, true);
        d0 = a("measurement.test.int_flag", -2, cyk0.a, false);
        e0 = a("measurement.test.double_flag", Double.valueOf(-3.0d), dyk0.a, false);
        f0 = a("measurement.experiment.max_ids", 50, gt8.b, false);
        g0 = a("measurement.upload.max_item_scoped_custom_parameters", 27, hyk0.a, false);
        h0 = a("measurement.upload.max_event_parameter_value_length", 500, vgg0.a, true);
        i0 = a("measurement.max_bundles_per_iteration", 100, nt8.c, false);
        j0 = a("measurement.sdk.attribution.cache.ttl", 604800000L, oyk0.a, false);
        k0 = a("measurement.redaction.app_instance_id.ttl", 7200000L, qyk0.a, false);
        l0 = a("measurement.rb.attribution.client.min_ad_services_version", 7, ei00.b, false);
        m0 = a("measurement.dma_consent.max_daily_dcu_realtime_events", 1, vyk0.a, false);
        n0 = a("measurement.rb.attribution.uri_scheme", "https", bbc0.a, false);
        o0 = a("measurement.rb.attribution.uri_authority", "google-analytics.com", lu8.b, false);
        p0 = a("measurement.rb.attribution.uri_path", "privacy-sandbox/register-app-conversion", qzk0.a, false);
        q0 = a("measurement.session.engagement_interval", 3600000L, zbc0.a, false);
        r0 = a("measurement.rb.attribution.app_allowlist", "", tzk0.a, false);
        s0 = a("measurement.rb.attribution.user_properties", "_npa,npa|_fot,fot", ua40.b, false);
        t0 = a("measurement.rb.attribution.event_params", "value|currency", wzk0.a, false);
        u0 = a("measurement.rb.attribution.query_parameters_to_remove", "", bv8.b, false);
        v0 = a("measurement.rb.attribution.max_queue_time", 864000000L, cb40.a, false);
        w0 = a("measurement.rb.attribution.max_retry_delay_seconds", 16, ev8.b, false);
        x0 = a("measurement.rb.attribution.client.min_time_after_boot_seconds", 90, fv8.b, false);
        a("measurement.rb.attribution.max_trigger_uris_queried_at_once", 0, uig0.c, false);
        y0 = a("measurement.rb.max_trigger_registrations_per_day", 1000, c8r.b, false);
        Boolean bool2 = Boolean.TRUE;
        z0 = a("measurement.config.bundle_for_all_apps_on_backgrounded", bool2, d8r.b, false);
        A0 = a("measurement.config.notify_trigger_uris_on_backgrounded", bool2, f0l0.a, false);
        B0 = a("measurement.rb.attribution.notify_app_delay_millis", 3000, ov8.e, false);
        C0 = a("measurement.quality.checksum", bool, null, false);
        D0 = a("measurement.audience.use_bundle_end_timestamp_for_non_sequence_property_filters", bool, i0l0.a, false);
        E0 = a("measurement.audience.refresh_event_count_filters_timestamp", bool, edc0.a, false);
        F0 = a("measurement.audience.use_bundle_timestamp_for_event_count_filters", bool, o0l0.a, true);
        G0 = a("measurement.sdk.collection.last_deep_link_referrer_campaign2", bool, ueh.b, false);
        H0 = a("measurement.integration.disable_firebase_instance_id", bool, qdc0.b, false);
        I0 = a("measurement.collection.service.update_with_analytics_fix", bool, gw8.e, false);
        J0 = a("measurement.service.storage_consent_support_version", 203600, iw8.c, false);
        K0 = a("measurement.service.store_null_safelist", bool2, kw8.b, false);
        L0 = a("measurement.service.store_safelist", bool2, shm.b, false);
        M0 = a("measurement.session_stitching_token_enabled", bool, q1l0.a, false);
        N0 = a("measurement.sgtm.client.upload_on_backgrounded.dev", bool, s1l0.a, true);
        O0 = a("measurement.gmscore_client_telemetry", bool, ylc.c, false);
        P0 = a("measurement.rb.attribution.service", bool2, uw8.b, true);
        Q0 = a("measurement.rb.attribution.client2", bool2, jmg0.b, true);
        R0 = a("measurement.rb.attribution.uuid_generation", bool2, uec0.a, false);
        S0 = a("measurement.rb.attribution.enable_trigger_redaction", bool2, y1l0.a, false);
        a("measurement.rb.attribution.followup1.service", bool, a2l0.a, false);
        T0 = a("measurement.rb.attribution.retry_disposition", bool, cx8.f, false);
        U0 = a("measurement.client.sessions.enable_fix_background_engagement", bool, r2l0.a, false);
        V0 = a("measurement.set_default_event_parameters_propagate_clear.service.dev", bool2, vmg0.a, false);
        W0 = a("measurement.set_default_event_parameters_propagate_clear.client.dev", bool2, fx8.c, false);
        X0 = a("measurement.service.ad_impression.convert_value_to_double", bool2, e2l0.a, false);
        a("measurement.rb.attribution.service.enable_max_trigger_uris_queried_at_once", bool2, hx8.b, false);
        a("measurement.remove_conflicting_first_party_apis.dev", bool, h2l0.a, false);
        Y0 = a("measurement.rb.attribution.service.trigger_uris_high_priority", bool2, ttk0.a, false);
        Z0 = a("measurement.tcf.consent_fix", bool2, d240.b, false);
        a1 = a("measurement.experiment.enable_phenotype_experiment_reporting", bool2, jam.b, false);
        b1 = a("measurement.set_default_event_parameters.fix_service_request_ordering", bool, f4h.a, false);
        c1 = a("measurement.set_default_event_parameters.fix_app_update_logging", bool2, gtk0.a, false);
        d1 = a("measurement.service.fix_stop_bundling_bug", bool2, fdc.b, false);
        e1 = a("measurement.fix_params_logcat_spam", bool2, n4h.a, false);
        f1 = a("measurement.gbraid_campaign.stop_lgclid", bool, rlc.b, false);
        g1 = a("measurement.gbraid_compaign.compaign_params_triggering_info_update", "gclid,gbraid,gad_campaignid", r5h.b, false);
        h1 = a("measurement.edpb.service", bool, va00.a, false);
        i1 = a("measurement.edpb.events_cached_in_no_data_mode", "_f,_v,_cmp", wtk0.a, false);
        j1 = a("measurement.add_first_launch_logging_timestamp.service", bool, p2l0.a, false);
        k1 = a("measurement.overlapping_bundles_fix", bool, ytk0.a, false);
    }
}
