package defpackage;

import android.view.View;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.appcompat.widget.AppCompatTextView;
import androidx.compose.ui.platform.ComposeView;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.constraintlayout.widget.Group;
import androidx.drawerlayout.widget.DrawerLayout;
import androidx.viewpager2.widget.ViewPager2;
import com.sportygames.commons.components.GiftToast;
import com.sportygames.commons.components.ProgressMeterComponent;
import com.sportygames.commons.components.SGHamburgerMenu;
import com.sportygames.commons.utils.SnowfallView;
import com.sportygames.crash.components.header.DepositTooltipComponent;
import com.sportygames.sportyherov2.components.SHKeypadContainer;
import com.sportygames.sportyherov2.components.SHOverBetComponent;
import com.sportygames.sportyherov2.components.SHRangeComponent;
import com.sportygames.sportyherov2.components.SHToastContainer;
import com.sportygames.sportyherov2.components.ShAllBetList;
import com.sportygames.sportyherov2.components.ShBetContainer;
import com.sportygames.sportyherov2.components.ShHeaderContainer;
import com.sportygames.sportyherov2.components.ShMultiplierContainer;
import com.sportygames.sportyherov2.components.ShRoundHistoryContainer;
import com.sportygames.sportyherov2.components.SideBetTabContainer;
import eightbitlab.com.blurview.BlurView;

/* JADX INFO: loaded from: classes8.dex */
public final class w3c0 implements g6i0 {
    public final BlurView A;
    public final LinearLayout A0;
    public final BlurView B;
    public final ViewPager2 B0;
    public final BlurView C;
    public final View C0;
    public final ImageView D;
    public final View D0;
    public final ImageView E;
    public final TextView F;
    public final TextView G;
    public final prr H;
    public final ComposeView I;
    public final DrawerLayout J;
    public final View K;
    public final ConstraintLayout L;
    public final ComposeView M;
    public final GiftToast N;
    public final SGHamburgerMenu O;
    public final ShHeaderContainer P;
    public final ConstraintLayout Q;
    public final SHKeypadContainer R;
    public final FrameLayout S;
    public final ShMultiplierContainer T;
    public final AppCompatTextView U;
    public final SHToastContainer V;
    public final ComposeView W;
    public final FrameLayout X;
    public final SHKeypadContainer Y;
    public final SHKeypadContainer Z;
    public final ConstraintLayout a;
    public final SHOverBetComponent a0;
    public final ConstraintLayout b;
    public final ConstraintLayout b0;
    public final AppCompatTextView c;
    public final ShRoundHistoryContainer c0;
    public final ShBetContainer d;
    public final ProgressMeterComponent d0;
    public final ShBetContainer e;
    public final ap80 e0;
    public final Group f;
    public final SHToastContainer f0;
    public final cp80 g0;
    public final SHKeypadContainer h0;
    public final View i;
    public final SHKeypadContainer i0;
    public final SHRangeComponent j0;
    public final ShAllBetList k0;
    public final SideBetTabContainer l0;
    public final Group m0;
    public final Group n0;
    public final SnowfallView o0;
    public final View p0;
    public final View q0;
    public final View r0;
    public final View s0;
    public final View t0;
    public final View u0;
    public final BlurView v;
    public final View v0;
    public final BlurView w;
    public final SHToastContainer w0;
    public final DepositTooltipComponent x0;
    public final BlurView y;
    public final AppCompatTextView y0;
    public final FrameLayout z;
    public final LinearLayout z0;

    public w3c0(ConstraintLayout constraintLayout, ConstraintLayout constraintLayout2, AppCompatTextView appCompatTextView, ShBetContainer shBetContainer, ShBetContainer shBetContainer2, Group group, View view, BlurView blurView, BlurView blurView2, BlurView blurView3, FrameLayout frameLayout, BlurView blurView4, BlurView blurView5, BlurView blurView6, ImageView imageView, ImageView imageView2, TextView textView, TextView textView2, prr prrVar, ComposeView composeView, DrawerLayout drawerLayout, View view2, FrameLayout frameLayout2, ConstraintLayout constraintLayout3, ComposeView composeView2, GiftToast giftToast, SGHamburgerMenu sGHamburgerMenu, ShHeaderContainer shHeaderContainer, ConstraintLayout constraintLayout4, SHKeypadContainer sHKeypadContainer, FrameLayout frameLayout3, ShMultiplierContainer shMultiplierContainer, AppCompatTextView appCompatTextView2, SHToastContainer sHToastContainer, ComposeView composeView3, FrameLayout frameLayout4, SHKeypadContainer sHKeypadContainer2, SHKeypadContainer sHKeypadContainer3, SHOverBetComponent sHOverBetComponent, ConstraintLayout constraintLayout5, ShRoundHistoryContainer shRoundHistoryContainer, ProgressMeterComponent progressMeterComponent, ap80 ap80Var, SHToastContainer sHToastContainer2, cp80 cp80Var, SHKeypadContainer sHKeypadContainer4, SHKeypadContainer sHKeypadContainer5, SHRangeComponent sHRangeComponent, ShAllBetList shAllBetList, SideBetTabContainer sideBetTabContainer, Group group2, Group group3, SnowfallView snowfallView, View view3, View view4, View view5, View view6, View view7, View view8, View view9, SHToastContainer sHToastContainer3, DepositTooltipComponent depositTooltipComponent, AppCompatTextView appCompatTextView3, LinearLayout linearLayout, LinearLayout linearLayout2, ViewPager2 viewPager2, View view10, View view11) {
        this.a = constraintLayout;
        this.b = constraintLayout2;
        this.c = appCompatTextView;
        this.d = shBetContainer;
        this.e = shBetContainer2;
        this.f = group;
        this.i = view;
        this.v = blurView;
        this.w = blurView2;
        this.y = blurView3;
        this.z = frameLayout;
        this.A = blurView4;
        this.B = blurView5;
        this.C = blurView6;
        this.D = imageView;
        this.E = imageView2;
        this.F = textView;
        this.G = textView2;
        this.H = prrVar;
        this.I = composeView;
        this.J = drawerLayout;
        this.K = view2;
        this.L = constraintLayout3;
        this.M = composeView2;
        this.N = giftToast;
        this.O = sGHamburgerMenu;
        this.P = shHeaderContainer;
        this.Q = constraintLayout4;
        this.R = sHKeypadContainer;
        this.S = frameLayout3;
        this.T = shMultiplierContainer;
        this.U = appCompatTextView2;
        this.V = sHToastContainer;
        this.W = composeView3;
        this.X = frameLayout4;
        this.Y = sHKeypadContainer2;
        this.Z = sHKeypadContainer3;
        this.a0 = sHOverBetComponent;
        this.b0 = constraintLayout5;
        this.c0 = shRoundHistoryContainer;
        this.d0 = progressMeterComponent;
        this.e0 = ap80Var;
        this.f0 = sHToastContainer2;
        this.g0 = cp80Var;
        this.h0 = sHKeypadContainer4;
        this.i0 = sHKeypadContainer5;
        this.j0 = sHRangeComponent;
        this.k0 = shAllBetList;
        this.l0 = sideBetTabContainer;
        this.m0 = group2;
        this.n0 = group3;
        this.o0 = snowfallView;
        this.p0 = view3;
        this.q0 = view4;
        this.r0 = view5;
        this.s0 = view6;
        this.t0 = view7;
        this.u0 = view8;
        this.v0 = view9;
        this.w0 = sHToastContainer3;
        this.x0 = depositTooltipComponent;
        this.y0 = appCompatTextView3;
        this.z0 = linearLayout;
        this.A0 = linearLayout2;
        this.B0 = viewPager2;
        this.C0 = view10;
        this.D0 = view11;
    }

    @Override // defpackage.g6i0
    public final View getRoot() {
        return this.a;
    }
}
