package defpackage;

import android.view.View;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.constraintlayout.widget.ConstraintLayout;

/* JADX INFO: loaded from: classes6.dex */
public final class yp80 implements g6i0 {
    public final TextView A;
    public final TextView A0;
    public final ConstraintLayout A1;
    public final TextView B;
    public final TextView B0;
    public final ConstraintLayout B1;
    public final TextView C;
    public final TextView C0;
    public final ConstraintLayout C1;
    public final TextView D;
    public final TextView D0;
    public final ConstraintLayout D1;
    public final TextView E;
    public final TextView E0;
    public final ConstraintLayout E1;
    public final TextView F;
    public final TextView F0;
    public final ConstraintLayout F1;
    public final TextView G;
    public final TextView G0;
    public final TextView H;
    public final TextView H0;
    public final TextView I;
    public final TextView I0;
    public final TextView J;
    public final TextView J0;
    public final ConstraintLayout K;
    public final TextView K0;
    public final ConstraintLayout L;
    public final TextView L0;
    public final ConstraintLayout M;
    public final TextView M0;
    public final ConstraintLayout N;
    public final TextView N0;
    public final ConstraintLayout O;
    public final TextView O0;
    public final ConstraintLayout P;
    public final TextView P0;
    public final ConstraintLayout Q;
    public final TextView Q0;
    public final ConstraintLayout R;
    public final TextView R0;
    public final ConstraintLayout S;
    public final TextView S0;
    public final ConstraintLayout T;
    public final TextView T0;
    public final ConstraintLayout U;
    public final TextView U0;
    public final ConstraintLayout V;
    public final TextView V0;
    public final ConstraintLayout W;
    public final TextView W0;
    public final ConstraintLayout X;
    public final TextView X0;
    public final ConstraintLayout Y;
    public final TextView Y0;
    public final ConstraintLayout Z;
    public final TextView Z0;
    public final ConstraintLayout a;
    public final ConstraintLayout a0;
    public final TextView a1;
    public final TextView b;
    public final ConstraintLayout b0;
    public final TextView b1;
    public final TextView c;
    public final ConstraintLayout c0;
    public final TextView c1;
    public final TextView d;
    public final ConstraintLayout d0;
    public final TextView d1;
    public final TextView e;
    public final ImageView e0;
    public final TextView e1;
    public final TextView f;
    public final ImageView f0;
    public final TextView f1;
    public final ImageView g0;
    public final TextView g1;
    public final ImageView h0;
    public final TextView h1;
    public final TextView i;
    public final ImageView i0;
    public final TextView i1;
    public final ImageView j0;
    public final TextView j1;
    public final ImageView k0;
    public final TextView k1;
    public final ImageView l0;
    public final TextView l1;
    public final ImageView m0;
    public final ConstraintLayout m1;
    public final ImageView n0;
    public final ConstraintLayout n1;
    public final ImageView o0;
    public final ConstraintLayout o1;
    public final ImageView p0;
    public final ConstraintLayout p1;
    public final ImageView q0;
    public final ConstraintLayout q1;
    public final ImageView r0;
    public final ConstraintLayout r1;
    public final ImageView s0;
    public final ConstraintLayout s1;
    public final ImageView t0;
    public final ConstraintLayout t1;
    public final ImageView u0;
    public final ConstraintLayout u1;
    public final TextView v;
    public final ImageView v0;
    public final ConstraintLayout v1;
    public final TextView w;
    public final ImageView w0;
    public final ConstraintLayout w1;
    public final ImageView x0;
    public final ConstraintLayout x1;
    public final TextView y;
    public final TextView y0;
    public final ConstraintLayout y1;
    public final TextView z;
    public final TextView z0;
    public final ConstraintLayout z1;

    public yp80(ConstraintLayout constraintLayout, TextView textView, TextView textView2, TextView textView3, TextView textView4, TextView textView5, TextView textView6, TextView textView7, TextView textView8, TextView textView9, TextView textView10, TextView textView11, TextView textView12, TextView textView13, TextView textView14, TextView textView15, TextView textView16, TextView textView17, TextView textView18, TextView textView19, TextView textView20, ConstraintLayout constraintLayout2, ConstraintLayout constraintLayout3, ConstraintLayout constraintLayout4, ConstraintLayout constraintLayout5, ConstraintLayout constraintLayout6, ConstraintLayout constraintLayout7, ConstraintLayout constraintLayout8, ConstraintLayout constraintLayout9, ConstraintLayout constraintLayout10, ConstraintLayout constraintLayout11, ConstraintLayout constraintLayout12, ConstraintLayout constraintLayout13, ConstraintLayout constraintLayout14, ConstraintLayout constraintLayout15, ConstraintLayout constraintLayout16, ConstraintLayout constraintLayout17, ConstraintLayout constraintLayout18, ConstraintLayout constraintLayout19, ConstraintLayout constraintLayout20, ConstraintLayout constraintLayout21, ImageView imageView, ImageView imageView2, ImageView imageView3, ImageView imageView4, ImageView imageView5, ImageView imageView6, ImageView imageView7, ImageView imageView8, ImageView imageView9, ImageView imageView10, ImageView imageView11, ImageView imageView12, ImageView imageView13, ImageView imageView14, ImageView imageView15, ImageView imageView16, ImageView imageView17, ImageView imageView18, ImageView imageView19, ImageView imageView20, TextView textView21, TextView textView22, TextView textView23, TextView textView24, TextView textView25, TextView textView26, TextView textView27, TextView textView28, TextView textView29, TextView textView30, TextView textView31, TextView textView32, TextView textView33, TextView textView34, TextView textView35, TextView textView36, TextView textView37, TextView textView38, TextView textView39, TextView textView40, TextView textView41, TextView textView42, TextView textView43, TextView textView44, TextView textView45, TextView textView46, TextView textView47, TextView textView48, TextView textView49, TextView textView50, TextView textView51, TextView textView52, TextView textView53, TextView textView54, TextView textView55, TextView textView56, TextView textView57, TextView textView58, TextView textView59, TextView textView60, ConstraintLayout constraintLayout22, ConstraintLayout constraintLayout23, ConstraintLayout constraintLayout24, ConstraintLayout constraintLayout25, ConstraintLayout constraintLayout26, ConstraintLayout constraintLayout27, ConstraintLayout constraintLayout28, ConstraintLayout constraintLayout29, ConstraintLayout constraintLayout30, ConstraintLayout constraintLayout31, ConstraintLayout constraintLayout32, ConstraintLayout constraintLayout33, ConstraintLayout constraintLayout34, ConstraintLayout constraintLayout35, ConstraintLayout constraintLayout36, ConstraintLayout constraintLayout37, ConstraintLayout constraintLayout38, ConstraintLayout constraintLayout39, ConstraintLayout constraintLayout40, ConstraintLayout constraintLayout41) {
        this.a = constraintLayout;
        this.b = textView;
        this.c = textView2;
        this.d = textView3;
        this.e = textView4;
        this.f = textView5;
        this.i = textView6;
        this.v = textView7;
        this.w = textView8;
        this.y = textView9;
        this.z = textView10;
        this.A = textView11;
        this.B = textView12;
        this.C = textView13;
        this.D = textView14;
        this.E = textView15;
        this.F = textView16;
        this.G = textView17;
        this.H = textView18;
        this.I = textView19;
        this.J = textView20;
        this.K = constraintLayout2;
        this.L = constraintLayout3;
        this.M = constraintLayout4;
        this.N = constraintLayout5;
        this.O = constraintLayout6;
        this.P = constraintLayout7;
        this.Q = constraintLayout8;
        this.R = constraintLayout9;
        this.S = constraintLayout10;
        this.T = constraintLayout11;
        this.U = constraintLayout12;
        this.V = constraintLayout13;
        this.W = constraintLayout14;
        this.X = constraintLayout15;
        this.Y = constraintLayout16;
        this.Z = constraintLayout17;
        this.a0 = constraintLayout18;
        this.b0 = constraintLayout19;
        this.c0 = constraintLayout20;
        this.d0 = constraintLayout21;
        this.e0 = imageView;
        this.f0 = imageView2;
        this.g0 = imageView3;
        this.h0 = imageView4;
        this.i0 = imageView5;
        this.j0 = imageView6;
        this.k0 = imageView7;
        this.l0 = imageView8;
        this.m0 = imageView9;
        this.n0 = imageView10;
        this.o0 = imageView11;
        this.p0 = imageView12;
        this.q0 = imageView13;
        this.r0 = imageView14;
        this.s0 = imageView15;
        this.t0 = imageView16;
        this.u0 = imageView17;
        this.v0 = imageView18;
        this.w0 = imageView19;
        this.x0 = imageView20;
        this.y0 = textView21;
        this.z0 = textView22;
        this.A0 = textView23;
        this.B0 = textView24;
        this.C0 = textView25;
        this.D0 = textView26;
        this.E0 = textView27;
        this.F0 = textView28;
        this.G0 = textView29;
        this.H0 = textView30;
        this.I0 = textView31;
        this.J0 = textView32;
        this.K0 = textView33;
        this.L0 = textView34;
        this.M0 = textView35;
        this.N0 = textView36;
        this.O0 = textView37;
        this.P0 = textView38;
        this.Q0 = textView39;
        this.R0 = textView40;
        this.S0 = textView41;
        this.T0 = textView42;
        this.U0 = textView43;
        this.V0 = textView44;
        this.W0 = textView45;
        this.X0 = textView46;
        this.Y0 = textView47;
        this.Z0 = textView48;
        this.a1 = textView49;
        this.b1 = textView50;
        this.c1 = textView51;
        this.d1 = textView52;
        this.e1 = textView53;
        this.f1 = textView54;
        this.g1 = textView55;
        this.h1 = textView56;
        this.i1 = textView57;
        this.j1 = textView58;
        this.k1 = textView59;
        this.l1 = textView60;
        this.m1 = constraintLayout22;
        this.n1 = constraintLayout23;
        this.o1 = constraintLayout24;
        this.p1 = constraintLayout25;
        this.q1 = constraintLayout26;
        this.r1 = constraintLayout27;
        this.s1 = constraintLayout28;
        this.t1 = constraintLayout29;
        this.u1 = constraintLayout30;
        this.v1 = constraintLayout31;
        this.w1 = constraintLayout32;
        this.x1 = constraintLayout33;
        this.y1 = constraintLayout34;
        this.z1 = constraintLayout35;
        this.A1 = constraintLayout36;
        this.B1 = constraintLayout37;
        this.C1 = constraintLayout38;
        this.D1 = constraintLayout39;
        this.E1 = constraintLayout40;
        this.F1 = constraintLayout41;
    }

    @Override // defpackage.g6i0
    public final View getRoot() {
        return this.a;
    }
}
