server {
    listen 80;
    listen [::]:80;
    server_name api.soccerarena.org 139.59.93.218;
    access_log off;
    error_log /var/log/nginx/soccerarena-error.log warn;
    client_max_body_size 1m;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/soccerarena-acme;
        try_files $uri =404;
    }
    location /static/ {
        alias /srv/soccerarena/current/staticfiles/;
        add_header Access-Control-Allow-Origin '*' always;
    }
    location / {
        include /etc/nginx/snippets/soccerarena-proxy.conf;
    }
}
