package com.sporty.android.core.model.config.bo.enums;

import androidx.recyclerview.widget.r;
import com.google.android.gms.common.annotation.LjLk.llGRV;
import com.google.android.gms.dynamite.descriptors.com.google.android.gms.measurement.dynamite.ModuleDescriptor;
import com.sporty.android.core.model.betbuilder.BetBuilderExclusionFilters;
import com.sporty.android.core.model.cashout.CashOutMetricsSamplingUserIdTailDto;
import com.sporty.android.core.model.cashout.CashoutAdditionalMarketSpecifierMap;
import com.sporty.android.core.model.cashout.CashoutProviderMarketRulesMap;
import com.sporty.android.core.model.cashout.CashoutQuickReinvestConfig;
import com.sporty.android.core.model.cashout.CashoutSuspendDeactivateAllowConfigs;
import com.sporty.android.core.model.common.Range;
import com.sporty.android.core.model.config.BoreDrawSelectionEligibilityDto;
import com.sporty.android.core.model.config.bo.BOConfigDeserializeOption;
import com.sporty.android.core.model.config.bo.BOConfigFeatureFlag;
import com.sporty.android.core.model.config.bo.IBOConfigParam;
import com.sporty.android.core.model.config.tax.WinningTaxRateMap;
import com.sporty.android.core.model.eventdetails.NewBadgeEventDetailsValue;
import com.sporty.android.core.model.instantwin.BuildAndGoTabConfig;
import com.sporty.android.core.model.instantwin.InstantWinPromotionData;
import com.sporty.android.core.model.instantwin.NetworkVirtualInHouseGamePromotionBanner;
import com.sporty.android.core.model.multimaker.MultiMakerTotalOddsBOSettings;
import com.sporty.android.core.model.otp.RegisterVCodeIgnoreConfigMap;
import com.sporty.android.core.model.pay.bo.PhonePrefixData;
import com.sporty.android.core.model.pocket.common.PLAOperatorBOConfig;
import com.sporty.android.core.model.pocket.common.PayHintData;
import com.sporty.android.core.model.pocket.common.TradingAmountMap;
import com.sporty.android.core.model.pocket.common.UserAdditionalPhoneConfig;
import com.sporty.android.core.model.pocket.common.WhTaxData;
import com.sporty.android.core.model.pocket.withdraw.PartnerWithdrawFeeConfigDto;
import com.sporty.android.core.model.realsports.EarlyPayoutConfigModel;
import com.sporty.android.core.model.realsports.FlexiBetBoConfigOddsKey;
import com.sporty.android.core.model.realsports.OddsFilterEventCountData;
import com.sporty.android.core.model.social.CodeChatBOConfigModel;
import com.sporty.android.core.model.social.ShareMyBetBOConfigModel;
import com.sporty.android.core.model.virtual.BannerItem;
import com.sporty.android.core.model.virtual.MainEntranceItem;
import com.sporty.android.core.model.watchdog.HangWatchdogConfigData;
import com.sporty.android.core.model.worldcuptournament.WorldCupTeam;
import com.sporty.android.core.model.worldcuptournament.WorldCupTournamentPageGroup;
import com.sportybet.android.instantwin.presentation.legendsrace.AxRn.LGxrN;
import defpackage.jq40;
import defpackage.om2;
import defpackage.tag;
import java.math.BigDecimal;
import java.util.Map;
import kotlin.Metadata;
import kotlin.jvm.internal.DefaultConstructorMarker;
import okhttp3.internal.http.HttpStatusCodesKt;
import okhttp3.internal.ws.WebSocketProtocol;

/* JADX WARN: Enum visitor error
jadx.core.utils.exceptions.JadxRuntimeException: Init of enum field 'PaychAlertContent' uses external variables
	at jadx.core.dex.visitors.EnumVisitor.createEnumFieldByConstructor(EnumVisitor.java:485)
	at jadx.core.dex.visitors.EnumVisitor.processEnumFieldByField(EnumVisitor.java:399)
	at jadx.core.dex.visitors.EnumVisitor.processEnumFieldByWrappedInsn(EnumVisitor.java:364)
	at jadx.core.dex.visitors.EnumVisitor.extractEnumFieldsFromFilledArray(EnumVisitor.java:349)
	at jadx.core.dex.visitors.EnumVisitor.extractEnumFieldsFromInsn(EnumVisitor.java:284)
	at jadx.core.dex.visitors.EnumVisitor.extractEnumFieldsFromInvoke(EnumVisitor.java:315)
	at jadx.core.dex.visitors.EnumVisitor.extractEnumFieldsFromInsn(EnumVisitor.java:288)
	at jadx.core.dex.visitors.EnumVisitor.convertToEnum(EnumVisitor.java:160)
	at jadx.core.dex.visitors.EnumVisitor.visit(EnumVisitor.java:102)
 */
/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX INFO: loaded from: classes4.dex */
@Metadata(d1 = {"\u0000)\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0010\u0010\n\u0000\n\u0002\u0018\u0002\n\u0000\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u000e\n\u0000\n\u0002\u0018\u0002\n\u0003\bØ\u0001\b\u0086\u0081\u0002\u0018\u00002\u00020\u00012\b\u0012\u0004\u0012\u00020\u00000\u0002B+\b\u0002\u0012\u0006\u0010\u0003\u001a\u00020\u0004\u0012\u0006\u0010\u0005\u001a\u00020\u0006\u0012\u0006\u0010\u0007\u001a\u00020\b\u0012\b\b\u0002\u0010\t\u001a\u00020\n¢\u0006\u0004\b\u000b\u0010\fR\u0014\u0010\u0003\u001a\u00020\u0004X\u0096\u0004¢\u0006\b\n\u0000\u001a\u0004\b\r\u0010\u000eR\u0014\u0010\u0005\u001a\u00020\u0006X\u0096\u0004¢\u0006\b\n\u0000\u001a\u0004\b\u000f\u0010\u0010R\u0014\u0010\u0007\u001a\u00020\bX\u0096\u0004¢\u0006\b\n\u0000\u001a\u0004\b\u0011\u0010\u0012R\u0014\u0010\t\u001a\u00020\nX\u0096\u0004¢\u0006\b\n\u0000\u001a\u0004\b\u0013\u0010\u0014j\u0002\b\u0015j\u0002\b\u0016j\u0002\b\u0017j\u0002\b\u0018j\u0002\b\u0019j\u0002\b\u001aj\u0002\b\u001bj\u0002\b\u001cj\u0002\b\u001dj\u0002\b\u001ej\u0002\b\u001fj\u0002\b j\u0002\b!j\u0002\b\"j\u0002\b#j\u0002\b$j\u0002\b%j\u0002\b&j\u0002\b'j\u0002\b(j\u0002\b)j\u0002\b*j\u0002\b+j\u0002\b,j\u0002\b-j\u0002\b.j\u0002\b/j\u0002\b0j\u0002\b1j\u0002\b2j\u0002\b3j\u0002\b4j\u0002\b5j\u0002\b6j\u0002\b7j\u0002\b8j\u0002\b9j\u0002\b:j\u0002\b;j\u0002\b<j\u0002\b=j\u0002\b>j\u0002\b?j\u0002\b@j\u0002\bAj\u0002\bBj\u0002\bCj\u0002\bDj\u0002\bEj\u0002\bFj\u0002\bGj\u0002\bHj\u0002\bIj\u0002\bJj\u0002\bKj\u0002\bLj\u0002\bMj\u0002\bNj\u0002\bOj\u0002\bPj\u0002\bQj\u0002\bRj\u0002\bSj\u0002\bTj\u0002\bUj\u0002\bVj\u0002\bWj\u0002\bXj\u0002\bYj\u0002\bZj\u0002\b[j\u0002\b\\j\u0002\b]j\u0002\b^j\u0002\b_j\u0002\b`j\u0002\baj\u0002\bbj\u0002\bcj\u0002\bdj\u0002\bej\u0002\bfj\u0002\bgj\u0002\bhj\u0002\bij\u0002\bjj\u0002\bkj\u0002\blj\u0002\bmj\u0002\bnj\u0002\boj\u0002\bpj\u0002\bqj\u0002\brj\u0002\bsj\u0002\btj\u0002\buj\u0002\bvj\u0002\bwj\u0002\bxj\u0002\byj\u0002\bzj\u0002\b{j\u0002\b|j\u0002\b}j\u0002\b~j\u0002\b\u007fj\u0003\b\u0080\u0001j\u0003\b\u0081\u0001j\u0003\b\u0082\u0001j\u0003\b\u0083\u0001j\u0003\b\u0084\u0001j\u0003\b\u0085\u0001j\u0003\b\u0086\u0001j\u0003\b\u0087\u0001j\u0003\b\u0088\u0001j\u0003\b\u0089\u0001j\u0003\b\u008a\u0001j\u0003\b\u008b\u0001j\u0003\b\u008c\u0001j\u0003\b\u008d\u0001j\u0003\b\u008e\u0001j\u0003\b\u008f\u0001j\u0003\b\u0090\u0001j\u0003\b\u0091\u0001j\u0003\b\u0092\u0001j\u0003\b\u0093\u0001j\u0003\b\u0094\u0001j\u0003\b\u0095\u0001j\u0003\b\u0096\u0001j\u0003\b\u0097\u0001j\u0003\b\u0098\u0001j\u0003\b\u0099\u0001j\u0003\b\u009a\u0001j\u0003\b\u009b\u0001j\u0003\b\u009c\u0001j\u0003\b\u009d\u0001j\u0003\b\u009e\u0001j\u0003\b\u009f\u0001j\u0003\b \u0001j\u0003\b¡\u0001j\u0003\b¢\u0001j\u0003\b£\u0001j\u0003\b¤\u0001j\u0003\b¥\u0001j\u0003\b¦\u0001j\u0003\b§\u0001j\u0003\b¨\u0001j\u0003\b©\u0001j\u0003\bª\u0001j\u0003\b«\u0001j\u0003\b¬\u0001j\u0003\b\u00ad\u0001j\u0003\b®\u0001j\u0003\b¯\u0001j\u0003\b°\u0001j\u0003\b±\u0001j\u0003\b²\u0001j\u0003\b³\u0001j\u0003\b´\u0001j\u0003\bµ\u0001j\u0003\b¶\u0001j\u0003\b·\u0001j\u0003\b¸\u0001j\u0003\b¹\u0001j\u0003\bº\u0001j\u0003\b»\u0001j\u0003\b¼\u0001j\u0003\b½\u0001j\u0003\b¾\u0001j\u0003\b¿\u0001j\u0003\bÀ\u0001j\u0003\bÁ\u0001j\u0003\bÂ\u0001j\u0003\bÃ\u0001j\u0003\bÄ\u0001j\u0003\bÅ\u0001j\u0003\bÆ\u0001j\u0003\bÇ\u0001j\u0003\bÈ\u0001j\u0003\bÉ\u0001j\u0003\bÊ\u0001j\u0003\bË\u0001j\u0003\bÌ\u0001j\u0003\bÍ\u0001j\u0003\bÎ\u0001j\u0003\bÏ\u0001j\u0003\bÐ\u0001j\u0003\bÑ\u0001j\u0003\bÒ\u0001j\u0003\bÓ\u0001j\u0003\bÔ\u0001j\u0003\bÕ\u0001j\u0003\bÖ\u0001j\u0003\b×\u0001j\u0003\bØ\u0001j\u0003\bÙ\u0001j\u0003\bÚ\u0001j\u0003\bÛ\u0001j\u0003\bÜ\u0001j\u0003\bÝ\u0001j\u0003\bÞ\u0001j\u0003\bß\u0001j\u0003\bà\u0001j\u0003\bá\u0001¨\u0006â\u0001"}, d2 = {"Lcom/sporty/android/core/model/config/bo/enums/BOConfigParam;", "Lcom/sporty/android/core/model/config/bo/IBOConfigParam;", "", "appId", "Lcom/sporty/android/core/model/config/bo/enums/BOConfigAppId;", "namespace", "Lcom/sporty/android/core/model/config/bo/enums/BOConfigNamespace;", "configKey", "", "deserializeOption", "Lcom/sporty/android/core/model/config/bo/BOConfigDeserializeOption;", "<init>", "(Ljava/lang/String;ILcom/sporty/android/core/model/config/bo/enums/BOConfigAppId;Lcom/sporty/android/core/model/config/bo/enums/BOConfigNamespace;Ljava/lang/String;Lcom/sporty/android/core/model/config/bo/BOConfigDeserializeOption;)V", "getAppId", "()Lcom/sporty/android/core/model/config/bo/enums/BOConfigAppId;", "getNamespace", "()Lcom/sporty/android/core/model/config/bo/enums/BOConfigNamespace;", "getConfigKey", "()Ljava/lang/String;", "getDeserializeOption", "()Lcom/sporty/android/core/model/config/bo/BOConfigDeserializeOption;", "PaychAlertContent", "WithdrawTabOrder", "DepositTabOrder", "DepositBankTransferSubTabOrder", "ShowNewWithdrawLabel", "ShowNewDepositLabel", "RiskWithdrawLimitByPaymentMethod", "RiskWithdrawMin", "RiskWithdrawMax", "RiskDepositMin", "RiskDepositMax", "TransferC2cMinAmount", "TransferC2cMaxAmount", "WithdrawFeeRange", "FeeWithdrawOnceAmount", "FeeWithdrawOnceType", "FeeWithdrawOnceFree", "PartnerWithdrawFee", "FeeWithdrawCancelAmount", "GtWithServAllowedNoOfAssets", "MastercardDepAllowedNoOfAssets", "PaybillProvider", "WhtSettings", "UserAdditionalPhoneConfigParam", "OthersOrderDeposit", "ManualClaimUserLockTime", "SportybankRetryManualInterval", "SportybankRetryAutoInterval", "AllowDeleteNonExpiredCard", "DepositAmountQuickAddingValues", "PlaOperator", "EWalletTooltipEnabledConfig", "PixMaxNumberOfAccounts", "PixBtgDepositPollingInterval", "PixBtgDepositPollingMax", "PixBtgDepositMinRemainingSeconds", "TransactionEnableInitialBalance", "PartialBankWithdraw", "PartialMobileMoneyWithdraw", "PartialPartnerWithdraw", "PartialTransferToFriendWithdraw", "DepositDedicatedAccountsNumberLimit", "PartialMobileMoneyDeposit", "PartialPaybillDeposit", "PartialCardDeposit", "PartialOthersDeposit", "PartialBankTransferDeposit", "PartialSportyBankAndroid", "PartialOtherBanksDeposit", "PartialOpayDeposit", "PartialPalmpayDeposit", "PartialTennDeposit", "PartialKudaDeposit", "WithdrawAllowDecimal", "DepositAllowDecimal", "MultiMakerToggle", "MultiMakerTotalOddsToggle", "MultiMakerTotalOddsSetting", "MultiMakerMaxReqNum", "WinningTaxType", "WinningTaxRate", "ExciseTaxRateToShow", "ExciseTaxRateToCharge", "ExciseTaxRateStakeBonus", "VirtualWinningTaxType", "VirtualWinningTaxRate", "VirtualExciseTaxRateToShow", "VirtualExciseTaxRateToCharge", "VirtualExciseTaxRateStakeBonus", "NewVirtualLobbyMainEntranceAndroid", "NewVirtualLobbyBannerAndroid", "NewVirtualLobbyBngFloatButtonEnableAndroid", "BetBuilderEnabled", "BetBuilderMaxSelectionsLimit", "BetBuilderMinNumberOfSelections", "BetBuilderMaxOdds", "BetBuilderSupportedBetTypes", "BetBuilderExclusionFilter", "FeaturedBetBuilderEnabled", "FeaturedBetBuilderEvents", "NewBadgeEventDetails", "OddsFilterRangePreFixed", "CodehubFilterToggle", "CodeHubWorldCupEnabledAndroid", "QuickMarketMenuToggle", "GiftGroupDisplayOrder", "LoyaltyProgramQualifyPopup", "RegisterVcodeIgnoreConfig", "SimCutStatus", "IsEnableCodeHubLoadCode", "IsEnableCreateSocialPage", "EnableCodeHubCustomCodes", "CodeHubCustomCodePattern", "CodeHubCustomCodeSeparator", "CodeHubCustomCodeCountLimit", "EnableCreatorCredits", "SocialCreatorCreditsMinimumSelections", "AndroidManuallyUpdateUrlGp", "SimpleKycRegisterStatusConfig", "DynamicReplacementMarkets", "GoogleAnalyticsEventFireByBackend", "IsFeaturedCodeEnabled", "KeDepositRangeFreeThreshold", "MaxCombinationsRejectEnabled", "MaxCombinationsRejectCount", "AnyWinStatus", "AnyWinMinOdds", "AnyWinMinSelectionOdds", "AnyWinMinSelectionNumber", "AnyWinMaxSelectionNumber", "FlexiBetWeightedRTPEnabled", "FlexiBetAverageWeightedRTPMultiplier", "FlexiBetOddsKey", "FlexiBetOddsKeyTable", "FlexiBetStatus", "FlexiBetMinOdds", "FlexiBetWeightedRTPSupportedMinVersion", "FlexiBetAverageWeightedRTPMinimum", "OlderBetHistoryMonth", "BetHistoryRefreshDebounceMs", "GiftReminderEnabledAddToStake", "GiftReminderEnabledUserIdSuffix", "MissionProgressEnabledAddToBetslip", "AutoBetEnabled", "AutoBetActive", "AutoBetMatchMaxDays", "AutoBetMaxActiveSettingPerUser", "MissionProgressEnabledUserIdSuffix", "AutoBetMaxOdds", "AutoBetMinOdds", "MarketsTabsOrder", "HangWatchdogConfig", "CashoutSuspendDeactivateEnabled", "CashoutSuspendDeactivateAllow", "CashoutSuspendDeactivatePhase", "CashoutSuspendDeactivateAdditionalMarketSpecifier", "CashoutOutcomeActiveEnabled", "CashoutMarketActiveEnabled", "CashoutNewFeedEnabled", "CashoutEventAbandonedEnabled", "CashoutFallbackEnabled", "CashoutFallbackMinCapEnabled", "CashoutFlexibleBetAllow", "CashoutAnyWinAllow", "CashoutSupportGiftEnabled", "CashoutHighProbabilityAllow", "CashoutQuickReinvestEnabled", "CashoutHighProbabilityAllowBound", "CashoutFlexibleBetRealTimeAmountDisplay", "CashoutDetailThrottleInterval", "CashoutProviderMarketRules", "BuildAndGoFeaturedTabConfig", "MomoPhonePrefixData", "EarlyPayoutConfig", "DefaultSportyInsureUpsType", "StaleOddsAutoRefresh", "DisplayNewForDobBenefitCard", "InstantWinPromotionConfig", "BoreDrawSelectionEligibility", "OddsBoostCashoutable", "SimpleStandardBetSlipEnabled", "IsPostBetUpsellEnabled", "RecommendedPostBetUpsellGame", "OddsBoostFlashBoostEnabled", "OddsBoostPrematchBoostEnabled", "AndroidMiniGamesOpenBetsEnabled", "RemixBetEnabled", "SportySocialCodeChatEnabled", "SportySocialCodeChatThreshold", "SportySocialNewShareFlowEnabled", "SportySocialForYouEnabledAndroid", "SportySocialEditUsernameEnabled", "RequireFTDForLiveStreaming", "IncludeMAIDInUserMetadata", "SportyJokerEnabled", "GamesForYouEnabled", "DedicatedTeamPageEnabled", "FifaWorldCupTournamentIds", "MegaBetBuilder", "WorldCupTournamentPageConfig", "MultipleBetCashoutSimRebet", "SportyPicks", "WorldCupTournamentPageTeams", "WorldCupTournamentPageGroups", "VirtualInHouseGamePromotionBanner", "CashoutUnavailableClickMetricsDebounceMs", "OpenBetRefreshDebounceTime", "CashoutMetricsSamplingUserIdTail", "MissionCompletedGamesCarouselBottomSheetEnabled", "LuckyNumberModuleEnabled", "WinningPopupAudioResource", "StakeDefaultAmount", "StakeMinAmount", "StakeMaxAmount", "StakeMinCashoutAmount", "StakeMaxCashoutAmount", "StakeMaxPayoutAmount", "StakeQuickAmount1", "StakeQuickAmount2", "StakeQuickAmount3", "StakeMaxSelectionLimit", "StakeBettorLimitLossDefault", "StakeBettorLimitTimeDefault", "SetPasswordV2EnabledCountries", "NewSearchScreen", "model"}, k = 1, mv = {2, 4, 0}, xi = 48)
public final class BOConfigParam implements IBOConfigParam {
    private static final /* synthetic */ tag $ENTRIES;
    private static final /* synthetic */ BOConfigParam[] $VALUES;
    public static final BOConfigParam AllowDeleteNonExpiredCard;
    public static final BOConfigParam AndroidManuallyUpdateUrlGp;
    public static final BOConfigParam AndroidMiniGamesOpenBetsEnabled;
    public static final BOConfigParam AnyWinMaxSelectionNumber;
    public static final BOConfigParam AnyWinMinOdds;
    public static final BOConfigParam AnyWinMinSelectionNumber;
    public static final BOConfigParam AnyWinMinSelectionOdds;
    public static final BOConfigParam AnyWinStatus;
    public static final BOConfigParam AutoBetActive;
    public static final BOConfigParam AutoBetEnabled;
    public static final BOConfigParam AutoBetMatchMaxDays;
    public static final BOConfigParam AutoBetMaxActiveSettingPerUser;
    public static final BOConfigParam AutoBetMaxOdds;
    public static final BOConfigParam AutoBetMinOdds;
    public static final BOConfigParam BetBuilderEnabled;
    public static final BOConfigParam BetBuilderExclusionFilter;
    public static final BOConfigParam BetBuilderMaxOdds;
    public static final BOConfigParam BetBuilderMaxSelectionsLimit;
    public static final BOConfigParam BetBuilderMinNumberOfSelections;
    public static final BOConfigParam BetBuilderSupportedBetTypes;
    public static final BOConfigParam BetHistoryRefreshDebounceMs;
    public static final BOConfigParam BoreDrawSelectionEligibility;
    public static final BOConfigParam BuildAndGoFeaturedTabConfig;
    public static final BOConfigParam CashoutAnyWinAllow;
    public static final BOConfigParam CashoutDetailThrottleInterval;
    public static final BOConfigParam CashoutEventAbandonedEnabled;
    public static final BOConfigParam CashoutFallbackEnabled;
    public static final BOConfigParam CashoutFallbackMinCapEnabled;
    public static final BOConfigParam CashoutFlexibleBetAllow;
    public static final BOConfigParam CashoutFlexibleBetRealTimeAmountDisplay;
    public static final BOConfigParam CashoutHighProbabilityAllow;
    public static final BOConfigParam CashoutHighProbabilityAllowBound;
    public static final BOConfigParam CashoutMarketActiveEnabled;
    public static final BOConfigParam CashoutMetricsSamplingUserIdTail;
    public static final BOConfigParam CashoutNewFeedEnabled;
    public static final BOConfigParam CashoutOutcomeActiveEnabled;
    public static final BOConfigParam CashoutProviderMarketRules;
    public static final BOConfigParam CashoutQuickReinvestEnabled;
    public static final BOConfigParam CashoutSupportGiftEnabled;
    public static final BOConfigParam CashoutSuspendDeactivateAdditionalMarketSpecifier;
    public static final BOConfigParam CashoutSuspendDeactivateAllow;
    public static final BOConfigParam CashoutSuspendDeactivateEnabled;
    public static final BOConfigParam CashoutSuspendDeactivatePhase;
    public static final BOConfigParam CashoutUnavailableClickMetricsDebounceMs;
    public static final BOConfigParam CodeHubCustomCodeCountLimit;
    public static final BOConfigParam CodeHubCustomCodePattern;
    public static final BOConfigParam CodeHubCustomCodeSeparator;
    public static final BOConfigParam CodeHubWorldCupEnabledAndroid;
    public static final BOConfigParam CodehubFilterToggle;
    public static final BOConfigParam DedicatedTeamPageEnabled;
    public static final BOConfigParam DefaultSportyInsureUpsType;
    public static final BOConfigParam DepositAllowDecimal;
    public static final BOConfigParam DepositAmountQuickAddingValues;
    public static final BOConfigParam DepositBankTransferSubTabOrder;
    public static final BOConfigParam DepositDedicatedAccountsNumberLimit;
    public static final BOConfigParam DepositTabOrder;
    public static final BOConfigParam DisplayNewForDobBenefitCard;
    public static final BOConfigParam DynamicReplacementMarkets;
    public static final BOConfigParam EWalletTooltipEnabledConfig;
    public static final BOConfigParam EarlyPayoutConfig;
    public static final BOConfigParam EnableCodeHubCustomCodes;
    public static final BOConfigParam EnableCreatorCredits;
    public static final BOConfigParam ExciseTaxRateStakeBonus;
    public static final BOConfigParam ExciseTaxRateToCharge;
    public static final BOConfigParam ExciseTaxRateToShow;
    public static final BOConfigParam FeaturedBetBuilderEnabled;
    public static final BOConfigParam FeaturedBetBuilderEvents;
    public static final BOConfigParam FeeWithdrawCancelAmount;
    public static final BOConfigParam FeeWithdrawOnceAmount;
    public static final BOConfigParam FeeWithdrawOnceFree;
    public static final BOConfigParam FeeWithdrawOnceType;
    public static final BOConfigParam FifaWorldCupTournamentIds;
    public static final BOConfigParam FlexiBetAverageWeightedRTPMinimum;
    public static final BOConfigParam FlexiBetAverageWeightedRTPMultiplier;
    public static final BOConfigParam FlexiBetMinOdds;
    public static final BOConfigParam FlexiBetOddsKey;
    public static final BOConfigParam FlexiBetOddsKeyTable;
    public static final BOConfigParam FlexiBetStatus;
    public static final BOConfigParam FlexiBetWeightedRTPEnabled;
    public static final BOConfigParam FlexiBetWeightedRTPSupportedMinVersion;
    public static final BOConfigParam GamesForYouEnabled;
    public static final BOConfigParam GiftGroupDisplayOrder;
    public static final BOConfigParam GiftReminderEnabledAddToStake;
    public static final BOConfigParam GiftReminderEnabledUserIdSuffix;
    public static final BOConfigParam GoogleAnalyticsEventFireByBackend;
    public static final BOConfigParam GtWithServAllowedNoOfAssets;
    public static final BOConfigParam HangWatchdogConfig;
    public static final BOConfigParam IncludeMAIDInUserMetadata;
    public static final BOConfigParam InstantWinPromotionConfig;
    public static final BOConfigParam IsEnableCodeHubLoadCode;
    public static final BOConfigParam IsEnableCreateSocialPage;
    public static final BOConfigParam IsFeaturedCodeEnabled;
    public static final BOConfigParam IsPostBetUpsellEnabled;
    public static final BOConfigParam KeDepositRangeFreeThreshold;
    public static final BOConfigParam LoyaltyProgramQualifyPopup;
    public static final BOConfigParam LuckyNumberModuleEnabled;
    public static final BOConfigParam ManualClaimUserLockTime;
    public static final BOConfigParam MarketsTabsOrder;
    public static final BOConfigParam MastercardDepAllowedNoOfAssets;
    public static final BOConfigParam MaxCombinationsRejectCount;
    public static final BOConfigParam MaxCombinationsRejectEnabled;
    public static final BOConfigParam MegaBetBuilder;
    public static final BOConfigParam MissionCompletedGamesCarouselBottomSheetEnabled;
    public static final BOConfigParam MissionProgressEnabledAddToBetslip;
    public static final BOConfigParam MissionProgressEnabledUserIdSuffix;
    public static final BOConfigParam MomoPhonePrefixData;
    public static final BOConfigParam MultiMakerMaxReqNum;
    public static final BOConfigParam MultiMakerToggle;
    public static final BOConfigParam MultiMakerTotalOddsSetting;
    public static final BOConfigParam MultiMakerTotalOddsToggle;
    public static final BOConfigParam MultipleBetCashoutSimRebet;
    public static final BOConfigParam NewBadgeEventDetails;
    public static final BOConfigParam NewSearchScreen;
    public static final BOConfigParam NewVirtualLobbyBannerAndroid;
    public static final BOConfigParam NewVirtualLobbyBngFloatButtonEnableAndroid;
    public static final BOConfigParam NewVirtualLobbyMainEntranceAndroid;
    public static final BOConfigParam OddsBoostCashoutable;
    public static final BOConfigParam OddsBoostFlashBoostEnabled;
    public static final BOConfigParam OddsBoostPrematchBoostEnabled;
    public static final BOConfigParam OddsFilterRangePreFixed;
    public static final BOConfigParam OlderBetHistoryMonth;
    public static final BOConfigParam OpenBetRefreshDebounceTime;
    public static final BOConfigParam OthersOrderDeposit;
    public static final BOConfigParam PartialBankTransferDeposit;
    public static final BOConfigParam PartialBankWithdraw;
    public static final BOConfigParam PartialCardDeposit;
    public static final BOConfigParam PartialKudaDeposit;
    public static final BOConfigParam PartialMobileMoneyDeposit;
    public static final BOConfigParam PartialMobileMoneyWithdraw;
    public static final BOConfigParam PartialOpayDeposit;
    public static final BOConfigParam PartialOtherBanksDeposit;
    public static final BOConfigParam PartialOthersDeposit;
    public static final BOConfigParam PartialPalmpayDeposit;
    public static final BOConfigParam PartialPartnerWithdraw;
    public static final BOConfigParam PartialPaybillDeposit;
    public static final BOConfigParam PartialSportyBankAndroid;
    public static final BOConfigParam PartialTennDeposit;
    public static final BOConfigParam PartialTransferToFriendWithdraw;
    public static final BOConfigParam PartnerWithdrawFee;
    public static final BOConfigParam PaybillProvider;
    public static final BOConfigParam PaychAlertContent;
    public static final BOConfigParam PixBtgDepositMinRemainingSeconds;
    public static final BOConfigParam PixBtgDepositPollingInterval;
    public static final BOConfigParam PixBtgDepositPollingMax;
    public static final BOConfigParam PixMaxNumberOfAccounts;
    public static final BOConfigParam PlaOperator;
    public static final BOConfigParam QuickMarketMenuToggle;
    public static final BOConfigParam RecommendedPostBetUpsellGame;
    public static final BOConfigParam RegisterVcodeIgnoreConfig;
    public static final BOConfigParam RemixBetEnabled;
    public static final BOConfigParam RequireFTDForLiveStreaming;
    public static final BOConfigParam RiskDepositMax;
    public static final BOConfigParam RiskDepositMin;
    public static final BOConfigParam RiskWithdrawLimitByPaymentMethod;
    public static final BOConfigParam RiskWithdrawMax;
    public static final BOConfigParam RiskWithdrawMin;
    public static final BOConfigParam SetPasswordV2EnabledCountries;
    public static final BOConfigParam ShowNewDepositLabel;
    public static final BOConfigParam ShowNewWithdrawLabel;
    public static final BOConfigParam SimCutStatus;
    public static final BOConfigParam SimpleKycRegisterStatusConfig;
    public static final BOConfigParam SimpleStandardBetSlipEnabled;
    public static final BOConfigParam SocialCreatorCreditsMinimumSelections;
    public static final BOConfigParam SportyJokerEnabled;
    public static final BOConfigParam SportyPicks;
    public static final BOConfigParam SportySocialCodeChatEnabled;
    public static final BOConfigParam SportySocialCodeChatThreshold;
    public static final BOConfigParam SportySocialEditUsernameEnabled;
    public static final BOConfigParam SportySocialForYouEnabledAndroid;
    public static final BOConfigParam SportySocialNewShareFlowEnabled;
    public static final BOConfigParam SportybankRetryAutoInterval;
    public static final BOConfigParam SportybankRetryManualInterval;
    public static final BOConfigParam StakeBettorLimitLossDefault;
    public static final BOConfigParam StakeBettorLimitTimeDefault;
    public static final BOConfigParam StakeDefaultAmount;
    public static final BOConfigParam StakeMaxAmount;
    public static final BOConfigParam StakeMaxCashoutAmount;
    public static final BOConfigParam StakeMaxPayoutAmount;
    public static final BOConfigParam StakeMaxSelectionLimit;
    public static final BOConfigParam StakeMinAmount;
    public static final BOConfigParam StakeMinCashoutAmount;
    public static final BOConfigParam StakeQuickAmount1;
    public static final BOConfigParam StakeQuickAmount2;
    public static final BOConfigParam StakeQuickAmount3;
    public static final BOConfigParam StaleOddsAutoRefresh;
    public static final BOConfigParam TransactionEnableInitialBalance;
    public static final BOConfigParam TransferC2cMaxAmount;
    public static final BOConfigParam TransferC2cMinAmount;
    public static final BOConfigParam UserAdditionalPhoneConfigParam;
    public static final BOConfigParam VirtualExciseTaxRateStakeBonus;
    public static final BOConfigParam VirtualExciseTaxRateToCharge;
    public static final BOConfigParam VirtualExciseTaxRateToShow;
    public static final BOConfigParam VirtualInHouseGamePromotionBanner;
    public static final BOConfigParam VirtualWinningTaxRate;
    public static final BOConfigParam VirtualWinningTaxType;
    public static final BOConfigParam WhtSettings;
    public static final BOConfigParam WinningPopupAudioResource;
    public static final BOConfigParam WinningTaxRate;
    public static final BOConfigParam WinningTaxType;
    public static final BOConfigParam WithdrawAllowDecimal;
    public static final BOConfigParam WithdrawFeeRange;
    public static final BOConfigParam WithdrawTabOrder;
    public static final BOConfigParam WorldCupTournamentPageConfig;
    public static final BOConfigParam WorldCupTournamentPageGroups;
    public static final BOConfigParam WorldCupTournamentPageTeams;
    private final BOConfigAppId appId;
    private final String configKey;
    private final BOConfigDeserializeOption deserializeOption;
    private final BOConfigNamespace namespace;

    private static final /* synthetic */ BOConfigParam[] $values() {
        return new BOConfigParam[]{PaychAlertContent, WithdrawTabOrder, DepositTabOrder, DepositBankTransferSubTabOrder, ShowNewWithdrawLabel, ShowNewDepositLabel, RiskWithdrawLimitByPaymentMethod, RiskWithdrawMin, RiskWithdrawMax, RiskDepositMin, RiskDepositMax, TransferC2cMinAmount, TransferC2cMaxAmount, WithdrawFeeRange, FeeWithdrawOnceAmount, FeeWithdrawOnceType, FeeWithdrawOnceFree, PartnerWithdrawFee, FeeWithdrawCancelAmount, GtWithServAllowedNoOfAssets, MastercardDepAllowedNoOfAssets, PaybillProvider, WhtSettings, UserAdditionalPhoneConfigParam, OthersOrderDeposit, ManualClaimUserLockTime, SportybankRetryManualInterval, SportybankRetryAutoInterval, AllowDeleteNonExpiredCard, DepositAmountQuickAddingValues, PlaOperator, EWalletTooltipEnabledConfig, PixMaxNumberOfAccounts, PixBtgDepositPollingInterval, PixBtgDepositPollingMax, PixBtgDepositMinRemainingSeconds, TransactionEnableInitialBalance, PartialBankWithdraw, PartialMobileMoneyWithdraw, PartialPartnerWithdraw, PartialTransferToFriendWithdraw, DepositDedicatedAccountsNumberLimit, PartialMobileMoneyDeposit, PartialPaybillDeposit, PartialCardDeposit, PartialOthersDeposit, PartialBankTransferDeposit, PartialSportyBankAndroid, PartialOtherBanksDeposit, PartialOpayDeposit, PartialPalmpayDeposit, PartialTennDeposit, PartialKudaDeposit, WithdrawAllowDecimal, DepositAllowDecimal, MultiMakerToggle, MultiMakerTotalOddsToggle, MultiMakerTotalOddsSetting, MultiMakerMaxReqNum, WinningTaxType, WinningTaxRate, ExciseTaxRateToShow, ExciseTaxRateToCharge, ExciseTaxRateStakeBonus, VirtualWinningTaxType, VirtualWinningTaxRate, VirtualExciseTaxRateToShow, VirtualExciseTaxRateToCharge, VirtualExciseTaxRateStakeBonus, NewVirtualLobbyMainEntranceAndroid, NewVirtualLobbyBannerAndroid, NewVirtualLobbyBngFloatButtonEnableAndroid, BetBuilderEnabled, BetBuilderMaxSelectionsLimit, BetBuilderMinNumberOfSelections, BetBuilderMaxOdds, BetBuilderSupportedBetTypes, BetBuilderExclusionFilter, FeaturedBetBuilderEnabled, FeaturedBetBuilderEvents, NewBadgeEventDetails, OddsFilterRangePreFixed, CodehubFilterToggle, CodeHubWorldCupEnabledAndroid, QuickMarketMenuToggle, GiftGroupDisplayOrder, LoyaltyProgramQualifyPopup, RegisterVcodeIgnoreConfig, SimCutStatus, IsEnableCodeHubLoadCode, IsEnableCreateSocialPage, EnableCodeHubCustomCodes, CodeHubCustomCodePattern, CodeHubCustomCodeSeparator, CodeHubCustomCodeCountLimit, EnableCreatorCredits, SocialCreatorCreditsMinimumSelections, AndroidManuallyUpdateUrlGp, SimpleKycRegisterStatusConfig, DynamicReplacementMarkets, GoogleAnalyticsEventFireByBackend, IsFeaturedCodeEnabled, KeDepositRangeFreeThreshold, MaxCombinationsRejectEnabled, MaxCombinationsRejectCount, AnyWinStatus, AnyWinMinOdds, AnyWinMinSelectionOdds, AnyWinMinSelectionNumber, AnyWinMaxSelectionNumber, FlexiBetWeightedRTPEnabled, FlexiBetAverageWeightedRTPMultiplier, FlexiBetOddsKey, FlexiBetOddsKeyTable, FlexiBetStatus, FlexiBetMinOdds, FlexiBetWeightedRTPSupportedMinVersion, FlexiBetAverageWeightedRTPMinimum, OlderBetHistoryMonth, BetHistoryRefreshDebounceMs, GiftReminderEnabledAddToStake, GiftReminderEnabledUserIdSuffix, MissionProgressEnabledAddToBetslip, AutoBetEnabled, AutoBetActive, AutoBetMatchMaxDays, AutoBetMaxActiveSettingPerUser, MissionProgressEnabledUserIdSuffix, AutoBetMaxOdds, AutoBetMinOdds, MarketsTabsOrder, HangWatchdogConfig, CashoutSuspendDeactivateEnabled, CashoutSuspendDeactivateAllow, CashoutSuspendDeactivatePhase, CashoutSuspendDeactivateAdditionalMarketSpecifier, CashoutOutcomeActiveEnabled, CashoutMarketActiveEnabled, CashoutNewFeedEnabled, CashoutEventAbandonedEnabled, CashoutFallbackEnabled, CashoutFallbackMinCapEnabled, CashoutFlexibleBetAllow, CashoutAnyWinAllow, CashoutSupportGiftEnabled, CashoutHighProbabilityAllow, CashoutQuickReinvestEnabled, CashoutHighProbabilityAllowBound, CashoutFlexibleBetRealTimeAmountDisplay, CashoutDetailThrottleInterval, CashoutProviderMarketRules, BuildAndGoFeaturedTabConfig, MomoPhonePrefixData, EarlyPayoutConfig, DefaultSportyInsureUpsType, StaleOddsAutoRefresh, DisplayNewForDobBenefitCard, InstantWinPromotionConfig, BoreDrawSelectionEligibility, OddsBoostCashoutable, SimpleStandardBetSlipEnabled, IsPostBetUpsellEnabled, RecommendedPostBetUpsellGame, OddsBoostFlashBoostEnabled, OddsBoostPrematchBoostEnabled, AndroidMiniGamesOpenBetsEnabled, RemixBetEnabled, SportySocialCodeChatEnabled, SportySocialCodeChatThreshold, SportySocialNewShareFlowEnabled, SportySocialForYouEnabledAndroid, SportySocialEditUsernameEnabled, RequireFTDForLiveStreaming, IncludeMAIDInUserMetadata, SportyJokerEnabled, GamesForYouEnabled, DedicatedTeamPageEnabled, FifaWorldCupTournamentIds, MegaBetBuilder, WorldCupTournamentPageConfig, MultipleBetCashoutSimRebet, SportyPicks, WorldCupTournamentPageTeams, WorldCupTournamentPageGroups, VirtualInHouseGamePromotionBanner, CashoutUnavailableClickMetricsDebounceMs, OpenBetRefreshDebounceTime, CashoutMetricsSamplingUserIdTail, MissionCompletedGamesCarouselBottomSheetEnabled, LuckyNumberModuleEnabled, WinningPopupAudioResource, StakeDefaultAmount, StakeMinAmount, StakeMaxAmount, StakeMinCashoutAmount, StakeMaxCashoutAmount, StakeMaxPayoutAmount, StakeQuickAmount1, StakeQuickAmount2, StakeQuickAmount3, StakeMaxSelectionLimit, StakeBettorLimitLossDefault, StakeBettorLimitTimeDefault, SetPasswordV2EnabledCountries, NewSearchScreen};
    }

    public /* synthetic */ BOConfigParam(String str, int i, BOConfigAppId bOConfigAppId, BOConfigNamespace bOConfigNamespace, String str2, BOConfigDeserializeOption bOConfigDeserializeOption, int i2, DefaultConstructorMarker defaultConstructorMarker) {
        this(str, i, bOConfigAppId, bOConfigNamespace, str2, (i2 & 8) != 0 ? BOConfigDeserializeOption.Primitive.INSTANCE : bOConfigDeserializeOption);
    }

    public static tag<BOConfigParam> getEntries() {
        return $ENTRIES;
    }

    public static BOConfigParam valueOf(String str) {
        return (BOConfigParam) Enum.valueOf(BOConfigParam.class, str);
    }

    public static BOConfigParam[] values() {
        return (BOConfigParam[]) $VALUES.clone();
    }

    @Override // com.sporty.android.core.model.config.bo.BOConfigId
    public BOConfigAppId getAppId() {
        return this.appId;
    }

    @Override // com.sporty.android.core.model.config.bo.BOConfigId
    public String getConfigKey() {
        return this.configKey;
    }

    @Override // com.sporty.android.core.model.config.bo.BOConfigDeserializable
    public BOConfigDeserializeOption getDeserializeOption() {
        return this.deserializeOption;
    }

    @Override // com.sporty.android.core.model.config.bo.BOConfigId
    public BOConfigNamespace getNamespace() {
        return this.namespace;
    }

    static {
        BOConfigAppId bOConfigAppId = BOConfigAppId.POCKET;
        BOConfigNamespace bOConfigNamespace = BOConfigNamespace.APPLICATION;
        PaychAlertContent = new BOConfigParam("PaychAlertContent", 0, bOConfigAppId, bOConfigNamespace, "paych.alert.content", new BOConfigDeserializeOption.WithKClass(jq40.a(PayHintData.PayHintEntity.class)));
        BOConfigAppId bOConfigAppId2 = BOConfigAppId.COMMON;
        BOConfigNamespace bOConfigNamespace2 = BOConfigNamespace.CONFIG;
        WithdrawTabOrder = new BOConfigParam("WithdrawTabOrder", 1, bOConfigAppId2, bOConfigNamespace2, "withdraw_tab_order", null, 8, null);
        int i = 8;
        DefaultConstructorMarker defaultConstructorMarker = null;
        BOConfigDeserializeOption bOConfigDeserializeOption = null;
        DepositTabOrder = new BOConfigParam("DepositTabOrder", 2, bOConfigAppId2, bOConfigNamespace2, "deposit_tab_order", bOConfigDeserializeOption, i, defaultConstructorMarker);
        DepositBankTransferSubTabOrder = new BOConfigParam("DepositBankTransferSubTabOrder", 3, bOConfigAppId2, bOConfigNamespace2, "deposit_bank_transfer_sub_tab_order", bOConfigDeserializeOption, i, defaultConstructorMarker);
        ShowNewWithdrawLabel = new BOConfigParam("ShowNewWithdrawLabel", 4, bOConfigAppId2, bOConfigNamespace2, "show_new_withdraw_label", bOConfigDeserializeOption, i, defaultConstructorMarker);
        ShowNewDepositLabel = new BOConfigParam("ShowNewDepositLabel", 5, bOConfigAppId2, bOConfigNamespace2, "show_new_deposit_label", bOConfigDeserializeOption, i, defaultConstructorMarker);
        RiskWithdrawLimitByPaymentMethod = new BOConfigParam("RiskWithdrawLimitByPaymentMethod", 6, bOConfigAppId, bOConfigNamespace, "risk.withdraw.limit.by.payment.method", new BOConfigDeserializeOption.WithKClass(jq40.a(TradingAmountMap.class)));
        int i2 = 8;
        BOConfigDeserializeOption bOConfigDeserializeOption2 = null;
        RiskWithdrawMin = new BOConfigParam("RiskWithdrawMin", 7, bOConfigAppId, bOConfigNamespace, "risk.withdraw.min", bOConfigDeserializeOption2, i2, null);
        RiskWithdrawMax = new BOConfigParam("RiskWithdrawMax", 8, bOConfigAppId, bOConfigNamespace, "risk.withdraw.max", bOConfigDeserializeOption2, i2, null);
        RiskDepositMin = new BOConfigParam("RiskDepositMin", 9, bOConfigAppId, bOConfigNamespace, "risk.deposit.min", bOConfigDeserializeOption2, i2, null);
        RiskDepositMax = new BOConfigParam("RiskDepositMax", 10, bOConfigAppId, bOConfigNamespace, "risk.deposit.max", bOConfigDeserializeOption2, i2, null);
        TransferC2cMinAmount = new BOConfigParam("TransferC2cMinAmount", 11, bOConfigAppId, bOConfigNamespace, "transfer.c2c.min.amount", bOConfigDeserializeOption2, i2, null);
        TransferC2cMaxAmount = new BOConfigParam("TransferC2cMaxAmount", 12, bOConfigAppId, bOConfigNamespace, "transfer.c2c.max.amount", bOConfigDeserializeOption2, i2, null);
        WithdrawFeeRange = new BOConfigParam("WithdrawFeeRange", 13, bOConfigAppId, bOConfigNamespace, "withdraw.fee.range", new BOConfigDeserializeOption.WithKClass(jq40.a(Range[].class)));
        BOConfigDeserializeOption bOConfigDeserializeOption3 = null;
        FeeWithdrawOnceAmount = new BOConfigParam("FeeWithdrawOnceAmount", 14, bOConfigAppId, bOConfigNamespace, "fee.withdrawOnce.amount", bOConfigDeserializeOption3, i2, null);
        FeeWithdrawOnceType = new BOConfigParam("FeeWithdrawOnceType", 15, bOConfigAppId, bOConfigNamespace, "fee.withdrawOnce.type", bOConfigDeserializeOption3, i2, null);
        FeeWithdrawOnceFree = new BOConfigParam("FeeWithdrawOnceFree", 16, bOConfigAppId, bOConfigNamespace, "fee.withdrawOnce.free", bOConfigDeserializeOption3, i2, null);
        PartnerWithdrawFee = new BOConfigParam("PartnerWithdrawFee", 17, bOConfigAppId2, bOConfigNamespace, "partner_withdraw_fee", new BOConfigDeserializeOption.WithKClass(jq40.a(PartnerWithdrawFeeConfigDto.class)));
        int i3 = 8;
        BOConfigDeserializeOption bOConfigDeserializeOption4 = null;
        FeeWithdrawCancelAmount = new BOConfigParam("FeeWithdrawCancelAmount", 18, bOConfigAppId, bOConfigNamespace, "fee.withdrawCancel.amount", bOConfigDeserializeOption4, i3, null);
        GtWithServAllowedNoOfAssets = new BOConfigParam("GtWithServAllowedNoOfAssets", 19, bOConfigAppId, bOConfigNamespace, "gt-with-serv.allowed-no-of-assets", bOConfigDeserializeOption4, i3, null);
        MastercardDepAllowedNoOfAssets = new BOConfigParam("MastercardDepAllowedNoOfAssets", 20, bOConfigAppId, bOConfigNamespace, "mastercard-dep.allowed-no-of-assets", bOConfigDeserializeOption4, i3, null);
        PaybillProvider = new BOConfigParam("PaybillProvider", 21, bOConfigAppId, bOConfigNamespace, "paybill.provider", bOConfigDeserializeOption4, i3, null);
        WhtSettings = new BOConfigParam("WhtSettings", 22, bOConfigAppId, bOConfigNamespace, "wht.settings", new BOConfigDeserializeOption.WithKClass(jq40.a(WhTaxData.class)));
        UserAdditionalPhoneConfigParam = new BOConfigParam("UserAdditionalPhoneConfigParam", 23, bOConfigAppId2, bOConfigNamespace, "user_additional_phone_config", new BOConfigDeserializeOption.WithKClass(jq40.a(UserAdditionalPhoneConfig.class)));
        int i4 = 8;
        BOConfigDeserializeOption bOConfigDeserializeOption5 = null;
        OthersOrderDeposit = new BOConfigParam("OthersOrderDeposit", 24, bOConfigAppId, bOConfigNamespace, "others_order_deposit", bOConfigDeserializeOption5, i4, null);
        ManualClaimUserLockTime = new BOConfigParam("ManualClaimUserLockTime", 25, bOConfigAppId, bOConfigNamespace, "manualClaim.user.lock.time", bOConfigDeserializeOption5, i4, null);
        SportybankRetryManualInterval = new BOConfigParam("SportybankRetryManualInterval", 26, bOConfigAppId2, bOConfigNamespace2, "sportybank.retry.manual.interval", bOConfigDeserializeOption, i, defaultConstructorMarker);
        SportybankRetryAutoInterval = new BOConfigParam("SportybankRetryAutoInterval", 27, bOConfigAppId2, bOConfigNamespace2, "sportybank.retry.auto.interval", new BOConfigDeserializeOption.WithKClass(jq40.a(Integer[].class)));
        AllowDeleteNonExpiredCard = new BOConfigParam("AllowDeleteNonExpiredCard", 28, bOConfigAppId, bOConfigNamespace, "allow.delete.non.expired.card", bOConfigDeserializeOption5, 8, null);
        DepositAmountQuickAddingValues = new BOConfigParam("DepositAmountQuickAddingValues", 29, bOConfigAppId, bOConfigNamespace, "deposit_amount_quick_adding_values", new BOConfigDeserializeOption.WithKClass(jq40.a(BigDecimal[].class)));
        PlaOperator = new BOConfigParam("PlaOperator", 30, bOConfigAppId2, bOConfigNamespace, "pla_operator", new BOConfigDeserializeOption.WithKClass(jq40.a(PLAOperatorBOConfig.class)));
        BOConfigDeserializeOption bOConfigDeserializeOption6 = null;
        EWalletTooltipEnabledConfig = new BOConfigParam("EWalletTooltipEnabledConfig", 31, bOConfigAppId2, bOConfigNamespace2, "ewallet_tooltip_enabled_config", bOConfigDeserializeOption6, i, defaultConstructorMarker);
        int i5 = 8;
        BOConfigDeserializeOption bOConfigDeserializeOption7 = null;
        PixMaxNumberOfAccounts = new BOConfigParam("PixMaxNumberOfAccounts", 32, bOConfigAppId, bOConfigNamespace, "pix.max_number_of_accounts", bOConfigDeserializeOption7, i5, null);
        PixBtgDepositPollingInterval = new BOConfigParam("PixBtgDepositPollingInterval", 33, bOConfigAppId, bOConfigNamespace, "pix.btg.deposit.polling.interval", bOConfigDeserializeOption7, i5, null);
        PixBtgDepositPollingMax = new BOConfigParam("PixBtgDepositPollingMax", 34, bOConfigAppId, bOConfigNamespace, "pix.btg.deposit.polling.max", bOConfigDeserializeOption7, i5, null);
        PixBtgDepositMinRemainingSeconds = new BOConfigParam("PixBtgDepositMinRemainingSeconds", 35, bOConfigAppId, bOConfigNamespace, "pix.btg.deposit.min.remaining.seconds", bOConfigDeserializeOption7, i5, null);
        TransactionEnableInitialBalance = new BOConfigParam("TransactionEnableInitialBalance", 36, bOConfigAppId, bOConfigNamespace, "transaction_enable_initial_balance", bOConfigDeserializeOption7, i5, null);
        PartialBankWithdraw = new BOConfigParam("PartialBankWithdraw", 37, bOConfigAppId2, bOConfigNamespace2, "partial_bank_withdraw", bOConfigDeserializeOption6, i, defaultConstructorMarker);
        PartialMobileMoneyWithdraw = new BOConfigParam("PartialMobileMoneyWithdraw", 38, bOConfigAppId2, bOConfigNamespace2, "partial_mobile_money_withdraw", bOConfigDeserializeOption6, i, defaultConstructorMarker);
        PartialPartnerWithdraw = new BOConfigParam("PartialPartnerWithdraw", 39, bOConfigAppId2, bOConfigNamespace2, "partial_partner_withdraw", bOConfigDeserializeOption6, i, defaultConstructorMarker);
        PartialTransferToFriendWithdraw = new BOConfigParam("PartialTransferToFriendWithdraw", 40, bOConfigAppId2, bOConfigNamespace2, "partial_transfer_to_friend_withdraw", bOConfigDeserializeOption6, i, defaultConstructorMarker);
        DepositDedicatedAccountsNumberLimit = new BOConfigParam("DepositDedicatedAccountsNumberLimit", 41, bOConfigAppId, bOConfigNamespace, "sporty.bank.account.limit", bOConfigDeserializeOption7, 8, null);
        PartialMobileMoneyDeposit = new BOConfigParam("PartialMobileMoneyDeposit", 42, bOConfigAppId2, bOConfigNamespace2, "partial_mobile_money_deposit", bOConfigDeserializeOption6, i, defaultConstructorMarker);
        PartialPaybillDeposit = new BOConfigParam("PartialPaybillDeposit", 43, bOConfigAppId2, bOConfigNamespace2, "partial_paybill_deposit", bOConfigDeserializeOption6, i, defaultConstructorMarker);
        PartialCardDeposit = new BOConfigParam("PartialCardDeposit", 44, bOConfigAppId2, bOConfigNamespace2, "partial_card_deposit", bOConfigDeserializeOption6, i, defaultConstructorMarker);
        PartialOthersDeposit = new BOConfigParam("PartialOthersDeposit", 45, bOConfigAppId2, bOConfigNamespace2, "partial_others_deposit", bOConfigDeserializeOption6, i, defaultConstructorMarker);
        PartialBankTransferDeposit = new BOConfigParam("PartialBankTransferDeposit", 46, bOConfigAppId2, bOConfigNamespace2, "partial_bank_transfer_deposit", bOConfigDeserializeOption6, i, defaultConstructorMarker);
        PartialSportyBankAndroid = new BOConfigParam("PartialSportyBankAndroid", 47, bOConfigAppId2, bOConfigNamespace2, "partial_sporty_bank_android", bOConfigDeserializeOption6, i, defaultConstructorMarker);
        PartialOtherBanksDeposit = new BOConfigParam("PartialOtherBanksDeposit", 48, bOConfigAppId2, bOConfigNamespace2, "partial_other_banks_deposit", bOConfigDeserializeOption6, i, defaultConstructorMarker);
        PartialOpayDeposit = new BOConfigParam("PartialOpayDeposit", 49, bOConfigAppId2, bOConfigNamespace2, "partial_opay_deposit", bOConfigDeserializeOption6, i, defaultConstructorMarker);
        PartialPalmpayDeposit = new BOConfigParam("PartialPalmpayDeposit", 50, bOConfigAppId2, bOConfigNamespace2, "partial_palmpay_deposit", bOConfigDeserializeOption6, i, defaultConstructorMarker);
        PartialTennDeposit = new BOConfigParam("PartialTennDeposit", 51, bOConfigAppId2, bOConfigNamespace2, "partial_tenn_deposit", bOConfigDeserializeOption6, i, defaultConstructorMarker);
        PartialKudaDeposit = new BOConfigParam("PartialKudaDeposit", 52, bOConfigAppId2, bOConfigNamespace2, "partial_kuda_deposit", bOConfigDeserializeOption6, i, defaultConstructorMarker);
        int i6 = 8;
        WithdrawAllowDecimal = new BOConfigParam("WithdrawAllowDecimal", 53, bOConfigAppId, bOConfigNamespace, "withdraw_allow_decimal", bOConfigDeserializeOption7, i6, null);
        DepositAllowDecimal = new BOConfigParam("DepositAllowDecimal", 54, bOConfigAppId, bOConfigNamespace, "deposit_allow_decimal", bOConfigDeserializeOption7, i6, null);
        BOConfigAppId bOConfigAppId3 = BOConfigAppId.FACTS_CENTER_QUERY;
        int i7 = 8;
        DefaultConstructorMarker defaultConstructorMarker2 = null;
        BOConfigDeserializeOption bOConfigDeserializeOption8 = null;
        MultiMakerToggle = new BOConfigParam("MultiMakerToggle", 55, bOConfigAppId3, bOConfigNamespace, "multi_maker_toggle", bOConfigDeserializeOption8, i7, defaultConstructorMarker2);
        MultiMakerTotalOddsToggle = new BOConfigParam("MultiMakerTotalOddsToggle", 56, bOConfigAppId3, bOConfigNamespace, "multi_maker_total_odds_toggle", bOConfigDeserializeOption8, i7, defaultConstructorMarker2);
        MultiMakerTotalOddsSetting = new BOConfigParam(llGRV.FOMFZ, 57, bOConfigAppId3, bOConfigNamespace, "multi_maker_total_odds_setting", new BOConfigDeserializeOption.WithKClass(jq40.a(MultiMakerTotalOddsBOSettings.class)));
        MultiMakerMaxReqNum = new BOConfigParam("MultiMakerMaxReqNum", 58, bOConfigAppId3, bOConfigNamespace, "multi_maker_max_req_num", null, i7, defaultConstructorMarker2);
        WinningTaxType = new BOConfigParam("WinningTaxType", 59, bOConfigAppId2, bOConfigNamespace2, "winning_tax_type", bOConfigDeserializeOption6, i, defaultConstructorMarker);
        WinningTaxRate = new BOConfigParam("WinningTaxRate", 60, bOConfigAppId2, bOConfigNamespace2, "winning_tax_rate", new BOConfigDeserializeOption.WithKClass(jq40.a(WinningTaxRateMap.class)));
        int i8 = 8;
        DefaultConstructorMarker defaultConstructorMarker3 = null;
        BOConfigDeserializeOption bOConfigDeserializeOption9 = null;
        ExciseTaxRateToShow = new BOConfigParam("ExciseTaxRateToShow", 61, bOConfigAppId2, bOConfigNamespace, "excise_tax_rate_to_show", bOConfigDeserializeOption9, i8, defaultConstructorMarker3);
        ExciseTaxRateToCharge = new BOConfigParam("ExciseTaxRateToCharge", 62, bOConfigAppId2, bOConfigNamespace, "excise_tax_rate_to_charge", bOConfigDeserializeOption9, i8, defaultConstructorMarker3);
        ExciseTaxRateStakeBonus = new BOConfigParam("ExciseTaxRateStakeBonus", 63, bOConfigAppId2, bOConfigNamespace, "excise_tax_rate_stake_bonus", bOConfigDeserializeOption9, i8, defaultConstructorMarker3);
        VirtualWinningTaxType = new BOConfigParam("VirtualWinningTaxType", 64, bOConfigAppId2, bOConfigNamespace2, "virtual_winning_tax_type", null, i, defaultConstructorMarker);
        VirtualWinningTaxRate = new BOConfigParam("VirtualWinningTaxRate", 65, bOConfigAppId2, bOConfigNamespace2, "virtual_winning_tax_rate", new BOConfigDeserializeOption.WithKClass(jq40.a(WinningTaxRateMap.class)));
        int i9 = 8;
        DefaultConstructorMarker defaultConstructorMarker4 = null;
        BOConfigDeserializeOption bOConfigDeserializeOption10 = null;
        VirtualExciseTaxRateToShow = new BOConfigParam("VirtualExciseTaxRateToShow", 66, bOConfigAppId2, bOConfigNamespace, "virtual_excise_tax_rate_to_show", bOConfigDeserializeOption10, i9, defaultConstructorMarker4);
        VirtualExciseTaxRateToCharge = new BOConfigParam("VirtualExciseTaxRateToCharge", 67, bOConfigAppId2, bOConfigNamespace, "virtual_excise_tax_rate_to_charge", bOConfigDeserializeOption10, i9, defaultConstructorMarker4);
        VirtualExciseTaxRateStakeBonus = new BOConfigParam("VirtualExciseTaxRateStakeBonus", 68, bOConfigAppId2, bOConfigNamespace, "virtual_excise_tax_rate_stake_bonus", bOConfigDeserializeOption10, i9, defaultConstructorMarker4);
        NewVirtualLobbyMainEntranceAndroid = new BOConfigParam("NewVirtualLobbyMainEntranceAndroid", 69, bOConfigAppId2, bOConfigNamespace2, "new_virtual_lobby_main_entrance_android", new BOConfigDeserializeOption.WithKClass(jq40.a(MainEntranceItem[].class)));
        NewVirtualLobbyBannerAndroid = new BOConfigParam("NewVirtualLobbyBannerAndroid", 70, bOConfigAppId2, bOConfigNamespace2, "new_virtual_lobby_banner_android", new BOConfigDeserializeOption.WithKClass(jq40.a(BannerItem[].class)));
        NewVirtualLobbyBngFloatButtonEnableAndroid = new BOConfigParam("NewVirtualLobbyBngFloatButtonEnableAndroid", 71, bOConfigAppId2, bOConfigNamespace2, "new_virtual_lobby_bng_float_button_enable_android", null, i, defaultConstructorMarker);
        int i10 = 8;
        DefaultConstructorMarker defaultConstructorMarker5 = null;
        BOConfigDeserializeOption bOConfigDeserializeOption11 = null;
        BetBuilderEnabled = new BOConfigParam("BetBuilderEnabled", 72, bOConfigAppId2, bOConfigNamespace, "bet_builder_enabled", bOConfigDeserializeOption11, i10, defaultConstructorMarker5);
        BetBuilderMaxSelectionsLimit = new BOConfigParam("BetBuilderMaxSelectionsLimit", 73, bOConfigAppId2, bOConfigNamespace, "bet_builder_max_selections_limit", bOConfigDeserializeOption11, i10, defaultConstructorMarker5);
        BetBuilderMinNumberOfSelections = new BOConfigParam("BetBuilderMinNumberOfSelections", 74, bOConfigAppId2, bOConfigNamespace, "bet_builder_min_number_of_selections", bOConfigDeserializeOption11, i10, defaultConstructorMarker5);
        BetBuilderMaxOdds = new BOConfigParam("BetBuilderMaxOdds", 75, bOConfigAppId2, bOConfigNamespace, "bet_builder_max_odds", bOConfigDeserializeOption11, i10, defaultConstructorMarker5);
        BetBuilderSupportedBetTypes = new BOConfigParam("BetBuilderSupportedBetTypes", 76, bOConfigAppId2, bOConfigNamespace, "bet_builder_supported_bet_types", new BOConfigDeserializeOption.WithKClass(jq40.a(String[].class)));
        BetBuilderExclusionFilter = new BOConfigParam("BetBuilderExclusionFilter", 77, bOConfigAppId2, bOConfigNamespace, "bet_builder_exclusion_filter", new BOConfigDeserializeOption.WithKClass(jq40.a(BetBuilderExclusionFilters.class)));
        FeaturedBetBuilderEnabled = new BOConfigParam("FeaturedBetBuilderEnabled", 78, bOConfigAppId2, bOConfigNamespace, "featured_bet_builders_enabled", null, i10, defaultConstructorMarker5);
        FeaturedBetBuilderEvents = new BOConfigParam("FeaturedBetBuilderEvents", 79, bOConfigAppId2, bOConfigNamespace, "featured_bet_builder_events", new BOConfigDeserializeOption.WithKClass(jq40.a(String[].class)));
        NewBadgeEventDetails = new BOConfigParam("NewBadgeEventDetails", 80, bOConfigAppId2, bOConfigNamespace, "android_new_badge_event_details", new BOConfigDeserializeOption.WithKClass(jq40.a(NewBadgeEventDetailsValue.class)));
        BOConfigNamespace bOConfigNamespace3 = BOConfigNamespace.COMMON;
        OddsFilterRangePreFixed = new BOConfigParam("OddsFilterRangePreFixed", 81, bOConfigAppId3, bOConfigNamespace3, "odds_filter_range_pre_fixed", new BOConfigDeserializeOption.WithKClass(jq40.a(OddsFilterEventCountData.Item[].class)));
        BOConfigAppId bOConfigAppId4 = BOConfigAppId.ORDER;
        BOConfigDeserializeOption bOConfigDeserializeOption12 = null;
        CodehubFilterToggle = new BOConfigParam("CodehubFilterToggle", 82, bOConfigAppId4, bOConfigNamespace, "codehub_filter_toggle", bOConfigDeserializeOption12, i10, defaultConstructorMarker5);
        CodeHubWorldCupEnabledAndroid = new BOConfigParam("CodeHubWorldCupEnabledAndroid", 83, bOConfigAppId4, bOConfigNamespace, "codehub_world_cup_enabled_android", bOConfigDeserializeOption12, i10, defaultConstructorMarker5);
        QuickMarketMenuToggle = new BOConfigParam("QuickMarketMenuToggle", 84, bOConfigAppId2, bOConfigNamespace, "quick_market_menu_toggle", bOConfigDeserializeOption12, i10, defaultConstructorMarker5);
        GiftGroupDisplayOrder = new BOConfigParam("GiftGroupDisplayOrder", 85, bOConfigAppId2, bOConfigNamespace, "gift_group_display_order", bOConfigDeserializeOption12, i10, defaultConstructorMarker5);
        BOConfigAppId bOConfigAppId5 = BOConfigAppId.MARKETING;
        LoyaltyProgramQualifyPopup = new BOConfigParam("LoyaltyProgramQualifyPopup", 86, bOConfigAppId5, bOConfigNamespace, "loyalty.program.qualify.popup", bOConfigDeserializeOption12, i10, defaultConstructorMarker5);
        RegisterVcodeIgnoreConfig = new BOConfigParam("RegisterVcodeIgnoreConfig", 87, BOConfigAppId.PATRON, bOConfigNamespace, "register_vcode_ignore_config", new BOConfigDeserializeOption.WithKClass(jq40.a(RegisterVCodeIgnoreConfigMap.class)));
        SimCutStatus = new BOConfigParam("SimCutStatus", 88, bOConfigAppId2, bOConfigNamespace, "sim_cutbet_status", null, i10, defaultConstructorMarker5);
        int i11 = 8;
        DefaultConstructorMarker defaultConstructorMarker6 = null;
        BOConfigDeserializeOption bOConfigDeserializeOption13 = null;
        IsEnableCodeHubLoadCode = new BOConfigParam("IsEnableCodeHubLoadCode", 89, bOConfigAppId2, bOConfigNamespace2, "is_enable_code_hub_load_code", bOConfigDeserializeOption13, i11, defaultConstructorMarker6);
        IsEnableCreateSocialPage = new BOConfigParam("IsEnableCreateSocialPage", 90, bOConfigAppId2, bOConfigNamespace2, "is_enable_create_social_page", bOConfigDeserializeOption13, i11, defaultConstructorMarker6);
        EnableCodeHubCustomCodes = new BOConfigParam("EnableCodeHubCustomCodes", 91, bOConfigAppId2, bOConfigNamespace2, "enable_code_hub_custom_codes", bOConfigDeserializeOption13, i11, defaultConstructorMarker6);
        CodeHubCustomCodePattern = new BOConfigParam("CodeHubCustomCodePattern", 92, bOConfigAppId2, bOConfigNamespace2, "code_hub_custom_code_pattern", bOConfigDeserializeOption13, i11, defaultConstructorMarker6);
        CodeHubCustomCodeSeparator = new BOConfigParam("CodeHubCustomCodeSeparator", 93, bOConfigAppId2, bOConfigNamespace2, "code_hub_custom_code_separator", bOConfigDeserializeOption13, i11, defaultConstructorMarker6);
        CodeHubCustomCodeCountLimit = new BOConfigParam("CodeHubCustomCodeCountLimit", 94, bOConfigAppId2, bOConfigNamespace, "code_hub_custom_code_count_limit", null, 8, null);
        EnableCreatorCredits = new BOConfigParam("EnableCreatorCredits", 95, bOConfigAppId2, bOConfigNamespace2, "enable_creator_credits", bOConfigDeserializeOption13, i11, defaultConstructorMarker6);
        SocialCreatorCreditsMinimumSelections = new BOConfigParam("SocialCreatorCreditsMinimumSelections", 96, bOConfigAppId2, bOConfigNamespace, "social_creator_credits_minimum_selections", null, 8, null);
        AndroidManuallyUpdateUrlGp = new BOConfigParam("AndroidManuallyUpdateUrlGp", 97, bOConfigAppId2, BOConfigNamespace.APP_INFO, "android_manually_update_url_gp", bOConfigDeserializeOption13, i11, defaultConstructorMarker6);
        SimpleKycRegisterStatusConfig = new BOConfigParam("SimpleKycRegisterStatusConfig", 98, BOConfigAppId.SERVICE_PATRON, bOConfigNamespace, "simple_kyc_register_status_config", null, 8, null);
        DynamicReplacementMarkets = new BOConfigParam("DynamicReplacementMarkets", 99, bOConfigAppId2, bOConfigNamespace, "feature.v2.dynamic_replacement_markets", new BOConfigDeserializeOption.WithKClass(jq40.a(BOConfigFeatureFlag.class)));
        GoogleAnalyticsEventFireByBackend = new BOConfigParam("GoogleAnalyticsEventFireByBackend", 100, bOConfigAppId2, bOConfigNamespace2, "google_analytics.event.fire_by_backend", bOConfigDeserializeOption13, i11, defaultConstructorMarker6);
        IsFeaturedCodeEnabled = new BOConfigParam("IsFeaturedCodeEnabled", HttpStatusCodesKt.HTTP_SWITCHING_PROTOCOLS, bOConfigAppId2, bOConfigNamespace2, "is_featured_code_enabled", bOConfigDeserializeOption13, i11, defaultConstructorMarker6);
        KeDepositRangeFreeThreshold = new BOConfigParam("KeDepositRangeFreeThreshold", HttpStatusCodesKt.HTTP_PROCESSING, bOConfigAppId, bOConfigNamespace, "deposit.range.free.threshold", null, 8, null);
        int i12 = 8;
        DefaultConstructorMarker defaultConstructorMarker7 = null;
        BOConfigDeserializeOption bOConfigDeserializeOption14 = null;
        MaxCombinationsRejectEnabled = new BOConfigParam("MaxCombinationsRejectEnabled", HttpStatusCodesKt.HTTP_EARLY_HINTS, bOConfigAppId2, bOConfigNamespace, "max_combination_reject_enabled", bOConfigDeserializeOption14, i12, defaultConstructorMarker7);
        MaxCombinationsRejectCount = new BOConfigParam("MaxCombinationsRejectCount", 104, bOConfigAppId2, bOConfigNamespace, "max_combination_reject", bOConfigDeserializeOption14, i12, defaultConstructorMarker7);
        BOConfigNamespace bOConfigNamespace4 = BOConfigNamespace.FACTS_CENTER;
        AnyWinStatus = new BOConfigParam("AnyWinStatus", 105, bOConfigAppId2, bOConfigNamespace4, "anywin_status", bOConfigDeserializeOption13, i11, defaultConstructorMarker6);
        int i13 = 8;
        DefaultConstructorMarker defaultConstructorMarker8 = null;
        BOConfigDeserializeOption bOConfigDeserializeOption15 = null;
        AnyWinMinOdds = new BOConfigParam("AnyWinMinOdds", 106, bOConfigAppId2, bOConfigNamespace, "anywin_min_odds", bOConfigDeserializeOption15, i13, defaultConstructorMarker8);
        AnyWinMinSelectionOdds = new BOConfigParam("AnyWinMinSelectionOdds", 107, bOConfigAppId2, bOConfigNamespace, "anywin_min_sele_odds", bOConfigDeserializeOption15, i13, defaultConstructorMarker8);
        AnyWinMinSelectionNumber = new BOConfigParam("AnyWinMinSelectionNumber", 108, bOConfigAppId2, bOConfigNamespace, "anywin_min_sele_num", bOConfigDeserializeOption15, i13, defaultConstructorMarker8);
        AnyWinMaxSelectionNumber = new BOConfigParam("AnyWinMaxSelectionNumber", 109, bOConfigAppId2, bOConfigNamespace, "anywin_max_sele_num", bOConfigDeserializeOption15, i13, defaultConstructorMarker8);
        FlexiBetWeightedRTPEnabled = new BOConfigParam("FlexiBetWeightedRTPEnabled", 110, bOConfigAppId2, bOConfigNamespace, "flexi_weighted_rtp_enabled", bOConfigDeserializeOption15, i13, defaultConstructorMarker8);
        FlexiBetAverageWeightedRTPMultiplier = new BOConfigParam("FlexiBetAverageWeightedRTPMultiplier", 111, bOConfigAppId2, bOConfigNamespace, "flexi_average_weighted_rtp_multiplier", bOConfigDeserializeOption15, i13, defaultConstructorMarker8);
        FlexiBetOddsKey = new BOConfigParam("FlexiBetOddsKey", 112, bOConfigAppId2, bOConfigNamespace4, "flexible_bet_oddskey", bOConfigDeserializeOption13, i11, defaultConstructorMarker6);
        FlexiBetOddsKeyTable = new BOConfigParam("FlexiBetOddsKeyTable", 113, bOConfigAppId2, bOConfigNamespace4, "flexible_bet_oddskey_table", new BOConfigDeserializeOption.WithKClass(jq40.a(FlexiBetBoConfigOddsKey[].class)));
        FlexiBetStatus = new BOConfigParam("FlexiBetStatus", 114, bOConfigAppId2, bOConfigNamespace4, "flexible_bet_status", null, i11, defaultConstructorMarker6);
        int i14 = 8;
        DefaultConstructorMarker defaultConstructorMarker9 = null;
        BOConfigDeserializeOption bOConfigDeserializeOption16 = null;
        FlexiBetMinOdds = new BOConfigParam("FlexiBetMinOdds", 115, bOConfigAppId2, bOConfigNamespace, "flexible_min_odds", bOConfigDeserializeOption16, i14, defaultConstructorMarker9);
        FlexiBetWeightedRTPSupportedMinVersion = new BOConfigParam("FlexiBetWeightedRTPSupportedMinVersion", 116, bOConfigAppId2, bOConfigNamespace, "flexi_weighted_rtp_supported_android_app_min_ver", bOConfigDeserializeOption16, i14, defaultConstructorMarker9);
        FlexiBetAverageWeightedRTPMinimum = new BOConfigParam("FlexiBetAverageWeightedRTPMinimum", 117, bOConfigAppId2, bOConfigNamespace, "flexi_average_weighted_rtp_min", bOConfigDeserializeOption16, i14, defaultConstructorMarker9);
        OlderBetHistoryMonth = new BOConfigParam("OlderBetHistoryMonth", 118, bOConfigAppId4, bOConfigNamespace, "max_bet_history_access_months", bOConfigDeserializeOption16, i14, defaultConstructorMarker9);
        BetHistoryRefreshDebounceMs = new BOConfigParam("BetHistoryRefreshDebounceMs", 119, bOConfigAppId4, bOConfigNamespace, "bet_history_refresh_debounce_time", bOConfigDeserializeOption16, i14, defaultConstructorMarker9);
        GiftReminderEnabledAddToStake = new BOConfigParam("GiftReminderEnabledAddToStake", 120, bOConfigAppId4, bOConfigNamespace, "gift_reminder_enabled_add_to_stake", bOConfigDeserializeOption16, i14, defaultConstructorMarker9);
        GiftReminderEnabledUserIdSuffix = new BOConfigParam("GiftReminderEnabledUserIdSuffix", 121, bOConfigAppId4, bOConfigNamespace, "gift_reminder_enabled_user_id_suffix", bOConfigDeserializeOption16, i14, defaultConstructorMarker9);
        MissionProgressEnabledAddToBetslip = new BOConfigParam("MissionProgressEnabledAddToBetslip", 122, bOConfigAppId4, bOConfigNamespace, "mission_progress_enabled_add_to_betslip", bOConfigDeserializeOption16, i14, defaultConstructorMarker9);
        AutoBetEnabled = new BOConfigParam("AutoBetEnabled", 123, bOConfigAppId4, bOConfigNamespace, "auto_bet_enabled", bOConfigDeserializeOption16, i14, defaultConstructorMarker9);
        AutoBetActive = new BOConfigParam("AutoBetActive", 124, bOConfigAppId4, bOConfigNamespace, "auto_bet_active", bOConfigDeserializeOption16, i14, defaultConstructorMarker9);
        AutoBetMatchMaxDays = new BOConfigParam("AutoBetMatchMaxDays", 125, bOConfigAppId4, bOConfigNamespace, "auto_bet_max_days_before_match", bOConfigDeserializeOption16, i14, defaultConstructorMarker9);
        AutoBetMaxActiveSettingPerUser = new BOConfigParam("AutoBetMaxActiveSettingPerUser", WebSocketProtocol.PAYLOAD_SHORT, bOConfigAppId4, bOConfigNamespace, "auto_bet_max_active_settings_per_user", bOConfigDeserializeOption16, i14, defaultConstructorMarker9);
        MissionProgressEnabledUserIdSuffix = new BOConfigParam("MissionProgressEnabledUserIdSuffix", 127, bOConfigAppId4, bOConfigNamespace, "mission_progress_enabled_user_id_suffix", bOConfigDeserializeOption16, i14, defaultConstructorMarker9);
        AutoBetMaxOdds = new BOConfigParam("AutoBetMaxOdds", 128, bOConfigAppId4, bOConfigNamespace, "auto_bet_max_odds", bOConfigDeserializeOption16, i14, defaultConstructorMarker9);
        AutoBetMinOdds = new BOConfigParam("AutoBetMinOdds", 129, bOConfigAppId4, bOConfigNamespace, "auto_bet_min_odds", bOConfigDeserializeOption16, i14, defaultConstructorMarker9);
        MarketsTabsOrder = new BOConfigParam("MarketsTabsOrder", 130, bOConfigAppId3, bOConfigNamespace3, "markets_tabs_order", new BOConfigDeserializeOption.WithKClass(jq40.a(Map.class)));
        HangWatchdogConfig = new BOConfigParam("HangWatchdogConfig", 131, bOConfigAppId2, bOConfigNamespace2, "android_watchdog_config", new BOConfigDeserializeOption.WithKClass(jq40.a(HangWatchdogConfigData.class)));
        BOConfigAppId bOConfigAppId6 = BOConfigAppId.SERVICE_REAL_SPORTS_GAME;
        int i15 = 8;
        DefaultConstructorMarker defaultConstructorMarker10 = null;
        CashoutSuspendDeactivateEnabled = new BOConfigParam("CashoutSuspendDeactivateEnabled", 132, bOConfigAppId6, bOConfigNamespace, "cashout_suspend_deactivate_enabled", null, i15, defaultConstructorMarker10);
        CashoutSuspendDeactivateAllow = new BOConfigParam("CashoutSuspendDeactivateAllow", 133, bOConfigAppId6, bOConfigNamespace, "cashout_suspend_deactivate_allow", new BOConfigDeserializeOption.WithKClass(jq40.a(CashoutSuspendDeactivateAllowConfigs.class)));
        CashoutSuspendDeactivatePhase = new BOConfigParam("CashoutSuspendDeactivatePhase", 134, bOConfigAppId6, bOConfigNamespace, "cashout_suspend_deactivate_phase", null, i15, defaultConstructorMarker10);
        CashoutSuspendDeactivateAdditionalMarketSpecifier = new BOConfigParam("CashoutSuspendDeactivateAdditionalMarketSpecifier", 135, bOConfigAppId6, bOConfigNamespace, "cashout_suspend_deactivate_additional_market_specifier", new BOConfigDeserializeOption.WithKClass(jq40.a(CashoutAdditionalMarketSpecifierMap.class)));
        BOConfigDeserializeOption bOConfigDeserializeOption17 = null;
        CashoutOutcomeActiveEnabled = new BOConfigParam("CashoutOutcomeActiveEnabled", 136, bOConfigAppId6, bOConfigNamespace, "cashout_outcome_active_enabled", bOConfigDeserializeOption17, i15, defaultConstructorMarker10);
        CashoutMarketActiveEnabled = new BOConfigParam("CashoutMarketActiveEnabled", 137, bOConfigAppId6, bOConfigNamespace, "cashout_market_active_enabled", bOConfigDeserializeOption17, i15, defaultConstructorMarker10);
        CashoutNewFeedEnabled = new BOConfigParam("CashoutNewFeedEnabled", 138, bOConfigAppId6, bOConfigNamespace, "cash_out_new_feed_enabled", bOConfigDeserializeOption17, i15, defaultConstructorMarker10);
        CashoutEventAbandonedEnabled = new BOConfigParam("CashoutEventAbandonedEnabled", 139, bOConfigAppId6, bOConfigNamespace, LGxrN.nUCSOCDVqsHcKYm, bOConfigDeserializeOption17, i15, defaultConstructorMarker10);
        CashoutFallbackEnabled = new BOConfigParam("CashoutFallbackEnabled", 140, bOConfigAppId6, bOConfigNamespace, "cashout_fallback_enable", bOConfigDeserializeOption17, i15, defaultConstructorMarker10);
        CashoutFallbackMinCapEnabled = new BOConfigParam("CashoutFallbackMinCapEnabled", 141, bOConfigAppId6, bOConfigNamespace, "cashout_fallback_min_cap_enable", bOConfigDeserializeOption17, i15, defaultConstructorMarker10);
        CashoutFlexibleBetAllow = new BOConfigParam("CashoutFlexibleBetAllow", 142, bOConfigAppId6, bOConfigNamespace, "cashout_flexible_bet_allow", bOConfigDeserializeOption17, i15, defaultConstructorMarker10);
        CashoutAnyWinAllow = new BOConfigParam("CashoutAnyWinAllow", 143, bOConfigAppId6, bOConfigNamespace, "cashout_anywin_allow", bOConfigDeserializeOption17, i15, defaultConstructorMarker10);
        CashoutSupportGiftEnabled = new BOConfigParam("CashoutSupportGiftEnabled", 144, bOConfigAppId6, bOConfigNamespace, "cashout_support_gift_enabled", bOConfigDeserializeOption17, i15, defaultConstructorMarker10);
        CashoutHighProbabilityAllow = new BOConfigParam("CashoutHighProbabilityAllow", 145, bOConfigAppId6, bOConfigNamespace, "cashout_high_probability_allow", bOConfigDeserializeOption17, i15, defaultConstructorMarker10);
        CashoutQuickReinvestEnabled = new BOConfigParam("CashoutQuickReinvestEnabled", 146, bOConfigAppId2, bOConfigNamespace, "cashout_quick_reinvest_enabled_android", new BOConfigDeserializeOption.WithKClass(jq40.a(CashoutQuickReinvestConfig.class)));
        BOConfigDeserializeOption bOConfigDeserializeOption18 = null;
        CashoutHighProbabilityAllowBound = new BOConfigParam("CashoutHighProbabilityAllowBound", 147, bOConfigAppId6, bOConfigNamespace, "cashout_high_probability_allow_bound", bOConfigDeserializeOption18, i15, defaultConstructorMarker10);
        CashoutFlexibleBetRealTimeAmountDisplay = new BOConfigParam("CashoutFlexibleBetRealTimeAmountDisplay", 148, bOConfigAppId6, bOConfigNamespace, "cashout_flexible_bet_real_time_amount_display", bOConfigDeserializeOption18, i15, defaultConstructorMarker10);
        CashoutDetailThrottleInterval = new BOConfigParam("CashoutDetailThrottleInterval", 149, bOConfigAppId2, bOConfigNamespace, "cashout_detail_throttle_interval", bOConfigDeserializeOption18, i15, defaultConstructorMarker10);
        CashoutProviderMarketRules = new BOConfigParam("CashoutProviderMarketRules", 150, bOConfigAppId6, bOConfigNamespace, "cashout_provider_market_rules", new BOConfigDeserializeOption.WithKClass(jq40.a(CashoutProviderMarketRulesMap.class)));
        BuildAndGoFeaturedTabConfig = new BOConfigParam("BuildAndGoFeaturedTabConfig", 151, bOConfigAppId2, bOConfigNamespace2, "build_and_go_featured_tab_config", new BOConfigDeserializeOption.WithKClass(jq40.a(BuildAndGoTabConfig.class)));
        MomoPhonePrefixData = new BOConfigParam("MomoPhonePrefixData", 152, bOConfigAppId2, bOConfigNamespace2, "phone_number_prefix", new BOConfigDeserializeOption.WithKClass(jq40.a(PhonePrefixData[].class)));
        EarlyPayoutConfig = new BOConfigParam("EarlyPayoutConfig", 153, bOConfigAppId2, bOConfigNamespace, "early_payout_config", new BOConfigDeserializeOption.WithKClass(jq40.a(EarlyPayoutConfigModel.class)));
        int i16 = 8;
        DefaultConstructorMarker defaultConstructorMarker11 = null;
        DefaultSportyInsureUpsType = new BOConfigParam("DefaultSportyInsureUpsType", 154, bOConfigAppId2, bOConfigNamespace, "default_sporty_insure_ups_type", null, i16, defaultConstructorMarker11);
        StaleOddsAutoRefresh = new BOConfigParam("StaleOddsAutoRefresh", ModuleDescriptor.MODULE_VERSION, bOConfigAppId2, bOConfigNamespace, "stale_odds_auto_refresh_android", new BOConfigDeserializeOption.WithKClass(jq40.a(Map.class)));
        DisplayNewForDobBenefitCard = new BOConfigParam("DisplayNewForDobBenefitCard", 156, bOConfigAppId5, bOConfigNamespace, "loyalty_benefit_card_dob_gift_new_badge_show", null, i16, defaultConstructorMarker11);
        InstantWinPromotionConfig = new BOConfigParam("InstantWinPromotionConfig", 157, bOConfigAppId2, bOConfigNamespace, "virtual_promotion_popup", new BOConfigDeserializeOption.WithKClass(jq40.a(InstantWinPromotionData.class)));
        BoreDrawSelectionEligibility = new BOConfigParam("BoreDrawSelectionEligibility", 158, bOConfigAppId2, bOConfigNamespace, "bore_draw_selection_eligibility", new BOConfigDeserializeOption.WithKClass(jq40.a(BoreDrawSelectionEligibilityDto.class)));
        BOConfigDeserializeOption bOConfigDeserializeOption19 = null;
        OddsBoostCashoutable = new BOConfigParam("OddsBoostCashoutable", 159, bOConfigAppId2, bOConfigNamespace, "odds_boost_cashoutable", bOConfigDeserializeOption19, i16, defaultConstructorMarker11);
        SimpleStandardBetSlipEnabled = new BOConfigParam("SimpleStandardBetSlipEnabled", 160, bOConfigAppId2, bOConfigNamespace, "android_simple_standard_betslip_enabled", bOConfigDeserializeOption19, i16, defaultConstructorMarker11);
        IsPostBetUpsellEnabled = new BOConfigParam("IsPostBetUpsellEnabled", 161, bOConfigAppId2, bOConfigNamespace, "post_bet_upsell_enabled", bOConfigDeserializeOption19, i16, defaultConstructorMarker11);
        RecommendedPostBetUpsellGame = new BOConfigParam("RecommendedPostBetUpsellGame", 162, bOConfigAppId2, bOConfigNamespace, "recommended_game_id", bOConfigDeserializeOption19, i16, defaultConstructorMarker11);
        OddsBoostFlashBoostEnabled = new BOConfigParam("OddsBoostFlashBoostEnabled", 163, bOConfigAppId2, bOConfigNamespace, "feature.v2.liability_flash_boost", new BOConfigDeserializeOption.WithKClass(jq40.a(BOConfigFeatureFlag.class)));
        OddsBoostPrematchBoostEnabled = new BOConfigParam("OddsBoostPrematchBoostEnabled", 164, bOConfigAppId2, bOConfigNamespace, "feature.v2.prematch_boost", new BOConfigDeserializeOption.WithKClass(jq40.a(BOConfigFeatureFlag.class)));
        BOConfigDeserializeOption bOConfigDeserializeOption20 = null;
        AndroidMiniGamesOpenBetsEnabled = new BOConfigParam("AndroidMiniGamesOpenBetsEnabled", 165, bOConfigAppId2, bOConfigNamespace, "android_mini_games_open_bets_enabled", bOConfigDeserializeOption20, i16, defaultConstructorMarker11);
        RemixBetEnabled = new BOConfigParam("RemixBetEnabled", 166, bOConfigAppId4, bOConfigNamespace, "feature_remix_bet_enabled", bOConfigDeserializeOption20, i16, defaultConstructorMarker11);
        SportySocialCodeChatEnabled = new BOConfigParam("SportySocialCodeChatEnabled", 167, bOConfigAppId2, bOConfigNamespace, "sporty_social_code_chat_enabled", new BOConfigDeserializeOption.WithKClass(jq40.a(CodeChatBOConfigModel.class)));
        SportySocialCodeChatThreshold = new BOConfigParam("SportySocialCodeChatThreshold", 168, bOConfigAppId2, bOConfigNamespace, "code_chat_popularity_threshold_visibility", null, i16, defaultConstructorMarker11);
        SportySocialNewShareFlowEnabled = new BOConfigParam("SportySocialNewShareFlowEnabled", 169, bOConfigAppId2, bOConfigNamespace, "sporty_social_new_share_flow_enabled_android", new BOConfigDeserializeOption.WithKClass(jq40.a(ShareMyBetBOConfigModel.class)));
        BOConfigDeserializeOption bOConfigDeserializeOption21 = null;
        SportySocialForYouEnabledAndroid = new BOConfigParam("SportySocialForYouEnabledAndroid", 170, bOConfigAppId2, bOConfigNamespace, "sporty_social_for_you_enabled_android", bOConfigDeserializeOption21, i16, defaultConstructorMarker11);
        SportySocialEditUsernameEnabled = new BOConfigParam("SportySocialEditUsernameEnabled", 171, bOConfigAppId2, bOConfigNamespace, "sporty_social_edit_username_enabled_app", bOConfigDeserializeOption21, i16, defaultConstructorMarker11);
        RequireFTDForLiveStreaming = new BOConfigParam("RequireFTDForLiveStreaming", 172, bOConfigAppId2, bOConfigNamespace, "media.event.livestream.require_ftd", bOConfigDeserializeOption21, i16, defaultConstructorMarker11);
        IncludeMAIDInUserMetadata = new BOConfigParam("IncludeMAIDInUserMetadata", 173, bOConfigAppId2, bOConfigNamespace, "marketing.user_metadata.collect_maid", bOConfigDeserializeOption21, i16, defaultConstructorMarker11);
        SportyJokerEnabled = new BOConfigParam("SportyJokerEnabled", 174, bOConfigAppId2, bOConfigNamespace, "android_joker_enabled_v2", bOConfigDeserializeOption21, i16, defaultConstructorMarker11);
        GamesForYouEnabled = new BOConfigParam("GamesForYouEnabled", 175, bOConfigAppId2, bOConfigNamespace, "android_games_for_you_enabled_v2", bOConfigDeserializeOption21, i16, defaultConstructorMarker11);
        DedicatedTeamPageEnabled = new BOConfigParam("DedicatedTeamPageEnabled", 176, bOConfigAppId2, bOConfigNamespace, "feature.v2.dedicated_team_page", new BOConfigDeserializeOption.WithKClass(jq40.a(BOConfigFeatureFlag.class)));
        FifaWorldCupTournamentIds = new BOConfigParam("FifaWorldCupTournamentIds", 177, bOConfigAppId6, bOConfigNamespace, "fifa_world_cup_tournament_ids", new BOConfigDeserializeOption.WithKClass(jq40.a(String[].class)));
        MegaBetBuilder = new BOConfigParam("MegaBetBuilder", 178, bOConfigAppId2, bOConfigNamespace, "feature.v2.mega_bet_builder", new BOConfigDeserializeOption.WithKClass(jq40.a(BOConfigFeatureFlag.class)));
        WorldCupTournamentPageConfig = new BOConfigParam("WorldCupTournamentPageConfig", 179, bOConfigAppId2, bOConfigNamespace, "feature.v2.world_cup_tournament_page", new BOConfigDeserializeOption.WithKClass(jq40.a(BOConfigFeatureFlag.class)));
        MultipleBetCashoutSimRebet = new BOConfigParam("MultipleBetCashoutSimRebet", 180, bOConfigAppId2, bOConfigNamespace, "feature.v2.multiple_bet_cashout_sim_rebet", new BOConfigDeserializeOption.WithKClass(jq40.a(BOConfigFeatureFlag.class)));
        SportyPicks = new BOConfigParam("SportyPicks", 181, bOConfigAppId2, bOConfigNamespace, "feature.v2.sporty_picks", new BOConfigDeserializeOption.WithKClass(jq40.a(BOConfigFeatureFlag.class)));
        WorldCupTournamentPageTeams = new BOConfigParam("WorldCupTournamentPageTeams", 182, bOConfigAppId2, bOConfigNamespace, "world_cup_tournament_page_teams", new BOConfigDeserializeOption.WithKClass(jq40.a(WorldCupTeam[].class)));
        WorldCupTournamentPageGroups = new BOConfigParam("WorldCupTournamentPageGroups", 183, bOConfigAppId2, bOConfigNamespace, "world_cup_tournament_page_groups", new BOConfigDeserializeOption.WithKClass(jq40.a(WorldCupTournamentPageGroup[].class)));
        VirtualInHouseGamePromotionBanner = new BOConfigParam("VirtualInHouseGamePromotionBanner", 184, bOConfigAppId2, bOConfigNamespace, "virtual_in_house_game_promotion_banner", new BOConfigDeserializeOption.WithKClass(jq40.a(NetworkVirtualInHouseGamePromotionBanner.class)));
        BOConfigDeserializeOption bOConfigDeserializeOption22 = null;
        CashoutUnavailableClickMetricsDebounceMs = new BOConfigParam("CashoutUnavailableClickMetricsDebounceMs", 185, bOConfigAppId6, bOConfigNamespace, "cashout_unavailable_click_metrics_debounce_ms", bOConfigDeserializeOption22, i16, defaultConstructorMarker11);
        OpenBetRefreshDebounceTime = new BOConfigParam("OpenBetRefreshDebounceTime", 186, bOConfigAppId6, bOConfigNamespace, "open_bet_refresh_debounce_time", bOConfigDeserializeOption22, i16, defaultConstructorMarker11);
        CashoutMetricsSamplingUserIdTail = new BOConfigParam("CashoutMetricsSamplingUserIdTail", 187, bOConfigAppId2, bOConfigNamespace, "cashout_metrics_sampling_user_id_tail_android", new BOConfigDeserializeOption.WithKClass(jq40.a(CashOutMetricsSamplingUserIdTailDto[].class)));
        MissionCompletedGamesCarouselBottomSheetEnabled = new BOConfigParam("MissionCompletedGamesCarouselBottomSheetEnabled", 188, bOConfigAppId2, bOConfigNamespace, "feature.v2.missions_games_cross_selling_dialog", new BOConfigDeserializeOption.WithKClass(jq40.a(BOConfigFeatureFlag.class)));
        BOConfigDeserializeOption bOConfigDeserializeOption23 = null;
        LuckyNumberModuleEnabled = new BOConfigParam("LuckyNumberModuleEnabled", 189, BOConfigAppId.NUMBER_GAME, bOConfigNamespace, "module.enable", bOConfigDeserializeOption23, i16, defaultConstructorMarker11);
        WinningPopupAudioResource = new BOConfigParam("WinningPopupAudioResource", 190, bOConfigAppId2, bOConfigNamespace, "winning_popup_audio_resource", bOConfigDeserializeOption23, i16, defaultConstructorMarker11);
        StakeDefaultAmount = new BOConfigParam("StakeDefaultAmount", 191, bOConfigAppId2, bOConfigNamespace, "default_stake", bOConfigDeserializeOption23, i16, defaultConstructorMarker11);
        StakeMinAmount = new BOConfigParam("StakeMinAmount", 192, bOConfigAppId2, bOConfigNamespace, "min_stake", bOConfigDeserializeOption23, i16, defaultConstructorMarker11);
        StakeMaxAmount = new BOConfigParam("StakeMaxAmount", 193, bOConfigAppId2, bOConfigNamespace, "max_stake", bOConfigDeserializeOption23, i16, defaultConstructorMarker11);
        StakeMinCashoutAmount = new BOConfigParam("StakeMinCashoutAmount", 194, bOConfigAppId6, bOConfigNamespace, "min_cashout_amount", bOConfigDeserializeOption23, i16, defaultConstructorMarker11);
        StakeMaxCashoutAmount = new BOConfigParam("StakeMaxCashoutAmount", 195, bOConfigAppId6, bOConfigNamespace, "max_cashout_amount", bOConfigDeserializeOption23, i16, defaultConstructorMarker11);
        StakeMaxPayoutAmount = new BOConfigParam("StakeMaxPayoutAmount", 196, bOConfigAppId2, bOConfigNamespace, "potwin_max_value", bOConfigDeserializeOption23, i16, defaultConstructorMarker11);
        StakeQuickAmount1 = new BOConfigParam("StakeQuickAmount1", 197, bOConfigAppId2, bOConfigNamespace, "numberpad_quick_button1", bOConfigDeserializeOption23, i16, defaultConstructorMarker11);
        StakeQuickAmount2 = new BOConfigParam("StakeQuickAmount2", 198, bOConfigAppId2, bOConfigNamespace, "numberpad_quick_button2", bOConfigDeserializeOption23, i16, defaultConstructorMarker11);
        StakeQuickAmount3 = new BOConfigParam("StakeQuickAmount3", 199, bOConfigAppId2, bOConfigNamespace, "numberpad_quick_button3", bOConfigDeserializeOption23, i16, defaultConstructorMarker11);
        StakeMaxSelectionLimit = new BOConfigParam("StakeMaxSelectionLimit", r.d.DEFAULT_DRAG_ANIMATION_DURATION, bOConfigAppId2, bOConfigNamespace, "selections_max_value", bOConfigDeserializeOption23, i16, defaultConstructorMarker11);
        StakeBettorLimitLossDefault = new BOConfigParam("StakeBettorLimitLossDefault", 201, bOConfigAppId2, bOConfigNamespace, "bettor_limit_loss_default", bOConfigDeserializeOption23, i16, defaultConstructorMarker11);
        StakeBettorLimitTimeDefault = new BOConfigParam("StakeBettorLimitTimeDefault", 202, bOConfigAppId2, bOConfigNamespace, "bettor_limit_time_default", bOConfigDeserializeOption23, i16, defaultConstructorMarker11);
        SetPasswordV2EnabledCountries = new BOConfigParam("SetPasswordV2EnabledCountries", 203, bOConfigAppId2, bOConfigNamespace, "set_password_v2_enabled_countries", new BOConfigDeserializeOption.WithKClass(jq40.a(String[].class)));
        NewSearchScreen = new BOConfigParam("NewSearchScreen", 204, bOConfigAppId2, bOConfigNamespace, "feature.v2.new_search_screen", new BOConfigDeserializeOption.WithKClass(jq40.a(BOConfigFeatureFlag.class)));
        BOConfigParam[] bOConfigParamArr$values = $values();
        $VALUES = bOConfigParamArr$values;
        $ENTRIES = om2.a(bOConfigParamArr$values);
    }

    private BOConfigParam(String str, int i, BOConfigAppId bOConfigAppId, BOConfigNamespace bOConfigNamespace, String str2, BOConfigDeserializeOption bOConfigDeserializeOption) {
        super(str, i);
        this.appId = bOConfigAppId;
        this.namespace = bOConfigNamespace;
        this.configKey = str2;
        this.deserializeOption = bOConfigDeserializeOption;
    }
}
