# Generated by Django 5.2.17 on 2026-09-27 19:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "support_email",
                    models.EmailField(default="akilainnocent@pm.me", max_length=254),
                ),
                (
                    "payment_phone",
                    models.CharField(
                        default="255629645877",
                        max_length=16,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+?[1-9]\\d{6,14}$"
                            )
                        ],
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        default="Payment confirmation is manual. Contact support for assistance.",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Site settings",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)), name="singleton_settings"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=200)),
                (
                    "phone",
                    models.CharField(blank=True, max_length=16, null=True, unique=True),
                ),
                ("trial_consumed", models.BooleanField(default=False, editable=False)),
                ("trial_start", models.DateTimeField(blank=True, null=True)),
                ("trial_end", models.DateTimeField(blank=True, null=True)),
                ("paid_until", models.DateTimeField(blank=True, null=True)),
                ("suspended", models.BooleanField(default=False)),
                ("suspension_reason", models.CharField(blank=True, max_length=300)),
                (
                    "auth_version",
                    models.PositiveIntegerField(default=1, editable=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="TZS",
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{3}$",
                                "Use a three-letter uppercase currency code.",
                            )
                        ],
                    ),
                ),
                ("paid_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("reference", models.CharField(max_length=120, unique=True)),
                (
                    "months",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(120),
                        ],
                    ),
                ),
                (
                    "idempotency_key",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("confirmed", models.BooleanField(default=False)),
                ("period_start", models.DateTimeField(editable=False, null=True)),
                ("period_end", models.DateTimeField(editable=False, null=True)),
                ("applied_at", models.DateTimeField(editable=False, null=True)),
                ("note", models.TextField(blank=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="accounts.subscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-paid_at", "-pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("trial_end__isnull", True), ("trial_start__isnull", True)
                    ),
                    models.Q(
                        ("trial_end__gt", models.F("trial_start")),
                        ("trial_start__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="valid_trial_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="positive_payment"
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("months__gte", 1), ("months__lte", 120)),
                name="valid_payment_months",
            ),
        ),
    ]
