# Generated by Django 5.2.17 on 2026-09-27 19:43

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_identity_settings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="subscription",
            name="valid_trial_period",
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("trial_end__isnull", True), ("trial_start__isnull", True)
                    ),
                    models.Q(
                        ("trial_end__gt", models.F("trial_start")),
                        ("trial_end__isnull", False),
                        ("trial_start__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="valid_trial_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("phone__isnull", True),
                    ("phone__regex", "^\\+[1-9][0-9]{6,14}$"),
                    _connector="OR",
                ),
                name="canonical_phone",
            ),
        ),
    ]
